import type { GrammarFeatures } from "../types";

export const DEFAULT_GRAMMAR: GrammarFeatures = {
  wordOrder: "SOV",
  affixPosition: "suffix",
  pluralMarking: "affix",
  tenseMarking: "past",
  hasCase: true,
  genderCount: 2,
  synthesisIndex: 2.0,
  fusionIndex: 0.5,
  articlePresence: "none",
  caseStrategy: "case",
  incorporates: false,
  classifierSystem: false,
  prodrop: false,
  adjectivePosition: "pre",
  possessorPosition: "pre",
  numeralPosition: "pre",
  negationPosition: "pre-verb",
  aspectMarking: "none",
  voice: "active",
  moodMarking: "declarative",
  interrogativeStrategy: "intonation",
  interrogativeParticle: "final",
};
