import type { FeatureQuery } from "./features";

/**
 * Type-only declarations for procedurally-generated phonological rules.
 * Lives separately from `generated.ts` so `engine/types.ts` can refer to
 * `GeneratedRule` (via `Language.activeRules`) without importing the
 * runtime module — which itself depends on `engine/types.ts` and would
 * otherwise create an import cycle.
 */
export type RuleFamily =
  | "lenition"
  | "fortition"
  | "place_assim"
  | "palatalization"
  | "vowel_shift"
  | "vowel_reduction"
  | "harmony"
  | "deletion"
  | "metathesis"
  | "tone";

/**
 * Context in which a rule applies. Any field set to undefined = "don't care".
 */
export interface RuleContext {
  /** Match the segment immediately before the target. */
  before?: FeatureQuery | "#" | "any";
  /** Match the segment immediately after the target. */
  after?: FeatureQuery | "#" | "any";
  /** "intervocalic" = both neighbours are vowels; "edge" = at a word boundary. */
  locus?: "intervocalic" | "onset" | "coda" | "edge" | "any";
  /** "initial" / "medial" / "final" relative to the word. */
  position?: "initial" | "medial" | "final" | "any";
}

/**
 * A concrete rule generated by a template. It carries everything needed to
 * match phonemes in a word and produce an output phoneme per match.
 */
export interface GeneratedRule {
  id: string;
  family: RuleFamily;
  templateId: string;
  description: string;
  /** Birth generation (for UI). */
  birthGeneration: number;
  /** Retirement generation — set when strength falls and the rule dies. */
  deathGeneration?: number;
  /**
   * In [0, 1]. Starts at ~0.3; grows when the rule finds inputs and applies
   * cleanly, decays when it can't find inputs or the inventory evicts them.
   */
  strength: number;
  /** Last generation in which this rule fired at least once. */
  lastFireGeneration: number;
  /** Source-side feature query (what phonemes the rule matches). */
  from: FeatureQuery;
  /** Context that must hold around each match. */
  context: RuleContext;
  /**
   * Substitution map: matched phoneme → output phoneme. Templates that shift
   * features fill this when they propose. An input without an entry is left
   * unchanged (ensures we never emit an unknown segment).
   */
  outputMap: Record<string, string>;
}
