import type { Meaning } from "../types";
import type { POS } from "./pos";

/**
 * Expanded concept registry — adds tier-1 (agricultural), tier-2
 * (iron-age), and tier-3 (modern) vocabulary to what BASIC_240 ships.
 *
 * Kept separate from `BASIC_240` (in `basic240.ts`) on purpose:
 *
 *   - `BASIC_240` is the **proto-seed pool** that every preset's
 *     `fillMissing` populates at gen 0. Adding a tier-3 concept like
 *     "telegraph" there would cause Proto-Indo-European to ship with
 *     a word for "telegraph" — absurd.
 *   - This module is consumed only by `concepts.ts::CONCEPTS` so it
 *     enters the dictionary at concept-registry level. The tier
 *     gate in `genesis/need.ts::lexicalNeed` then prevents
 *     low-tier languages from coining for tier-2/3 concepts until
 *     they advance.
 *
 * Each concept here ships with explicit POS + cluster + tier so we
 * don't have to thread the new vocabulary through `pos.ts`,
 * `clusters.ts`, and `TIER_OVERRIDES` separately.
 */

export interface ExpandedConcept {
  id: Meaning;
  pos: POS;
  cluster: string;
  tier: 0 | 1 | 2 | 3;
}

// Helpers so the per-tier arrays below stay readable.
function noun(id: string, cluster: string, tier: 0 | 1 | 2 | 3): ExpandedConcept {
  return { id, pos: "noun", cluster, tier };
}
function verb(id: string, cluster: string, tier: 0 | 1 | 2 | 3): ExpandedConcept {
  return { id, pos: "verb", cluster, tier };
}
function adj(id: string, cluster: string, tier: 0 | 1 | 2 | 3): ExpandedConcept {
  return { id, pos: "adjective", cluster, tier };
}

// ---------------------------------------------------------------------------
// Tier 1 — agricultural / neolithic
// ---------------------------------------------------------------------------

const TIER_1: ExpandedConcept[] = [
  // Crops + cultivars (most field crops are already in BASIC_240,
  // these add the cultivar diversity that any agriculturally-aware
  // language eventually develops vocabulary for)
  noun("rye", "plants", 1),
  noun("oat", "plants", 1),
  noun("millet", "plants", 1),
  noun("sorghum", "plants", 1),
  noun("yam", "plants", 1),
  noun("taro", "plants", 1),
  noun("cassava", "plants", 1),
  noun("lentil", "plants", 1),
  noun("chickpea", "plants", 1),
  noun("flax", "plants", 1),
  noun("hemp", "plants", 1),
  noun("cotton", "plants", 1),
  noun("orchard", "environment", 1),
  noun("vineyard", "environment", 1),
  noun("garden", "environment", 1),
  noun("furrow", "environment", 1),
  noun("granary", "tools", 1),
  noun("barn", "tools", 1),
  noun("stable", "tools", 1),
  noun("pen", "tools", 1),
  noun("fence", "tools", 1),
  noun("well-water", "tools", 1),

  // Animal husbandry
  noun("herd", "animals", 1),
  noun("flock", "animals", 1),
  noun("yoke-pair", "tools", 1),
  noun("bridle-rein", "tools", 1),
  noun("shepherd", "kinship", 1),
  noun("herder", "kinship", 1),
  noun("milkmaid", "kinship", 1),
  noun("dairy", "tools", 1),

  // Food preparation + cuisine
  noun("yoghurt", "food", 1),
  noun("curds", "food", 1),
  noun("whey", "food", 1),
  noun("mead", "food", 1),
  noun("vinegar", "food", 1),
  noun("salt-pork", "food", 1),
  noun("dried-fruit", "food", 1),
  noun("preserve", "food", 1),
  noun("ferment", "food", 1),
  noun("oven", "tools", 1),
  noun("hearth-stone", "tools", 1),
  noun("kettle", "tools", 1),
  noun("cauldron", "tools", 1),
  noun("ladle", "tools", 1),
  noun("mortar-bowl", "tools", 1),
  noun("pestle", "tools", 1),
  noun("sieve", "tools", 1),
  noun("strainer", "tools", 1),
  verb("knead", "action", 1),
  verb("ferment-v", "action", 1),
  verb("brew", "action", 1),
  verb("smoke-meat", "action", 1),
  verb("salt-v", "action", 1),
  verb("dry-v", "action", 1),
  verb("grind", "action", 1),
  verb("churn", "action", 1),

  // Textiles + clothing
  noun("spindle", "tools", 1),
  noun("distaff", "tools", 1),
  noun("shuttle", "tools", 1),
  noun("yarn", "clothing", 1),
  noun("dye", "clothing", 1),
  noun("tunic", "clothing", 1),
  noun("cloak", "clothing", 1),
  noun("mantle", "clothing", 1),
  noun("apron", "clothing", 1),
  noun("buckle", "tools", 1),
  noun("buttonhole", "clothing", 1),
  verb("spin-thread", "action", 1),
  verb("weave-v", "action", 1),
  verb("dye-v", "action", 1),
  verb("sew-v", "action", 1),
  verb("knit", "action", 1),
  verb("embroider", "action", 1),

  // Pottery + crafts
  noun("kiln", "tools", 1),
  noun("clay-pot", "tools", 1),
  noun("jar", "tools", 1),
  noun("amphora", "tools", 1),
  noun("urn", "tools", 1),
  noun("brick", "tools", 1),
  noun("tile", "tools", 1),
  noun("wheel-potter", "tools", 1),
  verb("bake-pot", "action", 1),
  verb("mould", "action", 1),
  verb("glaze", "action", 1),

  // Settlement
  noun("hamlet", "abstract", 1),
  noun("road-stone", "environment", 1),
  noun("bridge", "tools", 1),
  noun("ford", "environment", 1),
  noun("market-square", "abstract", 1),
  noun("granary-house", "tools", 1),
  noun("well-shaft", "environment", 1),

  // Roles + ritual
  noun("elder-council", "abstract", 1),
  noun("priestess", "kinship", 1),
  noun("shaman", "kinship", 1),
  noun("healer", "kinship", 1),
  noun("midwife", "kinship", 1),
  noun("bard", "kinship", 1),
  noun("smith-village", "kinship", 1),
  noun("oath-stone", "abstract", 1),
  noun("blessing", "abstract", 1),
  noun("offering", "abstract", 1),
  noun("rite-passage", "abstract", 1),

  // Cooking adjectives + qualities
  adj("ripe-fruit", "quality", 1),
  adj("rotten-food", "quality", 1),
  adj("salted", "quality", 1),
  adj("smoked", "quality", 1),
  adj("fermented", "quality", 1),
  adj("freshly-baked", "quality", 1),
];

// ---------------------------------------------------------------------------
// Tier 2 — iron-age / classical
// ---------------------------------------------------------------------------

const TIER_2: ExpandedConcept[] = [
  // Metallurgy
  noun("smelter", "tools", 2),
  noun("forge", "tools", 2),
  noun("bellows", "tools", 2),
  noun("crucible", "tools", 2),
  noun("ingot", "tools", 2),
  noun("ore", "environment", 2),
  noun("slag", "environment", 2),
  noun("nail-iron", "tools", 2),
  noun("rivet", "tools", 2),
  noun("chain", "tools", 2),
  noun("lock", "tools", 2),
  noun("key", "tools", 2),
  noun("hinge", "tools", 2),
  noun("blade", "tools", 2),
  noun("dagger", "tools", 2),
  noun("scabbard", "tools", 2),
  noun("helmet", "tools", 2),
  noun("breastplate", "tools", 2),
  noun("shield-iron", "tools", 2),
  noun("bow-composite", "tools", 2),
  noun("crossbow", "tools", 2),
  noun("javelin", "tools", 2),
  verb("smelt", "action", 2),
  verb("forge-v", "action", 2),
  verb("temper", "action", 2),
  verb("hammer-v", "action", 2),
  verb("cast-metal", "action", 2),
  verb("polish", "action", 2),

  // City-states + governance
  noun("citadel", "abstract", 2),
  noun("acropolis", "abstract", 2),
  noun("city-wall", "abstract", 2),
  noun("gate", "tools", 2),
  noun("watchtower", "tools", 2),
  noun("harbour", "environment", 2),
  noun("dock", "tools", 2),
  noun("warehouse", "tools", 2),
  noun("treasury", "abstract", 2),
  noun("granary-state", "tools", 2),
  noun("council-hall", "abstract", 2),
  noun("forum", "abstract", 2),
  noun("agora", "abstract", 2),
  noun("court-of-law", "abstract", 2),
  noun("jury", "abstract", 2),
  noun("witness", "kinship", 2),
  noun("judge", "kinship", 2),
  noun("magistrate", "kinship", 2),
  noun("governor", "kinship", 2),
  noun("emperor", "kinship", 2),
  noun("queen", "kinship", 2),
  noun("noble", "kinship", 2),
  noun("knight", "kinship", 2),
  noun("commoner", "kinship", 2),
  noun("citizen", "kinship", 2),
  noun("subject", "kinship", 2),
  noun("vassal", "kinship", 2),
  noun("peasant", "kinship", 2),
  noun("serf", "kinship", 2),
  noun("slave-bond", "kinship", 2),
  noun("steward", "kinship", 2),
  noun("herald", "kinship", 2),
  noun("messenger", "kinship", 2),
  noun("ambassador", "kinship", 2),

  // Law + administration
  noun("statute", "abstract", 2),
  noun("decree", "abstract", 2),
  noun("edict", "abstract", 2),
  noun("treaty", "abstract", 2),
  noun("oath-state", "abstract", 2),
  noun("verdict", "abstract", 2),
  noun("crime", "abstract", 2),
  noun("punishment", "abstract", 2),
  noun("fine", "abstract", 2),
  noun("ransom", "abstract", 2),
  noun("tribute", "abstract", 2),
  noun("toll", "abstract", 2),
  noun("inheritance", "abstract", 2),
  noun("contract", "abstract", 2),
  verb("decree-v", "action", 2),
  verb("rule-v", "action", 2),
  verb("judge-v", "action", 2),
  verb("punish", "action", 2),
  verb("pardon", "action", 2),
  verb("convict", "action", 2),
  verb("acquit", "action", 2),

  // Writing + literacy + accounting
  noun("scribe", "kinship", 2),
  noun("scroll", "tools", 2),
  noun("tablet", "tools", 2),
  noun("seal-stamp", "tools", 2),
  noun("ink", "tools", 2),
  noun("quill", "tools", 2),
  noun("stylus", "tools", 2),
  noun("parchment", "tools", 2),
  noun("papyrus", "tools", 2),
  noun("manuscript", "tools", 2),
  noun("library", "abstract", 2),
  noun("archive", "abstract", 2),
  noun("ledger", "tools", 2),
  noun("tally", "tools", 2),
  noun("abacus", "tools", 2),
  verb("inscribe", "action", 2),
  verb("copy-v", "action", 2),
  verb("seal-v", "action", 2),
  verb("count-tally", "action", 2),

  // Trade + commerce
  noun("market-day", "abstract", 2),
  noun("merchant", "kinship", 2),
  noun("trader", "kinship", 2),
  noun("caravan", "tools", 2),
  noun("ship-trade", "tools", 2),
  noun("port", "environment", 2),
  noun("warehouse-trade", "tools", 2),
  noun("coin", "tools", 2),
  noun("silver-coin", "tools", 2),
  noun("gold-coin", "tools", 2),
  noun("scale-balance", "tools", 2),
  noun("weight-stone", "tools", 2),
  noun("price", "abstract", 2),
  noun("value", "abstract", 2),
  noun("loan", "abstract", 2),
  noun("interest", "abstract", 2),
  noun("profit", "abstract", 2),
  noun("loss", "abstract", 2),
  noun("bargain", "abstract", 2),
  noun("guild", "abstract", 2),
  verb("trade-v", "action", 2),
  verb("barter", "action", 2),
  verb("haggle", "action", 2),
  verb("import-v", "action", 2),
  verb("export-v", "action", 2),
  verb("ship-v", "action", 2),

  // Trade goods
  noun("silk", "clothing", 2),
  noun("linen", "clothing", 2),
  noun("velvet", "clothing", 2),
  noun("ivory", "tools", 2),
  noun("amber", "tools", 2),
  noun("pearl", "tools", 2),
  noun("gem", "tools", 2),
  noun("ruby", "tools", 2),
  noun("sapphire", "tools", 2),
  noun("emerald", "tools", 2),
  noun("incense", "food", 2),
  noun("myrrh", "food", 2),
  noun("perfume", "food", 2),
  noun("dye-purple", "clothing", 2),

  // Warfare + military
  noun("army", "abstract", 2),
  noun("legion", "abstract", 2),
  noun("regiment", "abstract", 2),
  noun("phalanx", "abstract", 2),
  noun("cavalry", "abstract", 2),
  noun("infantry", "abstract", 2),
  noun("archer", "kinship", 2),
  noun("captain", "kinship", 2),
  noun("general", "kinship", 2),
  noun("commander", "kinship", 2),
  noun("scout", "kinship", 2),
  noun("siege", "abstract", 2),
  noun("battle", "abstract", 2),
  noun("campaign", "abstract", 2),
  noun("retreat", "abstract", 2),
  noun("victory", "abstract", 2),
  noun("defeat", "abstract", 2),
  noun("conquest", "abstract", 2),
  noun("garrison", "abstract", 2),
  noun("fortress", "tools", 2),
  noun("rampart", "tools", 2),
  noun("moat", "tools", 2),
  noun("battering-ram", "tools", 2),
  noun("catapult", "tools", 2),
  noun("siege-tower", "tools", 2),
  noun("chariot", "tools", 2),
  verb("march-v", "action", 2),
  verb("charge-v", "action", 2),
  verb("retreat-v", "action", 2),
  verb("besiege", "action", 2),
  verb("conquer", "action", 2),
  verb("surrender", "action", 2),
  verb("rebel", "action", 2),

  // Religion + ritual + temples
  noun("temple-grand", "abstract", 2),
  noun("altar", "abstract", 2),
  noun("shrine", "abstract", 2),
  noun("sanctuary", "abstract", 2),
  noun("pilgrim", "kinship", 2),
  noun("pilgrimage", "abstract", 2),
  noun("monk", "kinship", 2),
  noun("nun", "kinship", 2),
  noun("priest-high", "kinship", 2),
  noun("oracle", "kinship", 2),
  noun("prophet", "kinship", 2),
  noun("scripture", "abstract", 2),
  noun("psalm", "abstract", 2),
  noun("hymn", "abstract", 2),
  noun("vow", "abstract", 2),
  noun("creed", "abstract", 2),
  noun("heresy", "abstract", 2),
  noun("sacred", "abstract", 2),
  noun("profane", "abstract", 2),
  verb("worship", "action", 2),
  verb("bless-v", "action", 2),
  verb("curse-v", "action", 2),
  verb("anoint", "action", 2),
  verb("baptise", "action", 2),

  // Education + scholarship
  noun("scholar", "kinship", 2),
  noun("philosopher", "kinship", 2),
  noun("astronomer", "kinship", 2),
  noun("physician", "kinship", 2),
  noun("apothecary", "kinship", 2),
  noun("school-academy", "abstract", 2),
  noun("academy", "abstract", 2),
  noun("treatise", "abstract", 2),
  noun("commentary", "abstract", 2),
  noun("lesson", "abstract", 2),
  noun("disciple", "kinship", 2),
  noun("master-teacher", "kinship", 2),
  verb("study", "action", 2),
  verb("debate", "action", 2),
  verb("teach-v", "action", 2),
  verb("lecture", "action", 2),
  verb("tutor", "action", 2),

  // Astronomy + measurement of time
  noun("zodiac", "abstract", 2),
  noun("eclipse", "environment", 2),
  noun("planet", "environment", 2),
  noun("comet", "environment", 2),
  noun("constellation", "environment", 2),
  noun("calendar", "abstract", 2),
  noun("century", "time", 2),
  noun("decade", "time", 2),
  noun("hour-clock", "time", 2),
  noun("week-named", "time", 2),
  noun("season-marker", "time", 2),

  // Civic professions + crafts
  noun("baker", "kinship", 2),
  noun("butcher", "kinship", 2),
  noun("brewer", "kinship", 2),
  noun("carpenter", "kinship", 2),
  noun("mason", "kinship", 2),
  noun("blacksmith", "kinship", 2),
  noun("goldsmith", "kinship", 2),
  noun("tailor", "kinship", 2),
  noun("cobbler", "kinship", 2),
  noun("weaver-prof", "kinship", 2),
  noun("dyer", "kinship", 2),
  noun("tanner", "kinship", 2),
  noun("potter-prof", "kinship", 2),
  noun("miller", "kinship", 2),
  noun("fisher-prof", "kinship", 2),
  noun("hunter-prof", "kinship", 2),
  noun("farmer-prof", "kinship", 2),
  noun("artisan", "kinship", 2),
  noun("apprentice", "kinship", 2),

  // Built environment
  noun("palace", "abstract", 2),
  noun("mansion", "abstract", 2),
  noun("courtyard", "abstract", 2),
  noun("garden-formal", "abstract", 2),
  noun("aqueduct", "tools", 2),
  noun("fountain", "tools", 2),
  noun("statue", "tools", 2),
  noun("monument", "tools", 2),
  noun("column", "tools", 2),
  noun("dome", "tools", 2),
  noun("vault", "tools", 2),
  noun("arch", "tools", 2),
  noun("mosaic", "tools", 2),
  noun("fresco", "tools", 2),

  // Abstract notions
  noun("freedom", "abstract", 2),
  noun("tyranny", "abstract", 2),
  noun("equality", "abstract", 2),
  noun("liberty", "abstract", 2),
  noun("philosophy", "abstract", 2),
  noun("logic", "abstract", 2),
  noun("rhetoric", "abstract", 2),
  noun("ethics", "abstract", 2),
  noun("destiny", "abstract", 2),
  noun("providence", "abstract", 2),
  noun("revelation", "abstract", 2),
  adj("noble-quality", "quality", 2),
  adj("base-quality", "quality", 2),
  adj("just-quality", "quality", 2),
  adj("unjust-quality", "quality", 2),
  adj("eloquent", "quality", 2),
  adj("learned", "quality", 2),
  adj("ignorant", "quality", 2),
];

// ---------------------------------------------------------------------------
// Tier 3 — modern (industrial / civic / scientific / digital)
// ---------------------------------------------------------------------------

const TIER_3: ExpandedConcept[] = [
  // Industrial revolution + machinery
  noun("factory", "tools", 3),
  noun("workshop", "tools", 3),
  noun("foundry", "tools", 3),
  noun("mill-mechanical", "tools", 3),
  noun("machine", "tools", 3),
  noun("engine", "tools", 3),
  noun("steam-engine", "tools", 3),
  noun("turbine", "tools", 3),
  noun("piston", "tools", 3),
  noun("gear", "tools", 3),
  noun("pulley", "tools", 3),
  noun("conveyor", "tools", 3),
  noun("crane-machine", "tools", 3),
  noun("boiler", "tools", 3),
  noun("furnace", "tools", 3),
  noun("generator", "tools", 3),
  noun("motor", "tools", 3),
  noun("battery", "tools", 3),
  noun("circuit", "tools", 3),
  noun("wire", "tools", 3),
  noun("cable", "tools", 3),
  noun("plug", "tools", 3),
  noun("socket", "tools", 3),
  noun("switch", "tools", 3),
  noun("light-bulb", "tools", 3),
  noun("lamp-electric", "tools", 3),
  verb("manufacture", "action", 3),
  verb("assemble", "action", 3),
  verb("automate", "action", 3),
  verb("operate", "action", 3),
  verb("electrify", "action", 3),

  // Transport
  noun("road-paved", "environment", 3),
  noun("highway", "environment", 3),
  noun("railway", "tools", 3),
  noun("track-rail", "tools", 3),
  noun("station", "tools", 3),
  noun("platform", "tools", 3),
  noun("ticket", "tools", 3),
  noun("car", "tools", 3),
  noun("bus", "tools", 3),
  noun("truck", "tools", 3),
  noun("bicycle", "tools", 3),
  noun("motorcycle", "tools", 3),
  noun("train", "tools", 3),
  noun("subway", "tools", 3),
  noun("tunnel", "tools", 3),
  noun("airport", "abstract", 3),
  noun("plane", "tools", 3),
  noun("helicopter", "tools", 3),
  noun("rocket", "tools", 3),
  noun("submarine", "tools", 3),
  noun("ferry", "tools", 3),
  noun("steamer", "tools", 3),
  noun("port-modern", "environment", 3),
  noun("garage", "tools", 3),
  noun("petrol", "tools", 3),
  noun("fuel", "tools", 3),
  noun("highway-exit", "environment", 3),
  noun("bridge-modern", "tools", 3),
  noun("traffic", "abstract", 3),
  noun("signal-traffic", "tools", 3),
  verb("drive-v", "action", 3),
  verb("commute", "action", 3),
  verb("ship-cargo", "action", 3),
  verb("fly-airplane", "action", 3),
  verb("park-v", "action", 3),
  verb("refuel", "action", 3),

  // Communication + media
  noun("telegraph", "tools", 3),
  noun("telephone", "tools", 3),
  noun("phone-mobile", "tools", 3),
  noun("smartphone", "tools", 3),
  noun("radio", "tools", 3),
  noun("television", "tools", 3),
  noun("camera", "tools", 3),
  noun("microphone", "tools", 3),
  noun("speaker-audio", "tools", 3),
  noun("headphone", "tools", 3),
  noun("antenna", "tools", 3),
  noun("satellite", "tools", 3),
  noun("internet", "abstract", 3),
  noun("website", "abstract", 3),
  noun("email", "abstract", 3),
  noun("message-text", "abstract", 3),
  noun("call-phone", "abstract", 3),
  noun("broadcast", "abstract", 3),
  noun("channel", "abstract", 3),
  noun("network", "abstract", 3),
  noun("server", "tools", 3),
  noun("router", "tools", 3),
  noun("modem", "tools", 3),
  noun("signal-radio", "abstract", 3),
  noun("podcast", "abstract", 3),
  noun("video", "abstract", 3),
  noun("photograph", "abstract", 3),
  noun("newspaper", "abstract", 3),
  noun("magazine", "abstract", 3),
  noun("journalist", "kinship", 3),
  noun("editor", "kinship", 3),
  noun("anchor", "kinship", 3),
  noun("influencer", "kinship", 3),
  noun("subscriber", "kinship", 3),
  noun("follower-online", "kinship", 3),
  verb("call-v", "action", 3),
  verb("text-v", "action", 3),
  verb("email-v", "action", 3),
  verb("broadcast-v", "action", 3),
  verb("stream-v", "action", 3),
  verb("download", "action", 3),
  verb("upload", "action", 3),
  verb("post-online", "action", 3),
  verb("share-online", "action", 3),
  verb("like-online", "action", 3),
  verb("subscribe", "action", 3),

  // Computing + digital
  noun("computer", "tools", 3),
  noun("laptop", "tools", 3),
  noun("tablet-device", "tools", 3),
  noun("keyboard", "tools", 3),
  noun("mouse-computer", "tools", 3),
  noun("screen", "tools", 3),
  noun("monitor", "tools", 3),
  noun("printer", "tools", 3),
  noun("software", "abstract", 3),
  noun("app", "abstract", 3),
  noun("program", "abstract", 3),
  noun("code-software", "abstract", 3),
  noun("file-digital", "abstract", 3),
  noun("folder", "abstract", 3),
  noun("password", "abstract", 3),
  noun("account-online", "abstract", 3),
  noun("data", "abstract", 3),
  noun("database", "abstract", 3),
  noun("memory-computer", "tools", 3),
  noun("disk", "tools", 3),
  noun("cloud-storage", "abstract", 3),
  noun("algorithm", "abstract", 3),
  noun("ai-system", "abstract", 3),
  noun("robot", "tools", 3),
  noun("game-video", "abstract", 3),
  noun("emoji", "abstract", 3),
  noun("link-hyper", "abstract", 3),
  noun("search-query", "abstract", 3),
  noun("notification", "abstract", 3),
  verb("click", "action", 3),
  verb("type-keyboard", "action", 3),
  verb("scroll-screen", "action", 3),
  verb("swipe", "action", 3),
  verb("save-file", "action", 3),
  verb("delete-file", "action", 3),
  verb("install", "action", 3),
  verb("update-software", "action", 3),
  verb("reboot", "action", 3),
  verb("login", "action", 3),
  verb("logout", "action", 3),
  verb("sync", "action", 3),
  verb("encrypt", "action", 3),
  verb("hack", "action", 3),

  // Science
  noun("atom", "abstract", 3),
  noun("molecule", "abstract", 3),
  noun("electron", "abstract", 3),
  noun("proton", "abstract", 3),
  noun("neutron", "abstract", 3),
  noun("element-chem", "abstract", 3),
  noun("compound-chem", "abstract", 3),
  noun("acid", "abstract", 3),
  noun("base-chem", "abstract", 3),
  noun("crystal", "environment", 3),
  noun("gene", "abstract", 3),
  noun("dna", "abstract", 3),
  noun("cell-bio", "abstract", 3),
  noun("organism", "abstract", 3),
  noun("species", "abstract", 3),
  noun("ecosystem", "abstract", 3),
  noun("evolution-theory", "abstract", 3),
  noun("microbe", "animals", 3),
  noun("bacteria", "animals", 3),
  noun("virus", "animals", 3),
  noun("planet-modern", "environment", 3),
  noun("orbit", "environment", 3),
  noun("galaxy", "environment", 3),
  noun("universe", "environment", 3),
  noun("black-hole", "environment", 3),
  noun("gravity", "abstract", 3),
  noun("magnetism", "abstract", 3),
  noun("electricity", "abstract", 3),
  noun("radiation", "abstract", 3),
  noun("energy-physics", "abstract", 3),
  noun("force-physics", "abstract", 3),
  noun("mass-physics", "abstract", 3),
  noun("velocity", "abstract", 3),
  noun("temperature-celsius", "abstract", 3),
  noun("experiment", "abstract", 3),
  noun("hypothesis", "abstract", 3),
  noun("theory", "abstract", 3),
  noun("formula", "abstract", 3),
  noun("equation", "abstract", 3),
  noun("graph-data", "abstract", 3),
  verb("measure-precise", "action", 3),
  verb("calculate", "action", 3),
  verb("hypothesise", "action", 3),
  verb("test-experiment", "action", 3),
  verb("publish-paper", "action", 3),

  // Medicine + health
  noun("doctor", "kinship", 3),
  noun("nurse", "kinship", 3),
  noun("surgeon", "kinship", 3),
  noun("dentist", "kinship", 3),
  noun("pharmacist", "kinship", 3),
  noun("paramedic", "kinship", 3),
  noun("therapist", "kinship", 3),
  noun("hospital-modern", "abstract", 3),
  noun("clinic", "abstract", 3),
  noun("emergency-room", "abstract", 3),
  noun("operating-room", "abstract", 3),
  noun("ambulance", "tools", 3),
  noun("syringe", "tools", 3),
  noun("vaccine", "abstract", 3),
  noun("antibiotic", "abstract", 3),
  noun("medicine-drug", "abstract", 3),
  noun("prescription", "abstract", 3),
  noun("diagnosis", "abstract", 3),
  noun("symptom", "abstract", 3),
  noun("disease", "abstract", 3),
  noun("infection", "abstract", 3),
  noun("cancer", "abstract", 3),
  noun("diabetes", "abstract", 3),
  noun("allergy", "abstract", 3),
  noun("surgery-op", "abstract", 3),
  noun("x-ray", "abstract", 3),
  noun("scan", "abstract", 3),
  noun("blood-test", "abstract", 3),
  noun("anesthesia", "abstract", 3),
  noun("therapy", "abstract", 3),
  noun("rehab", "abstract", 3),
  verb("vaccinate", "action", 3),
  verb("operate-medical", "action", 3),
  verb("prescribe", "action", 3),
  verb("diagnose", "action", 3),
  verb("treat-medical", "action", 3),
  verb("recover-health", "action", 3),

  // Politics + governance (modern)
  noun("democracy", "abstract", 3),
  noun("republic", "abstract", 3),
  noun("constitution", "abstract", 3),
  noun("parliament", "abstract", 3),
  noun("congress", "abstract", 3),
  noun("senate", "abstract", 3),
  noun("election", "abstract", 3),
  noun("vote", "abstract", 3),
  noun("ballot", "abstract", 3),
  noun("campaign-political", "abstract", 3),
  noun("party-political", "abstract", 3),
  noun("president", "kinship", 3),
  noun("prime-minister", "kinship", 3),
  noun("minister", "kinship", 3),
  noun("politician", "kinship", 3),
  noun("activist", "kinship", 3),
  noun("protester", "kinship", 3),
  noun("policy", "abstract", 3),
  noun("law-modern", "abstract", 3),
  noun("regulation", "abstract", 3),
  noun("rights", "abstract", 3),
  noun("revolution", "abstract", 3),
  noun("reform", "abstract", 3),
  noun("nation", "abstract", 3),
  noun("border", "environment", 3),
  noun("passport", "tools", 3),
  noun("visa", "tools", 3),
  noun("immigration", "abstract", 3),
  noun("refugee", "kinship", 3),
  noun("citizen-modern", "kinship", 3),
  noun("diplomat", "kinship", 3),
  noun("embassy", "abstract", 3),
  verb("vote-v", "action", 3),
  verb("elect", "action", 3),
  verb("legislate", "action", 3),
  verb("protest-v", "action", 3),
  verb("immigrate", "action", 3),
  verb("emigrate", "action", 3),

  // Finance + economy
  noun("bank-modern", "abstract", 3),
  noun("currency-modern", "abstract", 3),
  noun("dollar", "abstract", 3),
  noun("euro", "abstract", 3),
  noun("yen", "abstract", 3),
  noun("cash", "abstract", 3),
  noun("credit-card", "tools", 3),
  noun("debit-card", "tools", 3),
  noun("cheque", "tools", 3),
  noun("invoice", "tools", 3),
  noun("receipt", "tools", 3),
  noun("budget", "abstract", 3),
  noun("salary", "abstract", 3),
  noun("wage", "abstract", 3),
  noun("pension", "abstract", 3),
  noun("savings", "abstract", 3),
  noun("investment", "abstract", 3),
  noun("stock-share", "abstract", 3),
  noun("bond-finance", "abstract", 3),
  noun("loan-modern", "abstract", 3),
  noun("mortgage", "abstract", 3),
  noun("insurance", "abstract", 3),
  noun("tax-modern", "abstract", 3),
  noun("audit", "abstract", 3),
  noun("market-stock", "abstract", 3),
  noun("economy-modern", "abstract", 3),
  noun("inflation", "abstract", 3),
  noun("recession", "abstract", 3),
  noun("startup", "abstract", 3),
  noun("corporation", "abstract", 3),
  noun("shareholder", "kinship", 3),
  noun("accountant", "kinship", 3),
  noun("banker", "kinship", 3),
  noun("ceo", "kinship", 3),
  noun("manager", "kinship", 3),
  noun("employee", "kinship", 3),
  noun("contractor", "kinship", 3),
  verb("invest", "action", 3),
  verb("borrow-finance", "action", 3),
  verb("repay", "action", 3),
  verb("budget-v", "action", 3),
  verb("tax-v", "action", 3),
  verb("audit-v", "action", 3),
  verb("hire", "action", 3),
  verb("fire-employee", "action", 3),
  verb("promote-job", "action", 3),
  verb("retire", "action", 3),

  // Education + workplace
  noun("school-modern", "abstract", 3),
  noun("university", "abstract", 3),
  noun("college", "abstract", 3),
  noun("classroom", "abstract", 3),
  noun("textbook", "tools", 3),
  noun("notebook", "tools", 3),
  noun("pencil", "tools", 3),
  noun("eraser", "tools", 3),
  noun("ruler", "tools", 3),
  noun("calculator", "tools", 3),
  noun("backpack", "clothing", 3),
  noun("uniform", "clothing", 3),
  noun("homework", "abstract", 3),
  noun("exam", "abstract", 3),
  noun("grade", "abstract", 3),
  noun("degree", "abstract", 3),
  noun("diploma", "abstract", 3),
  noun("scholarship", "abstract", 3),
  noun("teacher-modern", "kinship", 3),
  noun("professor", "kinship", 3),
  noun("student-modern", "kinship", 3),
  noun("graduate", "kinship", 3),
  noun("librarian", "kinship", 3),
  noun("scientist", "kinship", 3),
  noun("engineer", "kinship", 3),
  noun("programmer", "kinship", 3),
  noun("designer", "kinship", 3),
  noun("artist-modern", "kinship", 3),
  noun("musician", "kinship", 3),
  noun("athlete", "kinship", 3),
  noun("office", "abstract", 3),
  noun("desk", "tools", 3),
  noun("meeting", "abstract", 3),
  noun("project", "abstract", 3),
  noun("deadline", "abstract", 3),
  noun("schedule", "abstract", 3),
  noun("calendar-app", "tools", 3),
  noun("alarm", "tools", 3),
  noun("reminder", "abstract", 3),
  verb("study-modern", "action", 3),
  verb("graduate-v", "action", 3),
  verb("research-v", "action", 3),
  verb("design-v", "action", 3),
  verb("code-v", "action", 3),

  // Domestic + appliances
  noun("refrigerator", "tools", 3),
  noun("freezer", "tools", 3),
  noun("stove-electric", "tools", 3),
  noun("oven-electric", "tools", 3),
  noun("microwave", "tools", 3),
  noun("dishwasher", "tools", 3),
  noun("washing-machine", "tools", 3),
  noun("dryer", "tools", 3),
  noun("vacuum-cleaner", "tools", 3),
  noun("iron-clothes", "tools", 3),
  noun("toaster", "tools", 3),
  noun("kettle-electric", "tools", 3),
  noun("blender", "tools", 3),
  noun("fan-electric", "tools", 3),
  noun("heater", "tools", 3),
  noun("air-conditioner", "tools", 3),
  noun("clock-modern", "tools", 3),
  noun("watch-wrist", "tools", 3),
  noun("flashlight", "tools", 3),
  noun("battery-modern", "tools", 3),

  // Buildings + urban environment
  noun("apartment", "abstract", 3),
  noun("skyscraper", "abstract", 3),
  noun("hotel", "abstract", 3),
  noun("restaurant", "abstract", 3),
  noun("cafe", "abstract", 3),
  noun("supermarket", "abstract", 3),
  noun("mall", "abstract", 3),
  noun("park-public", "environment", 3),
  noun("playground", "abstract", 3),
  noun("stadium", "abstract", 3),
  noun("museum", "abstract", 3),
  noun("gallery", "abstract", 3),
  noun("theatre-modern", "abstract", 3),
  noun("cinema", "abstract", 3),
  noun("library-modern", "abstract", 3),
  noun("post-office", "abstract", 3),
  noun("police-station", "abstract", 3),
  noun("fire-station", "abstract", 3),
  noun("prison", "abstract", 3),
  noun("courthouse", "abstract", 3),

  // Recreation + arts + sports
  noun("book-modern", "abstract", 3),
  noun("film-movie", "abstract", 3),
  noun("song-recorded", "abstract", 3),
  noun("album", "abstract", 3),
  noun("concert", "abstract", 3),
  noun("festival-modern", "abstract", 3),
  noun("theatre-play", "abstract", 3),
  noun("painting-art", "abstract", 3),
  noun("sculpture-art", "abstract", 3),
  noun("photograph-art", "abstract", 3),
  noun("dance-modern", "abstract", 3),
  noun("sport", "abstract", 3),
  noun("football", "abstract", 3),
  noun("basketball", "abstract", 3),
  noun("tennis", "abstract", 3),
  noun("baseball", "abstract", 3),
  noun("golf", "abstract", 3),
  noun("running-sport", "abstract", 3),
  noun("swimming-sport", "abstract", 3),
  noun("yoga", "abstract", 3),
  noun("gym", "abstract", 3),
  noun("ball-sport", "tools", 3),
  noun("trophy", "tools", 3),
  noun("medal", "tools", 3),
  noun("team", "abstract", 3),
  noun("coach", "kinship", 3),
  noun("referee", "kinship", 3),
  noun("fan-sport", "kinship", 3),
  verb("play-sport", "action", 3),
  verb("compete", "action", 3),
  verb("train-physical", "action", 3),
  verb("perform-stage", "action", 3),
  verb("paint-art", "action", 3),
  verb("compose-music", "action", 3),

  // Modern abstract notions
  noun("equality-modern", "abstract", 3),
  noun("privacy", "abstract", 3),
  noun("identity", "abstract", 3),
  noun("globalisation", "abstract", 3),
  noun("sustainability", "abstract", 3),
  noun("pollution", "abstract", 3),
  noun("climate-change", "abstract", 3),
  noun("carbon", "abstract", 3),
  noun("recycling", "abstract", 3),
  noun("biodiversity", "abstract", 3),
  noun("psychology-modern", "abstract", 3),
  noun("anxiety", "abstract", 3),
  noun("depression-mental", "abstract", 3),
  noun("therapy-mental", "abstract", 3),
  noun("addiction", "abstract", 3),
  noun("trauma", "abstract", 3),
  noun("self-care", "abstract", 3),
  noun("burnout", "abstract", 3),
  noun("wellbeing", "abstract", 3),
  adj("digital", "quality", 3),
  adj("analog", "quality", 3),
  adj("electric", "quality", 3),
  adj("modern", "quality", 3),
  adj("antique", "quality", 3),
  adj("efficient", "quality", 3),
  adj("sustainable", "quality", 3),
  adj("toxic", "quality", 3),
  adj("renewable", "quality", 3),
  adj("automated", "quality", 3),
  adj("remote-work", "quality", 3),
  adj("global", "quality", 3),
  adj("local", "quality", 3),
  adj("urban", "quality", 3),
  adj("rural", "quality", 3),
];

export const EXPANDED_CONCEPTS: readonly ExpandedConcept[] = [
  ...TIER_1,
  ...TIER_2,
  ...TIER_3,
];
