/**
 * build-corpus-rank.ts — generate src/engine/semantics/corpusRank.ts
 *
 * Source: glove-wiki-gigaword-50 (gensim-data, PUBLIC DOMAIN / PDDL). The GloVe
 * vocabulary file is in DESCENDING corpus-frequency order (line 2 = "the" = rank 0;
 * line 1 is the gensim "<count> <dim>" header). We recover that order — lost when
 * embeddingData.ts was alphabetized — and turn it into a DENSE rank over the concept
 * vocabulary (EMBED_TABLE ∪ ANCHOR_EXTRA_TABLE):
 *
 *   global rank(token) = its 0-based line position in the GloVe file
 *   global rank(concept) = MIN global rank over its hyphen-split tokens (the most
 *                          frequent component — a concept is at least that common)
 *   DENSE rank(concept)  = its position when all ranked concepts are sorted by
 *                          global rank ascending (0 = most frequent concept)
 *   MAX_RANK             = number of ranked concepts; concepts with no GloVe token
 *                          are omitted (rankOf → MAX_RANK → treated as rarest)
 *
 * Dense rank (not raw GloVe global rank) is what conceptRegistry.tierOf consumes:
 * tierOf does pct = rankOf(m)/MAX_RANK ∈ [0,1) and bands the percentile, so the tier
 * distribution spreads across the concept set instead of collapsing into tier 0.
 *
 * Run: GLOVE_PATH=/tmp/glove50 npx tsx scripts/build-corpus-rank.ts
 */
import * as fs from "fs";
import { EMBED_TABLE } from "../src/engine/semantics/embeddingData";
import { ANCHOR_EXTRA_TABLE } from "../src/engine/semantics/anchorExtrasData";

const GLOVE = process.env.GLOVE_PATH || "/tmp/glove50";

const tokensFor = (m: string): string[] =>
  m.toLowerCase().split("-").map((t) => t.trim()).filter((t) => t.length > 0);

// 1. Concept vocabulary + needed GloVe tokens.
const concepts = Array.from(new Set<string>([...Object.keys(EMBED_TABLE), ...Object.keys(ANCHOR_EXTRA_TABLE)]));
const needed = new Set<string>();
for (const m of concepts) for (const t of tokensFor(m)) needed.add(t);

// 2. Stream GloVe once; record the FIRST (lowest) global rank per needed token.
//    Skip the header line (gensim "<count> <dim>"); the next line is global rank 0.
const text = fs.readFileSync(GLOVE, "utf8");
const tokenRank = new Map<string, number>();
let nl = text.indexOf("\n");
let pos = nl + 1; // skip header
let rank = 0;
while (pos < text.length) {
  nl = text.indexOf("\n", pos);
  if (nl < 0) nl = text.length;
  const sp = text.indexOf(" ", pos);
  const word = sp < 0 || sp > nl ? text.slice(pos, nl) : text.slice(pos, sp);
  if (needed.has(word) && !tokenRank.has(word)) tokenRank.set(word, rank);
  rank++;
  pos = nl + 1;
}

// 3. Concept global rank = min token rank; drop concepts with no GloVe token.
const globalRank = new Map<string, number>();
for (const m of concepts) {
  let best = Infinity;
  for (const t of tokensFor(m)) {
    const r = tokenRank.get(t);
    if (r !== undefined && r < best) best = r;
  }
  if (Number.isFinite(best)) globalRank.set(m, best);
}

// 4. Dense rank: sort ranked concepts by global rank asc (tie-break by key for determinism).
const ranked = [...globalRank.keys()].sort((a, b) => {
  const d = globalRank.get(a)! - globalRank.get(b)!;
  return d !== 0 ? d : a < b ? -1 : a > b ? 1 : 0;
});
const CORPUS_RANK: Record<string, number> = {};
ranked.forEach((m, i) => { CORPUS_RANK[m] = i; });
const MAX_RANK = ranked.length;

// 5. Emit (keys sorted for a stable, reviewable diff).
const sortedEntries = Object.keys(CORPUS_RANK).sort().map((k) => [k, CORPUS_RANK[k]] as const);
const obj = "{" + sortedEntries.map(([k, v]) => `${JSON.stringify(k)}:${v}`).join(",") + "}";
const banner =
  `// AUTO-GENERATED by scripts/build-corpus-rank.ts — DO NOT EDIT BY HAND.\n` +
  `// Source: glove-wiki-gigaword-50 (gensim-data, public domain / PDDL) frequency order.\n` +
  `// DENSE rank over the concept vocabulary (0 = most frequent); ${MAX_RANK} ranked of\n` +
  `// ${concepts.length} concept keys. Concepts absent here had no GloVe token → rankOf = MAX_RANK.\n`;
fs.writeFileSync(
  "src/engine/semantics/corpusRank.ts",
  banner +
    `/** 0-based DENSE GloVe-frequency rank per concept (lower = more frequent). */\n` +
    `export const CORPUS_RANK: Readonly<Record<string, number>> = ${obj};\n` +
    `export const MAX_RANK = ${MAX_RANK};\n` +
    `export function rankOf(meaning: string): number {\n` +
    `  return CORPUS_RANK[meaning] ?? MAX_RANK;\n` +
    `}\n`,
);

// 6. Sanity report (stderr).
const out = process.stderr;
out.write(`ranked ${MAX_RANK}/${concepts.length} concepts\n`);
const show = (m: string) => out.write(`  rankOf(${JSON.stringify(m)}) = ${CORPUS_RANK[m] ?? `MAX(${MAX_RANK})`}\n`);
for (const m of ["water", "fire", "good", "dog", "king", "mountain", "honey", "abacus", "the"]) show(m);
