/**
 * build-pos-table.ts — generate src/engine/lexicon/posTable.ts
 *
 * Source: Princeton WordNet 3.0 index files (public, redistributable; via nltk_data
 * `wordnet.zip`). For each concept key (EMBED_TABLE ∪ ANCHOR_EXTRA_TABLE) we read its
 * DOMINANT open-class POS — the part of speech in which the lemma has the most synsets
 * (senses) across index.noun / index.verb / index.adj / index.adv. This replaces the
 * hand-assigned `ExpandedConcept.pos` with a corpus-grounded tagged-lexicon source.
 *
 * Mapping: n→noun, v→verb, a/s→adjective, r→adverb. Closed-class function words are
 * NOT taken from here (taggers/WordNet mishandle them) — conceptRegistry.posOf layers
 * the pos.ts closed-class override sets on top. Proper nouns: the concept vocabulary is
 * lowercased GloVe common words (no proper nouns expected); none are emitted as "propn".
 *
 * Run: WORDNET_DIR=/tmp/wordnet npx tsx scripts/build-pos-table.ts
 */
import * as fs from "fs";
import type { POS } from "../src/engine/lexicon/pos";
import { EMBED_TABLE } from "../src/engine/semantics/embeddingData";
import { ANCHOR_EXTRA_TABLE } from "../src/engine/semantics/anchorExtrasData";

const WN = process.env.WORDNET_DIR || "/tmp/wordnet";

const WN_POS: Record<string, POS> = { n: "noun", v: "verb", a: "adjective", s: "adjective", r: "adverb" };
// Tie-break priority when two POS have equal sense counts (nouns most frequent default).
const PRIORITY: POS[] = ["noun", "verb", "adjective", "adverb"];

const tokensFor = (m: string): string[] =>
  m.toLowerCase().split("-").map((t) => t.trim()).filter((t) => t.length > 0);

// 1. Concept vocabulary + the lemmas we need to look up (full key + its tokens).
const concepts = Array.from(new Set<string>([...Object.keys(EMBED_TABLE), ...Object.keys(ANCHOR_EXTRA_TABLE)]));
const needed = new Set<string>();
for (const m of concepts) {
  needed.add(m.toLowerCase());
  for (const t of tokensFor(m)) needed.add(t);
}

// 2. Parse WordNet index files → senseCount[lemma][POS] (only for needed lemmas).
const senses = new Map<string, Map<POS, number>>();
for (const file of ["index.noun", "index.verb", "index.adj", "index.adv"]) {
  const text = fs.readFileSync(`${WN}/${file}`, "utf8");
  for (const line of text.split("\n")) {
    if (line.startsWith("  ") || line.length === 0) continue; // license header / blank
    const parts = line.split(" ");
    const lemma = parts[0]!;
    if (!needed.has(lemma)) continue;
    const pos = WN_POS[parts[1]!];
    if (!pos) continue;
    const cnt = parseInt(parts[2]!, 10) || 0;
    let m = senses.get(lemma);
    if (!m) { m = new Map(); senses.set(lemma, m); }
    m.set(pos, (m.get(pos) ?? 0) + cnt);
  }
}

const dominant = (lemma: string): POS | undefined => {
  const m = senses.get(lemma);
  if (!m) return undefined;
  let best: POS | undefined;
  let bestCnt = -1;
  for (const pos of PRIORITY) {
    const c = m.get(pos) ?? 0;
    if (c > bestCnt) { bestCnt = c; best = pos; } // PRIORITY order makes ties deterministic
  }
  return bestCnt > 0 ? best : undefined;
};

// 3. POS per concept: full key → else first resolving token → else omitted.
const POS_TABLE: Record<string, POS | "propn"> = {};
let covered = 0;
for (const m of concepts) {
  let pos = dominant(m.toLowerCase());
  if (!pos) for (const t of tokensFor(m)) { pos = dominant(t); if (pos) break; }
  if (pos) { POS_TABLE[m] = pos; covered++; }
}

// 4. Emit (keys sorted for a stable, reviewable diff).
const entries = Object.keys(POS_TABLE).sort().map((k) => `${JSON.stringify(k)}:${JSON.stringify(POS_TABLE[k])}`);
const banner =
  `// AUTO-GENERATED by scripts/build-pos-table.ts — DO NOT EDIT BY HAND.\n` +
  `// Source: Princeton WordNet 3.0 (public domain) dominant open-class POS per concept;\n` +
  `// ${covered}/${concepts.length} concept keys covered. Closed-class function words are\n` +
  `// overridden in pos.ts (conceptRegistry.posOf layers them on top).\n`;
fs.writeFileSync(
  "src/engine/lexicon/posTable.ts",
  banner +
    `import type { POS } from "./pos";\n` +
    `/** Baked dominant POS per concept, from WordNet. Closed-class words overridden in pos.ts. */\n` +
    `export const POS_TABLE: Readonly<Record<string, POS | "propn">> = {${entries.join(",")}};\n` +
    `export function bakedPosOf(meaning: string): POS | "propn" | undefined {\n` +
    `  return POS_TABLE[meaning];\n` +
    `}\n`,
);

// 5. Sanity report.
const out = process.stderr;
out.write(`covered ${covered}/${concepts.length} concepts\n`);
for (const m of ["run", "red", "water", "good", "quickly", "dog", "happy", "king", "swim"]) {
  out.write(`  ${m} → ${POS_TABLE[m] ?? "(none → cc fallback)"}\n`);
}
