/**
 * build-morpheme-space.ts — generate src/engine/semantics/morphemeSpaceData.ts
 * Run: npx tsx scripts/build-morpheme-space.ts
 */
import * as fs from "fs";
import { presetEnglish } from "../src/engine/presets/english";
import { embed } from "../src/engine/semantics/embeddings";
import { fromFloats, type Vec } from "../src/engine/semantics/vec";
import { factorizeMorphemes, type Decomp } from "../src/engine/semantics/morphemeFactor";

const isAffix = (id: string) => id.startsWith("-") || id.endsWith("-");
const affixType = (id: string): "prefix" | "suffix" => (id.endsWith("-") ? "prefix" : "suffix");

const cfg = presetEnglish();
const compounds = cfg.seedCompounds ?? {};
const derivs = cfg.seedDerivations ?? {};
const roots = new Map<string, Vec>();
const affixIds = new Set<string>();
const decomps: Decomp[] = [];
const partsByWord = new Map<string, string[]>();
const addRoot = (m: string) => { if (!roots.has(m)) roots.set(m, fromFloats(embed(m))); };

for (const [word, c] of Object.entries(compounds)) {
  for (const p of c.parts) (isAffix(p) ? affixIds.add(p) : addRoot(p));
  decomps.push({ word, wordAnchor: fromFloats(embed(word)), parts: c.parts.slice() });
  partsByWord.set(word, c.parts.slice());
}
for (const [word, d] of Object.entries(derivs)) {
  isAffix(d.affix) ? affixIds.add(d.affix) : addRoot(d.affix);
  addRoot(d.base);
  decomps.push({ word, wordAnchor: fromFloats(embed(word)), parts: [d.base, d.affix] });
  partsByWord.set(word, [d.base, d.affix]);
}

const { morphemes, wordPoints } = factorizeMorphemes({ roots, affixIds, decomps });

const morphemeRows = [...morphemes.keys()].sort().map((id) => ({
  id,
  type: isAffix(id) ? affixType(id) : "root",
  point: Array.from(morphemes.get(id)!),
}));
const wordRows = [...wordPoints.keys()].sort().map((m) => ({
  meaning: m,
  parts: partsByWord.get(m)!,
  point: Array.from(wordPoints.get(m)!),
}));

const out =
  `// AUTO-GENERATED by scripts/build-morpheme-space.ts — do not edit by hand.\n` +
  `// Additive morpheme space for the English validation preset (Track A plan 2).\n` +
  `export const MORPHEME_SPACE = {\n` +
  `  preset: "english",\n` +
  `  morphemes: ${JSON.stringify(morphemeRows)},\n` +
  `  words: ${JSON.stringify(wordRows)},\n` +
  `} as const;\n`;

fs.writeFileSync("src/engine/semantics/morphemeSpaceData.ts", out);
console.log(`baked ${morphemeRows.length} morphemes, ${wordRows.length} words`);
