/**
 * build-embedding.ts — generate src/engine/semantics/embeddingData.ts
 *
 * Source: glove-wiki-gigaword-50 (gensim-data, PUBLIC DOMAIN / PDDL), 400k words × 50d.
 * Each canonical concept id is mapped to the average of its hyphen-split tokens' GloVe
 * vectors (disambiguation tags like -ish/-v/-action aren't GloVe words and drop out;
 * real tokens like swallow+bird average → "swallow (the bird)"). Vectors are then
 * antonym-counter-fitted (the 30 curated gradable pairs are pushed apart, since raw
 * distributional embeddings place antonyms close), L2-normalized, and quantized to int8.
 * Run: GLOVE_PATH=<glove50> npx tsx scripts/build-embedding.ts
 */
import * as fs from "fs";
import { CONCEPT_IDS } from "../src/engine/lexicon/concepts";
import { ANTONYM_PAIRS } from "../src/engine/semantics/antonyms";

const GLOVE = process.env.GLOVE_PATH || "/tmp/glove50";
const DIM = 50;

const tokensFor = (m: string): string[] =>
  m.toLowerCase().split("-").map((t) => t.trim()).filter((t) => t.length > 0);

// 1. Needed GloVe tokens.
const needed = new Set<string>();
for (const m of CONCEPT_IDS) for (const t of tokensFor(m)) needed.add(t);

// 2. Stream GloVe once, keep needed vectors.
const vecs = new Map<string, Float64Array>();
const text = fs.readFileSync(GLOVE, "utf8");
let nl = text.indexOf("\n");
let pos = nl + 1;
while (pos < text.length) {
  nl = text.indexOf("\n", pos);
  if (nl < 0) nl = text.length;
  const sp = text.indexOf(" ", pos);
  const word = text.slice(pos, sp);
  if (needed.has(word)) {
    const parts = text.slice(sp + 1, nl).split(" ");
    const v = new Float64Array(DIM);
    for (let d = 0; d < DIM; d++) v[d] = parseFloat(parts[d]!);
    vecs.set(word, v);
  }
  pos = nl + 1;
}

// 3. Build a normalized float table (average present tokens).
const norm = (v: Float64Array): Float64Array => {
  let n = 0;
  for (const x of v) n += x * x;
  n = Math.sqrt(n) || 1;
  const o = new Float64Array(v.length);
  for (let i = 0; i < v.length; i++) o[i] = v[i]! / n;
  return o;
};
const dot = (a: Float64Array, b: Float64Array): number => {
  let d = 0;
  for (let i = 0; i < a.length; i++) d += a[i]! * b[i]!;
  return d;
};
const ftable = new Map<string, Float64Array>();
for (const m of CONCEPT_IDS) {
  const toks = tokensFor(m).filter((t) => vecs.has(t));
  if (toks.length === 0) continue;
  const acc = new Float64Array(DIM);
  for (const t of toks) {
    const v = vecs.get(t)!;
    for (let d = 0; d < DIM; d++) acc[d]! += v[d]!;
  }
  for (let d = 0; d < DIM; d++) acc[d]! /= toks.length;
  ftable.set(m, norm(acc));
}
const found = ftable.size;

// 4. Antonym counter-fitting: push the curated gradable pairs apart.
// Raw distributional embeddings place antonyms close (hot/cold share contexts);
// repel each pair over a few iterations so the embedding reflects opposition.
const RATE = 0.18;
const ITERS = 14;
for (let it = 0; it < ITERS; it++) {
  for (const [a, b] of ANTONYM_PAIRS) {
    const u = ftable.get(a), v = ftable.get(b);
    if (!u || !v) continue;
    if (dot(u, v) <= -0.1) continue; // already opposed enough
    const nu = new Float64Array(DIM), nv = new Float64Array(DIM);
    for (let d = 0; d < DIM; d++) {
      nu[d] = u[d]! - RATE * v[d]!;
      nv[d] = v[d]! - RATE * u[d]!;
    }
    ftable.set(a, norm(nu));
    ftable.set(b, norm(nv));
  }
}

// 5. Quantize to int8 (×127).
const table: Record<string, number[]> = {};
for (const [m, v] of ftable) {
  const q: number[] = [];
  for (const x of v) q.push(Math.max(-127, Math.min(127, Math.round(x * 127))));
  table[m] = q;
}

const banner =
  `// AUTO-GENERATED by scripts/build-embedding.ts — DO NOT EDIT BY HAND.\n` +
  `// Source: glove-wiki-gigaword-50 (gensim-data, public domain / PDDL), 50d.\n` +
  `// ${found}/${CONCEPT_IDS.length} concepts carry a real distributional vector (int8,\n` +
  `// L2-normalized ×127); the 30 curated gradable antonym pairs are counter-fitted\n` +
  `// apart. Concepts not covered fall back to the legacy hash embed().\n`;
fs.writeFileSync(
  "src/engine/semantics/embeddingData.ts",
  banner +
    `export const EMBED_DIM = ${DIM};\n` +
    `export const EMBED_TABLE: Readonly<Record<string, ReadonlyArray<number>>> = ${JSON.stringify(table)};\n`,
);

// 6. Inline validation.
const cosI = (a: ReadonlyArray<number>, b: ReadonlyArray<number>): number => {
  let d = 0, na = 0, nb = 0;
  for (let i = 0; i < a.length; i++) { d += a[i]! * b[i]!; na += a[i]! * a[i]!; nb += b[i]! * b[i]!; }
  return d / (Math.sqrt(na) * Math.sqrt(nb));
};
const out = process.stderr;
out.write(`coverage: ${found}/${CONCEPT_IDS.length} (${((found / CONCEPT_IDS.length) * 100).toFixed(1)}%)\n`);
out.write(`data bytes: ${fs.statSync("src/engine/semantics/embeddingData.ts").size}\n`);
let asum = 0, an = 0;
out.write(`ANTONYMS (post counter-fit, want low/negative):\n`);
for (const [a, b] of ANTONYM_PAIRS.slice(0, 8)) {
  const u = table[a], v = table[b];
  if (u && v) { const c = cosI(u, v); asum += c; an++; out.write(`  ${a}/${b}=${c.toFixed(2)} `); }
}
for (const [a, b] of ANTONYM_PAIRS) { const u = table[a], v = table[b]; if (u && v) { /* count all for mean */ } }
let allSum = 0, allN = 0;
for (const [a, b] of ANTONYM_PAIRS) { const u = table[a], v = table[b]; if (u && v) { allSum += cosI(u, v); allN++; } }
out.write(`\n  MEAN antonym cos (all ${allN}) = ${(allSum / allN).toFixed(3)}\n`);
out.write(`RELATED (want HIGH): `);
for (const [a, b] of [["water", "sea"], ["dog", "cat"], ["king", "queen"], ["hot", "warm"], ["fire", "flame"]]) {
  const u = table[a], v = table[b];
  if (u && v) out.write(`${a}/${b}=${cosI(u, v).toFixed(2)} `);
}
out.write(`\n`);
