/**
 * build-anchor-extras.ts — generate src/engine/semantics/anchorExtrasData.ts
 *
 * Vector-native lexicon flip (anchor-coverage extension). The curated CONCEPTS registry never
 * covered ~150 basic CONTENT words the presets actually key (house/body/door/person/time/ocean/…),
 * so those words sat on a deterministic hash point that glossed to noise. This emits real GloVe-50
 * vectors for them as ANCHOR EXTRAS — they enrich the translator's anchor coordinate frame and give
 * the words real points, WITHOUT being added to the sim's coinable CONCEPTS registry (so tiering /
 * frequency / capacity are untouched; only the affected words' meaning POINTS change, a contained
 * GENN re-baseline). Same normalize+quantize as build-embedding.ts (L2-norm ×127 → int8); no antonym
 * counter-fitting (none of these are curated antonym poles).
 *
 * Run: GLOVE_PATH=<glove50> npx tsx scripts/build-anchor-extras.ts
 */
import * as fs from "fs";

const GLOVE = process.env.GLOVE_PATH || "/tmp/glove50";
const DIM = 50;

// Basic CONTENT words the presets key that the curated registry never covered. Grammatical orphans
// (pronouns, articles, conjunctions, prepositions, adverbs, deictics) are intentionally excluded —
// they have no lexical anchor by nature (their identity is the labeled POS=closed dim). Words GloVe
// lacks are silently skipped.
const EXTRA_WORDS: string[] = [
  "accept", "afraid", "agree", "allow", "angry", "animal", "area", "art", "axle", "baby",
  "ball", "become", "bed", "begin", "bind", "bitter", "body", "book", "bottle", "brave",
  "bring", "building", "burn", "business", "busy", "calm", "catch", "ceiling", "chair", "change",
  "city", "clock", "color", "community", "continue", "culture", "death", "decide", "different",
  "difficult", "distance", "divide", "door", "draw", "dress", "earn", "easy", "enemy", "enjoy",
  "enter", "feather", "feeling", "finish", "fisherman", "floor", "food", "fork", "future", "ghost",
  "glass", "government", "group", "guest", "happy", "hate", "healthy", "hearth", "height", "high",
  "hoe", "horn", "hospital", "host", "house", "hungry", "idea", "important", "jacket", "job",
  "join", "keep", "language", "leave", "letter", "life", "like", "line", "list", "live",
  "look", "low", "make", "man", "map", "market", "master", "medicine", "meet", "message",
  "mill", "mistake", "money", "move", "naked", "need", "noise", "number", "ocean", "open",
  "paper", "part", "person", "phone", "picture", "place", "point", "prayer", "problem", "put",
  "ready", "real", "reason", "reins", "return", "roof", "room", "rule", "sad", "save",
  "say", "scarecrow", "school", "science", "seabird", "shape", "share", "shop", "show", "sick",
  "simple", "size", "smart", "sock", "sound", "sow", "space", "spend", "start", "stiff",
  "stop", "store", "strange", "street", "student", "system", "table", "tail", "technology", "tell",
  "thing", "thought", "time", "tired", "use", "voice", "wake", "wall", "wallet", "want",
  "watch", "way", "weave", "weight", "window", "wing", "woman", "world", "yard", "youth",
];

const needed = new Set(EXTRA_WORDS);

// Stream GloVe once, keep needed vectors.
const vecs = new Map<string, Float64Array>();
const text = fs.readFileSync(GLOVE, "utf8");
let nl = text.indexOf("\n");
let pos = nl + 1; // skip the "<count> <dim>" header line
while (pos < text.length) {
  nl = text.indexOf("\n", pos);
  if (nl < 0) nl = text.length;
  const sp = text.indexOf(" ", pos);
  const word = text.slice(pos, sp);
  if (needed.has(word)) {
    const parts = text.slice(sp + 1, nl).split(" ");
    const v = new Float64Array(DIM);
    for (let d = 0; d < DIM; d++) v[d] = parseFloat(parts[d]!);
    vecs.set(word, v);
  }
  pos = nl + 1;
}

const norm = (v: Float64Array): Float64Array => {
  let n = 0;
  for (const x of v) n += x * x;
  n = Math.sqrt(n) || 1;
  const o = new Float64Array(v.length);
  for (let i = 0; i < v.length; i++) o[i] = v[i]! / n;
  return o;
};

// Quantize to int8 (×127), in sorted-key order for a stable, deterministic file.
const table: Record<string, number[]> = {};
const missing: string[] = [];
for (const w of [...EXTRA_WORDS].sort()) {
  const raw = vecs.get(w);
  if (!raw) {
    missing.push(w);
    continue;
  }
  const v = norm(raw);
  const q: number[] = [];
  for (const x of v) q.push(Math.max(-127, Math.min(127, Math.round(x * 127))));
  table[w] = q;
}

const found = Object.keys(table).length;
const banner =
  `// AUTO-GENERATED by scripts/build-anchor-extras.ts — DO NOT EDIT BY HAND.\n` +
  `// Source: glove-wiki-gigaword-50 (gensim-data, public domain / PDDL), 50d.\n` +
  `// Anchor-coverage extension for the vector-native lexicon flip: real GloVe vectors for ${found}\n` +
  `// basic CONTENT words the curated CONCEPTS registry never covered. NOT part of the sim's coinable\n` +
  `// concept pool — these only enrich the anchor frame + give the words real meaning points.\n`;
fs.writeFileSync(
  "src/engine/semantics/anchorExtrasData.ts",
  banner +
    `export const ANCHOR_EXTRA_TABLE: Readonly<Record<string, ReadonlyArray<number>>> = ${JSON.stringify(table)};\n`,
);

process.stderr.write(`anchor extras: ${found}/${EXTRA_WORDS.length} covered; missing (GloVe lacks): ${missing.join(", ")}\n`);
