import type { SimulationConfig, Lexicon, Meaning } from "../types";
import type { Morphology } from "../morphology/types";
import { defaultConfig } from "../config";

const LEXICON: Lexicon = {
  water: ["w", "ɔ", "t", "ə", "r"],
  fire: ["f", "a", "j", "ə", "r"],
  stone: ["s", "t", "o", "n"],
  earth: ["ə", "r", "θ"],
  sky: ["s", "k", "a", "j"],
  sun: ["s", "ʌ", "n"],
  moon: ["m", "uː", "n"],
  star: ["s", "t", "a", "r"],
  cloud: ["k", "l", "a", "w", "d"],
  rain: ["r", "e", "j", "n"],
  snow: ["s", "n", "o", "w"],
  ice: ["a", "j", "s"],
  wind: ["w", "ɪ", "n", "d"],
  thunder: ["θ", "ʌ", "n", "d", "ə", "r"],
  lightning: ["l", "a", "j", "t", "n", "ɪ", "ŋ"],
  river: ["r", "ɪ", "v", "ə", "r"],
  sea: ["s", "iː"],
  lake: ["l", "e", "j", "k"],
  ocean: ["o", "ʃ", "ə", "n"],
  mountain: ["m", "a", "w", "n", "t", "ə", "n"],
  hill: ["h", "ɪ", "l"],
  valley: ["v", "æ", "l", "i"],
  forest: ["f", "ɔ", "r", "ə", "s", "t"],
  field: ["f", "iː", "l", "d"],
  road: ["r", "o", "d"],
  path: ["p", "æ", "θ"],
  day: ["d", "e", "j"],
  night: ["n", "a", "j", "t"],
  morning: ["m", "ɔ", "r", "n", "ɪ", "ŋ"],
  evening: ["iː", "v", "n", "ɪ", "ŋ"],
  year: ["j", "ɪ", "r"],
  winter: ["w", "ɪ", "n", "t", "ə", "r"],
  summer: ["s", "ʌ", "m", "ə", "r"],
  spring: ["s", "p", "r", "ɪ", "ŋ"],
  time: ["t", "a", "j", "m"],
  tree: ["t", "r", "iː"],
  wood: ["w", "ʊ", "d"],
  leaf: ["l", "iː", "f"],
  flower: ["f", "l", "a", "w", "ə", "r"],
  grass: ["g", "r", "æ", "s"],
  root: ["r", "uː", "t"],
  seed: ["s", "iː", "d"],
  fruit: ["f", "r", "uː", "t"],
  grain: ["g", "r", "e", "j", "n"],
  bark: ["b", "a", "r", "k"],
  oak: ["o", "k"],
  apple: ["æ", "p", "ə", "l"],
  pine: ["p", "a", "j", "n"],
  bush: ["b", "ʊ", "ʃ"],
  vine: ["v", "a", "j", "n"],
  herb: ["ə", "r", "b"],
  mushroom: ["m", "ʌ", "ʃ", "r", "uː", "m"],
  berry: ["b", "ɛ", "r", "i"],
  bread: ["b", "r", "ɛ", "d"],
  meat: ["m", "iː", "t"],
  milk: ["m", "ɪ", "l", "k"],
  cheese: ["tʃ", "iː", "z"],
  egg: ["ɛ", "g"],
  honey: ["h", "ʌ", "n", "i"],
  salt: ["s", "ɔ", "l", "t"],
  sugar: ["ʃ", "ʊ", "g", "ə", "r"],
  oil: ["ɔ", "j", "l"],
  wine: ["w", "a", "j", "n"],
  beer: ["b", "ɪ", "r"],
  dog: ["d", "ɔ", "g"],
  wolf: ["w", "ʊ", "l", "f"],
  horse: ["h", "ɔ", "r", "s"],
  cow: ["k", "a", "w"],
  bull: ["b", "ʊ", "l"],
  sheep: ["ʃ", "iː", "p"],
  goat: ["g", "o", "t"],
  pig: ["p", "ɪ", "g"],
  bear: ["b", "ɛ", "r"],
  deer: ["d", "ɪ", "r"],
  fish: ["f", "ɪ", "ʃ"],
  bird: ["b", "ə", "r", "d"],
  eagle: ["iː", "g", "ə", "l"],
  hawk: ["h", "ɔ", "k"],
  cat: ["k", "æ", "t"],
  mouse: ["m", "a", "w", "s"],
  rabbit: ["r", "æ", "b", "ɪ", "t"],
  fox: ["f", "ɔ", "k", "s"],
  snake: ["s", "n", "e", "j", "k"],
  worm: ["w", "ə", "r", "m"],
  ant: ["æ", "n", "t"],
  bee: ["b", "iː"],
  fly: ["f", "l", "a", "j"],
  spider: ["s", "p", "a", "j", "d", "ə", "r"],
  feather: ["f", "ɛ", "ð", "ə", "r"],
  wing: ["w", "ɪ", "ŋ"],
  horn: ["h", "ɔ", "r", "n"],
  tail: ["t", "e", "j", "l"],
  body: ["b", "ɔ", "d", "i"],
  head: ["h", "ɛ", "d"],
  hair: ["h", "ɛ", "r"],
  face: ["f", "e", "j", "s"],
  eye: ["a", "j"],
  ear: ["ɪ", "r"],
  nose: ["n", "o", "z"],
  mouth: ["m", "a", "w", "θ"],
  tongue: ["t", "ʌ", "ŋ"],
  tooth: ["t", "uː", "θ"],
  lip: ["l", "ɪ", "p"],
  chin: ["tʃ", "ɪ", "n"],
  neck: ["n", "ɛ", "k"],
  shoulder: ["ʃ", "o", "l", "d", "ə", "r"],
  arm: ["a", "r", "m"],
  hand: ["h", "æ", "n", "d"],
  finger: ["f", "ɪ", "ŋ", "g", "ə", "r"],
  nail: ["n", "e", "j", "l"],
  chest: ["tʃ", "ɛ", "s", "t"],
  back: ["b", "æ", "k"],
  belly: ["b", "ɛ", "l", "i"],
  heart: ["h", "a", "r", "t"],
  liver: ["l", "ɪ", "v", "ə", "r"],
  bone: ["b", "o", "n"],
  blood: ["b", "l", "ʌ", "d"],
  skin: ["s", "k", "ɪ", "n"],
  flesh: ["f", "l", "ɛ", "ʃ"],
  knee: ["n", "iː"],
  leg: ["l", "ɛ", "g"],
  foot: ["f", "ʊ", "t"],
  mother: ["m", "ʌ", "ð", "ə", "r"],
  father: ["f", "a", "ð", "ə", "r"],
  son: ["s", "ʌ", "n"],
  daughter: ["d", "ɔ", "t", "ə", "r"],
  brother: ["b", "r", "ʌ", "ð", "ə", "r"],
  sister: ["s", "ɪ", "s", "t", "ə", "r"],
  uncle: ["ʌ", "ŋ", "k", "ə", "l"],
  aunt: ["æ", "n", "t"],
  child: ["tʃ", "a", "j", "l", "d"],
  parent: ["p", "ɛ", "r", "ə", "n", "t"],
  husband: ["h", "ʌ", "z", "b", "ə", "n", "d"],
  wife: ["w", "a", "j", "f"],
  friend: ["f", "r", "ɛ", "n", "d"],
  // Phase 36 Tranche 36f: 'stranger' is now expressed as a derivational
  // compound of 'strange' + agentive '-er.agt', rebuilt at language
  // birth via seedCompounds. See seedCompounds below for the chain.
  strange: ["s", "t", "r", "e", "j", "n", "dʒ"],
  king: ["k", "ɪ", "ŋ"],
  queen: ["k", "w", "iː", "n"],
  warrior: ["w", "ɔ", "r", "i", "ə", "r"],
  village: ["v", "ɪ", "l", "ɪ", "dʒ"],
  town: ["t", "a", "w", "n"],
  city: ["s", "ɪ", "t", "i"],
  house: ["h", "a", "w", "s"],
  home: ["h", "o", "m"],
  door: ["d", "ɔ", "r"],
  window: ["w", "ɪ", "n", "d", "o"],
  knife: ["n", "a", "j", "f"],
  axe: ["æ", "k", "s"],
  spear: ["s", "p", "ɪ", "r"],
  bow: ["b", "o"],
  arrow: ["æ", "r", "o"],
  rope: ["r", "o", "p"],
  cloth: ["k", "l", "ɔ", "θ"],
  shoe: ["ʃ", "uː"],
  hat: ["h", "æ", "t"],
  ring: ["r", "ɪ", "ŋ"],
  boat: ["b", "o", "t"],
  ship: ["ʃ", "ɪ", "p"],
  cart: ["k", "a", "r", "t"],
  wheel: ["w", "iː", "l"],
  i: ["a", "j"],
  you: ["j", "u"],
  he: ["h", "iː"],
  she: ["ʃ", "iː"],
  it: ["ɪ", "t"],
  "he-she": ["h", "iː"],
  we: ["w", "iː"],
  they: ["ð", "e", "j"],
  this: ["ð", "ɪ", "s"],
  that: ["ð", "æ", "t"],
  here: ["h", "ɪ", "r"],
  there: ["ð", "ɛ", "r"],
  what: ["w", "ʌ", "t"],
  who: ["h", "uː"],
  where: ["w", "ɛ", "r"],
  when: ["w", "ɛ", "n"],
  why: ["w", "a", "j"],
  how: ["h", "a", "w"],
  one: ["w", "ʌ", "n"],
  two: ["t", "uː"],
  three: ["θ", "r", "iː"],
  four: ["f", "ɔ", "r"],
  five: ["f", "a", "j", "v"],
  six: ["s", "ɪ", "k", "s"],
  seven: ["s", "ɛ", "v", "ə", "n"],
  eight: ["e", "j", "t"],
  nine: ["n", "a", "j", "n"],
  ten: ["t", "ɛ", "n"],
  hundred: ["h", "ʌ", "n", "d", "r", "ə", "d"],
  thousand: ["θ", "a", "w", "z", "ə", "n", "d"],
  many: ["m", "ɛ", "n", "i"],
  few: ["f", "j", "u"],
  half: ["h", "æ", "f"],
  big: ["b", "ɪ", "g"],
  small: ["s", "m", "ɔ", "l"],
  new: ["n", "u"],
  old: ["o", "l", "d"],
  good: ["g", "ʊ", "d"],
  bad: ["b", "æ", "d"],
  hot: ["h", "ɔ", "t"],
  cold: ["k", "o", "l", "d"],
  wet: ["w", "ɛ", "t"],
  dry: ["d", "r", "a", "j"],
  long: ["l", "ɔ", "ŋ"],
  short: ["ʃ", "ɔ", "r", "t"],
  hard: ["h", "a", "r", "d"],
  soft: ["s", "ɔ", "f", "t"],
  heavy: ["h", "ɛ", "v", "i"],
  round: ["r", "a", "w", "n", "d"],
  sharp: ["ʃ", "a", "r", "p"],
  sweet: ["s", "w", "iː", "t"],
  sour: ["s", "a", "w", "ə", "r"],
  strong: ["s", "t", "r", "ɔ", "ŋ"],
  weak: ["w", "iː", "k"],
  fast: ["f", "æ", "s", "t"],
  slow: ["s", "l", "o"],
  light: ["l", "a", "j", "t"],
  dark: ["d", "a", "r", "k"],
  go: ["g", "o"],
  come: ["k", "ʌ", "m"],
  walk: ["w", "ɔ", "k"],
  run: ["r", "ʌ", "n"],
  swim: ["s", "w", "ɪ", "m"],
  climb: ["k", "l", "a", "j", "m"],
  fall: ["f", "ɔ", "l"],
  rise: ["r", "a", "j", "z"],
  see: ["s", "iː"],
  know: ["n", "o"],
  hear: ["h", "ɪ", "r"],
  feel: ["f", "iː", "l"],
  find: ["f", "a", "j", "n", "d"],
  smell: ["s", "m", "ɛ", "l"],
  taste: ["t", "e", "j", "s", "t"],
  eat: ["iː", "t"],
  drink: ["d", "r", "ɪ", "ŋ", "k"],
  sleep: ["s", "l", "iː", "p"],
  die: ["d", "a", "j"],
  live: ["l", "ɪ", "v"],
  breathe: ["b", "r", "iː", "ð"],
  sit: ["s", "ɪ", "t"],
  stand: ["s", "t", "æ", "n", "d"],
  give: ["g", "ɪ", "v"],
  take: ["t", "e", "j", "k"],
  throw: ["θ", "r", "o"],
  break: ["b", "r", "e", "j", "k"],
  cut: ["k", "ʌ", "t"],
  kill: ["k", "ɪ", "l"],
  fight: ["f", "a", "j", "t"],
  hunt: ["h", "ʌ", "n", "t"],
  speak: ["s", "p", "iː", "k"],
  say: ["s", "e", "j"],
  sing: ["s", "ɪ", "ŋ"],
  laugh: ["l", "æ", "f"],
  cry: ["k", "r", "a", "j"],
  think: ["θ", "ɪ", "ŋ", "k"],
  love: ["l", "ʌ", "v"],
  fear: ["f", "ɪ", "r"],
  want: ["w", "a", "n", "t"],
  hold: ["h", "o", "l", "d"],
  carry: ["k", "ɛ", "r", "i"],
  push: ["p", "ʊ", "ʃ"],
  pull: ["p", "ʊ", "l"],
  build: ["b", "ɪ", "l", "d"],
  make: ["m", "e", "j", "k"],
  do: ["d", "uː"],
  be: ["b", "iː"],
  have: ["h", "æ", "v"],
  work: ["w", "ə", "r", "k"],
  play: ["p", "l", "e", "j"],
  name: ["n", "e", "j", "m"],
  word: ["w", "ə", "r", "d"],
  story: ["s", "t", "ɔ", "r", "i"],
  song: ["s", "ɔ", "ŋ"],
  truth: ["t", "r", "uː", "θ"],
  god: ["g", "ɔ", "d"],
  spirit: ["s", "p", "ɪ", "r", "ɪ", "t"],
  the: ["ð", "ə"],
  a: ["ə"],
  of: ["ə", "v"],
  to: ["t", "u"],
  in: ["ɪ", "n"],
  on: ["a", "n"],
  at: ["æ", "t"],
  by: ["b", "a", "j"],
  with: ["w", "ɪ", "ð"],
  for: ["f", "ɔ", "r"],
  from: ["f", "r", "ʌ", "m"],
  and: ["æ", "n", "d"],
  or: ["ɔ", "r"],
  not: ["n", "a", "t"],
  if: ["ɪ", "f"],
  yes: ["j", "ɛ", "s"],
  no: ["n", "o"],
  computer: ["k", "ə", "m", "p", "j", "uː", "t", "ə", "r"],
  phone: ["f", "o", "n"],
  school: ["s", "k", "uː", "l"],
  government: ["g", "ʌ", "v", "ə", "r", "n", "m", "ə", "n", "t"],
  medicine: ["m", "ɛ", "d", "ə", "s", "ə", "n"],
  science: ["s", "a", "j", "ə", "n", "s"],
  money: ["m", "ʌ", "n", "i"],
  market: ["m", "a", "r", "k", "ə", "t"],
  bridge: ["b", "r", "ɪ", "dʒ"],
  hospital: ["h", "a", "s", "p", "ɪ", "t", "ə", "l"],
  doctor: ["d", "a", "k", "t", "ə", "r"],
  // Phase 36 Tranche 36f: now a derivational compound (teach + -er.agt).
  // The teach + agentive form is recomposed via seedCompounds at birth.
  // The bare entry below is kept as a fallback for tests/boot-strap.
  student: ["s", "t", "uː", "d", "ə", "n", "t"],
  book: ["b", "ʊ", "k"],
  paper: ["p", "e", "j", "p", "ə", "r"],
  pen: ["p", "ɛ", "n"],
  music: ["m", "j", "uː", "z", "ɪ", "k"],
  art: ["a", "r", "t"],
  business: ["b", "ɪ", "z", "n", "ə", "s"],
  machine: ["m", "ə", "ʃ", "iː", "n"],
  electricity: ["ə", "l", "ɛ", "k", "t", "r", "ɪ", "s", "ə", "t", "i"],
  car: ["k", "a", "r"],
  train: ["t", "r", "e", "j", "n"],
  plane: ["p", "l", "e", "j", "n"],
  factory: ["f", "æ", "k", "t", "ə", "r", "i"],
  office: ["a", "f", "ə", "s"],
  world: ["w", "ə", "r", "l", "d"],
  planet: ["p", "l", "æ", "n", "ə", "t"],
  future: ["f", "j", "uː", "tʃ", "ə", "r"],
  history: ["h", "ɪ", "s", "t", "ə", "r", "i"],
  language: ["l", "æ", "ŋ", "g", "w", "ə", "dʒ"],
  culture: ["k", "ʌ", "l", "tʃ", "ə", "r"],
  idea: ["a", "j", "d", "iː", "ə"],
  problem: ["p", "r", "a", "b", "l", "ə", "m"],
  question: ["k", "w", "ɛ", "s", "tʃ", "ə", "n"],
  answer: ["æ", "n", "s", "ə", "r"],
  reason: ["r", "iː", "z", "ə", "n"],
  job: ["dʒ", "a", "b"],
  family: ["f", "æ", "m", "ə", "l", "i"],
  group: ["g", "r", "uː", "p"],
  community: ["k", "ə", "m", "j", "uː", "n", "ə", "t", "i"],
  system: ["s", "ɪ", "s", "t", "ə", "m"],
  technology: ["t", "ɛ", "k", "n", "a", "l", "ə", "dʒ", "i"],
  internet: ["ɪ", "n", "t", "ə", "r", "n", "ɛ", "t"],
  // Phase 36 Tranche 36f: now a derivational compound (free + -dom).
  justice: ["dʒ", "ʌ", "s", "t", "ə", "s"],
  rule: ["r", "uː", "l"],
  goose: ["g", "uː", "s"],
  ox: ["a", "k", "s"],
  man: ["m", "æ", "n"],
  woman: ["w", "ʊ", "m", "ə", "n"],
  put: ["p", "ʊ", "t"],
  me: ["m", "iː"],
  him: ["h", "ɪ", "m"],
  them: ["ð", "ɛ", "m"],
  us: ["ʌ", "s"],
  these: ["ð", "iː", "z"],
  those: ["ð", "o", "z"],
  my: ["m", "a", "j"],
  your: ["j", "ɔ", "r"],
  his: ["h", "ɪ", "z"],
  our: ["a", "w", "ə", "r"],
  their: ["ð", "ɛ", "r"],
  whom: ["h", "uː", "m"],
  whose: ["h", "uː", "z"],
  which: ["w", "ɪ", "tʃ"],
  can: ["k", "æ", "n"],
  could: ["k", "ʊ", "d"],
  will: ["w", "ɪ", "l"],
  would: ["w", "ʊ", "d"],
  should: ["ʃ", "ʊ", "d"],
  may: ["m", "e", "j"],
  might: ["m", "a", "j", "t"],
  must: ["m", "ʌ", "s", "t"],
  shall: ["ʃ", "æ", "l"],
  need: ["n", "iː", "d"],
  some: ["s", "ʌ", "m"],
  any: ["ɛ", "n", "i"],
  all: ["ɔ", "l"],
  every: ["ɛ", "v", "r", "i"],
  each: ["iː", "tʃ"],
  both: ["b", "o", "θ"],
  none: ["n", "ʌ", "n"],
  more: ["m", "ɔ", "r"],
  most: ["m", "o", "s", "t"],
  less: ["l", "ɛ", "s"],
  much: ["m", "ʌ", "tʃ"],
  enough: ["ɪ", "n", "ʌ", "f"],
  about: ["ə", "b", "a", "w", "t"],
  above: ["ə", "b", "ʌ", "v"],
  across: ["ə", "k", "r", "ɔ", "s"],
  after: ["æ", "f", "t", "ə", "r"],
  against: ["ə", "g", "ɛ", "n", "s", "t"],
  around: ["ə", "r", "a", "w", "n", "d"],
  before: ["b", "ɪ", "f", "ɔ", "r"],
  behind: ["b", "ɪ", "h", "a", "j", "n", "d"],
  below: ["b", "ɪ", "l", "o"],
  beside: ["b", "ɪ", "s", "a", "j", "d"],
  between: ["b", "ɪ", "t", "w", "iː", "n"],
  down: ["d", "a", "w", "n"],
  during: ["d", "ʊ", "r", "ɪ", "ŋ"],
  inside: ["ɪ", "n", "s", "a", "j", "d"],
  into: ["ɪ", "n", "t", "uː"],
  near: ["n", "ɪ", "r"],
  off: ["ɔ", "f"],
  out: ["a", "w", "t"],
  outside: ["a", "w", "t", "s", "a", "j", "d"],
  over: ["o", "v", "ə", "r"],
  through: ["θ", "r", "uː"],
  toward: ["t", "ɔ", "r", "d"],
  under: ["ʌ", "n", "d", "ə", "r"],
  until: ["ʌ", "n", "t", "ɪ", "l"],
  up: ["ʌ", "p"],
  upon: ["ə", "p", "a", "n"],
  without: ["w", "ɪ", "ð", "a", "w", "t"],
  although: ["ɔ", "l", "ð", "o"],
  because: ["b", "ɪ", "k", "ɔ", "z"],
  but: ["b", "ʌ", "t"],
  though: ["ð", "o"],
  unless: ["ʌ", "n", "l", "ɛ", "s"],
  while: ["w", "a", "j", "l"],
  whether: ["w", "ɛ", "ð", "ə", "r"],
  ask: ["æ", "s", "k"],
  tell: ["t", "ɛ", "l"],
  listen: ["l", "ɪ", "s", "ə", "n"],
  watch: ["w", "a", "tʃ"],
  look: ["l", "ʊ", "k"],
  lose: ["l", "uː", "z"],
  keep: ["k", "iː", "p"],
  leave: ["l", "iː", "v"],
  arrive: ["ə", "r", "a", "j", "v"],
  enter: ["ɛ", "n", "t", "ə", "r"],
  open: ["o", "p", "ə", "n"],
  start: ["s", "t", "a", "r", "t"],
  stop: ["s", "t", "a", "p"],
  finish: ["f", "ɪ", "n", "ɪ", "ʃ"],
  begin: ["b", "ɪ", "g", "ɪ", "n"],
  end: ["ɛ", "n", "d"],
  continue: ["k", "ə", "n", "t", "ɪ", "n", "j", "uː"],
  wait: ["w", "e", "j", "t"],
  hope: ["h", "o", "p"],
  choose: ["tʃ", "uː", "z"],
  decide: ["d", "ɪ", "s", "a", "j", "d"],
  agree: ["ə", "g", "r", "iː"],
  accept: ["æ", "k", "s", "ɛ", "p", "t"],
  allow: ["ə", "l", "a", "w"],
  help: ["h", "ɛ", "l", "p"],
  save: ["s", "e", "j", "v"],
  learn: ["l", "ə", "r", "n"],
  read: ["r", "iː", "d"],
  write: ["r", "a", "j", "t"],
  draw: ["d", "r", "ɔ"],
  count: ["k", "a", "w", "n", "t"],
  pay: ["p", "e", "j"],
  spend: ["s", "p", "ɛ", "n", "d"],
  earn: ["ə", "r", "n"],
  win: ["w", "ɪ", "n"],
  meet: ["m", "iː", "t"],
  show: ["ʃ", "o"],
  hide: ["h", "a", "j", "d"],
  remember: ["r", "ɪ", "m", "ɛ", "m", "b", "ə", "r"],
  forget: ["f", "ə", "r", "g", "ɛ", "t"],
  believe: ["b", "ɪ", "l", "iː", "v"],
  like: ["l", "a", "j", "k"],
  hate: ["h", "e", "j", "t"],
  enjoy: ["ɪ", "n", "dʒ", "ɔ", "j"],
  smile: ["s", "m", "a", "j", "l"],
  follow: ["f", "a", "l", "o"],
  move: ["m", "uː", "v"],
  change: ["tʃ", "e", "j", "n", "dʒ"],
  use: ["j", "uː", "z"],
  become: ["b", "ɪ", "k", "ʌ", "m"],
  return: ["r", "ɪ", "t", "ə", "r", "n"],
  bring: ["b", "r", "ɪ", "ŋ"],
  buy: ["b", "a", "j"],
  catch: ["k", "æ", "tʃ"],
  teach: ["t", "iː", "tʃ"],
  easy: ["iː", "z", "i"],
  difficult: ["d", "ɪ", "f", "ɪ", "k", "ə", "l", "t"],
  simple: ["s", "ɪ", "m", "p", "ə", "l"],
  dirty: ["d", "ə", "r", "t", "i"],
  clean: ["k", "l", "iː", "n"],
  full: ["f", "ʊ", "l"],
  empty: ["ɛ", "m", "p", "t", "i"],
  free: ["f", "r", "iː"],
  busy: ["b", "ɪ", "z", "i"],
  ready: ["r", "ɛ", "d", "i"],
  tired: ["t", "a", "j", "ə", "r", "d"],
  hungry: ["h", "ʌ", "ŋ", "g", "r", "i"],
  sick: ["s", "ɪ", "k"],
  healthy: ["h", "ɛ", "l", "θ", "i"],
  happy: ["h", "æ", "p", "i"],
  sad: ["s", "æ", "d"],
  angry: ["æ", "ŋ", "g", "r", "i"],
  afraid: ["ə", "f", "r", "e", "j", "d"],
  calm: ["k", "a", "m"],
  brave: ["b", "r", "e", "j", "v"],
  smart: ["s", "m", "a", "r", "t"],
  quiet: ["k", "w", "a", "j", "ə", "t"],
  loud: ["l", "a", "w", "d"],
  thin: ["θ", "ɪ", "n"],
  thick: ["θ", "ɪ", "k"],
  wide: ["w", "a", "j", "d"],
  narrow: ["n", "æ", "r", "o"],
  true: ["t", "r", "uː"],
  false: ["f", "ɔ", "l", "s"],
  real: ["r", "iː", "l"],
  important: ["ɪ", "m", "p", "ɔ", "r", "t", "ə", "n", "t"],
  same: ["s", "e", "j", "m"],
  different: ["d", "ɪ", "f", "ə", "r", "ə", "n", "t"],
  very: ["v", "ɛ", "r", "i"],
  really: ["r", "iː", "l", "i"],
  also: ["ɔ", "l", "s", "o"],
  only: ["o", "n", "l", "i"],
  still: ["s", "t", "ɪ", "l"],
  again: ["ə", "g", "ɛ", "n"],
  now: ["n", "a", "w"],
  then: ["ð", "ɛ", "n"],
  soon: ["s", "uː", "n"],
  always: ["ɔ", "l", "w", "e", "j", "z"],
  never: ["n", "ɛ", "v", "ə", "r"],
  sometimes: ["s", "ʌ", "m", "t", "a", "j", "m", "z"],
  well: ["w", "ɛ", "l"],
  zero: ["z", "ɪ", "r", "o"],
  eleven: ["ɪ", "l", "ɛ", "v", "ə", "n"],
  twelve: ["t", "w", "ɛ", "l", "v"],
  twenty: ["t", "w", "ɛ", "n", "t", "i"],
  thirty: ["θ", "ə", "r", "t", "i"],
  fifty: ["f", "ɪ", "f", "t", "i"],
  hour: ["a", "w", "ə", "r"],
  minute: ["m", "ɪ", "n", "ə", "t"],
  week: ["w", "iː", "k"],
  month: ["m", "ʌ", "n", "θ"],
  today: ["t", "ə", "d", "e", "j"],
  yesterday: ["j", "ɛ", "s", "t", "ə", "r", "d", "e", "j"],
  tomorrow: ["t", "ə", "m", "ɔ", "r", "o"],
  bed: ["b", "ɛ", "d"],
  table: ["t", "e", "j", "b", "ə", "l"],
  chair: ["tʃ", "ɛ", "r"],
  room: ["r", "uː", "m"],
  floor: ["f", "l", "ɔ", "r"],
  ceiling: ["s", "iː", "l", "ɪ", "ŋ"],
  wall: ["w", "ɔ", "l"],
  roof: ["r", "uː", "f"],
  garden: ["g", "a", "r", "d", "ə", "n"],
  yard: ["j", "a", "r", "d"],
  street: ["s", "t", "r", "iː", "t"],
  building: ["b", "ɪ", "l", "d", "ɪ", "ŋ"],
  store: ["s", "t", "ɔ", "r"],
  shop: ["ʃ", "a", "p"],
  key: ["k", "iː"],
  clock: ["k", "l", "a", "k"],
  bag: ["b", "æ", "g"],
  box: ["b", "a", "k", "s"],
  cup: ["k", "ʌ", "p"],
  bowl: ["b", "o", "l"],
  plate: ["p", "l", "e", "j", "t"],
  spoon: ["s", "p", "uː", "n"],
  fork: ["f", "ɔ", "r", "k"],
  glass: ["g", "l", "æ", "s"],
  bottle: ["b", "a", "t", "ə", "l"],
  shirt: ["ʃ", "ə", "r", "t"],
  dress: ["d", "r", "ɛ", "s"],
  coat: ["k", "o", "t"],
  jacket: ["dʒ", "æ", "k", "ə", "t"],
  sock: ["s", "a", "k"],
  color: ["k", "ʌ", "l", "ə", "r"],
  sound: ["s", "a", "w", "n", "d"],
  voice: ["v", "ɔ", "j", "s"],
  noise: ["n", "ɔ", "j", "z"],
  silence: ["s", "a", "j", "l", "ə", "n", "s"],
  feeling: ["f", "iː", "l", "ɪ", "ŋ"],
  thought: ["θ", "ɔ", "t"],
  dream: ["d", "r", "iː", "m"],
  gift: ["g", "ɪ", "f", "t"],
  mistake: ["m", "ɪ", "s", "t", "e", "j", "k"],
  beginning: ["b", "ɪ", "g", "ɪ", "n", "ɪ", "ŋ"],
  middle: ["m", "ɪ", "d", "ə", "l"],
  side: ["s", "a", "j", "d"],
  top: ["t", "a", "p"],
  bottom: ["b", "a", "t", "ə", "m"],
  edge: ["ɛ", "dʒ"],
  line: ["l", "a", "j", "n"],
  point: ["p", "ɔ", "j", "n", "t"],
  shape: ["ʃ", "e", "j", "p"],
  size: ["s", "a", "j", "z"],
  number: ["n", "ʌ", "m", "b", "ə", "r"],
  weight: ["w", "e", "j", "t"],
  height: ["h", "a", "j", "t"],
  area: ["ɛ", "r", "i", "ə"],
  place: ["p", "l", "e", "j", "s"],
  space: ["s", "p", "e", "j", "s"],
  distance: ["d", "ɪ", "s", "t", "ə", "n", "s"],
  age: ["e", "j", "dʒ"],
  letter: ["l", "ɛ", "t", "ə", "r"],
  message: ["m", "ɛ", "s", "ə", "dʒ"],
  list: ["l", "ɪ", "s", "t"],
  map: ["m", "æ", "p"],
  picture: ["p", "ɪ", "k", "tʃ", "ə", "r"],
  ball: ["b", "ɔ", "l"],
  food: ["f", "uː", "d"],
  animal: ["æ", "n", "ə", "m", "ə", "l"],
  plant: ["p", "l", "æ", "n", "t"],
  thing: ["θ", "ɪ", "ŋ"],
  person: ["p", "ə", "r", "s", "ə", "n"],
  part: ["p", "a", "r", "t"],
  way: ["w", "e", "j"],
  right: ["r", "a", "j", "t"],
  left: ["l", "ɛ", "f", "t"],
  last: ["l", "æ", "s", "t"],
  first: ["f", "ə", "r", "s", "t"],
  next: ["n", "ɛ", "k", "s", "t"],
  high: ["h", "a", "j"],
  low: ["l", "o"],
  far: ["f", "a", "r"],
  // Phase 36 Tranche 36f: bound derivational morphemes. These flow
  // through phonological evolution like any other lexicon entry; the
  // seedCompounds map below references them as suffixed parts. Marked
  // as such via boundMorphemes so the lexicon UI / translator do not
  // surface them as standalone words.
  "-er.agt": ["ə", "r"],
  "-ness": ["n", "ə", "s"],
  "-dom": ["d", "ə", "m"],
  "-ship": ["ʃ", "ɪ", "p"],
  "-hood": ["h", "ʊ", "d"],
};

/**
 * Phase 36 Tranche 36f: bound morphemes flagged so they don't appear
 * as standalone words in surface output.
 */
const BOUND_MORPHEMES = new Set<string>([
  "-er.agt", "-ness", "-dom", "-ship", "-hood",
]);

const SUPPLETION: NonNullable<import("../types").Language["suppletion"]> = {
  be: {
    "verb.tense.past": ["w", "a", "z"],
    "verb.tense.fut": ["w", "ɪ", "l", "b", "iː"],
    "verb.aspect.prog": ["b", "iː", "ɪ", "ŋ"],
    "verb.person.1sg": ["æ", "m"],
    "verb.person.2sg": ["a", "r"],
    "verb.person.3sg": ["ɪ", "z"],
    "verb.person.1pl": ["a", "r"],
    "verb.person.2pl": ["a", "r"],
    "verb.person.3pl": ["a", "r"],
  },
  go: {
    "verb.tense.past": ["w", "ɛ", "n", "t"],
    "verb.aspect.prog": ["g", "o", "ʊ", "ɪ", "ŋ"],
  },
  have: {
    "verb.tense.past": ["h", "æ", "d"],
    "verb.person.3sg": ["h", "æ", "z"],
  },
  do: {
    "verb.tense.past": ["d", "ɪ", "d"],
    "verb.person.3sg": ["d", "ʌ", "z"],
  },
  say: {
    "verb.tense.past": ["s", "ɛ", "d"],
    "verb.person.3sg": ["s", "ɛ", "z"],
  },
  make: { "verb.tense.past": ["m", "e", "j", "d"] },
  take: { "verb.tense.past": ["t", "ʊ", "k"] },
  see: { "verb.tense.past": ["s", "ɔ"] },
  give: { "verb.tense.past": ["g", "e", "j", "v"] },
  know: { "verb.tense.past": ["n", "uː"] },
  come: { "verb.tense.past": ["k", "e", "j", "m"] },
  eat: { "verb.tense.past": ["e", "j", "t"] },
  drink: { "verb.tense.past": ["d", "r", "æ", "ŋ", "k"] },
  sing: { "verb.tense.past": ["s", "æ", "ŋ"] },
  run: { "verb.tense.past": ["r", "æ", "n"] },
  find: { "verb.tense.past": ["f", "a", "w", "n", "d"] },
  think: { "verb.tense.past": ["θ", "ɔ", "t"] },
  bring: { "verb.tense.past": ["b", "r", "ɔ", "t"] },
  buy: { "verb.tense.past": ["b", "ɔ", "t"] },
  catch: { "verb.tense.past": ["k", "ɔ", "t"] },
  teach: { "verb.tense.past": ["t", "ɔ", "t"] },
  fight: { "verb.tense.past": ["f", "ɔ", "t"] },
  hold: { "verb.tense.past": ["h", "ɛ", "l", "d"] },
  break: { "verb.tense.past": ["b", "r", "o", "k"] },
  speak: { "verb.tense.past": ["s", "p", "o", "k"] },
  fall: { "verb.tense.past": ["f", "ɛ", "l"] },
  rise: { "verb.tense.past": ["r", "o", "z"] },
  feel: { "verb.tense.past": ["f", "ɛ", "l", "t"] },
  sleep: { "verb.tense.past": ["s", "l", "ɛ", "p", "t"] },
  hear: { "verb.tense.past": ["h", "ə", "r", "d"] },
  stand: { "verb.tense.past": ["s", "t", "ʊ", "d"] },
  cut: { "verb.tense.past": ["k", "ʌ", "t"] },
  put: { "verb.tense.past": ["p", "ʊ", "t"] },
  mouse: { "noun.num.pl": ["m", "a", "j", "s"] },
  child: { "noun.num.pl": ["tʃ", "ɪ", "l", "d", "r", "ə", "n"] },
  foot: { "noun.num.pl": ["f", "iː", "t"] },
  tooth: { "noun.num.pl": ["t", "iː", "θ"] },
  goose: { "noun.num.pl": ["g", "iː", "s"] },
  ox: { "noun.num.pl": ["a", "k", "s", "ə", "n"] },
  man: { "noun.num.pl": ["m", "ɛ", "n"] },
  woman: { "noun.num.pl": ["w", "ɪ", "m", "ə", "n"] },
  good: { "adj.degree.cmp": ["b", "ɛ", "t", "ə", "r"], "adj.degree.sup": ["b", "ɛ", "s", "t"] },
  bad: { "adj.degree.cmp": ["w", "ə", "r", "s"], "adj.degree.sup": ["w", "ə", "r", "s", "t"] },
};

const FREQ: Record<Meaning, number> = {
  the: 0.99, a: 0.98, of: 0.97, to: 0.97, in: 0.97, and: 0.98, not: 0.96,
  i: 0.99, you: 0.99, we: 0.97, they: 0.95, this: 0.96, that: 0.96,
  be: 0.99, have: 0.97, do: 0.96, go: 0.95, come: 0.94, see: 0.94,
  say: 0.94, know: 0.93, think: 0.92, want: 0.91, take: 0.90, give: 0.90,
  make: 0.91, work: 0.85,
  one: 0.96, two: 0.94, three: 0.92, big: 0.90, small: 0.88, good: 0.92, new: 0.88,
  water: 0.92, fire: 0.85, day: 0.92, night: 0.90, time: 0.95,
  mother: 0.92, father: 0.92, child: 0.90, friend: 0.85, name: 0.92,
  hand: 0.89, foot: 0.88, eye: 0.90, head: 0.88, heart: 0.86,
  eat: 0.92, drink: 0.90, sleep: 0.88, die: 0.85,
};

const MORPHOLOGY: Morphology = {
  paradigms: {
    "noun.num.pl": {
      affix: ["z"],
      position: "suffix",
      category: "noun.num.pl",
      variants: [
        { when: "vowel-final", affix: ["z"] },
        { when: "consonant-final", affix: ["s"] },
      ],
    },
    "noun.case.gen": { affix: ["z"], position: "suffix", category: "noun.case.gen" },
    "verb.tense.past": {
      affix: ["d"],
      position: "suffix",
      category: "verb.tense.past",
      variants: [
        { when: "vowel-final", affix: ["d"] },
        { when: "consonant-final", affix: ["ə", "d"] },
      ],
    },
    "verb.aspect.prog": { affix: ["ɪ", "ŋ"], position: "suffix", category: "verb.aspect.prog" },
    "verb.person.3sg": { affix: ["z"], position: "suffix", category: "verb.person.3sg" },
    "adj.degree.cmp": { affix: ["ə", "r"], position: "suffix", category: "adj.degree.cmp" },
    "adj.degree.sup": { affix: ["ə", "s", "t"], position: "suffix", category: "adj.degree.sup" },
  },
};

export function presetEnglish(): SimulationConfig {
  const base = defaultConfig();
  return {
    ...base,
    seed: "english",
    seedLexicon: LEXICON,
    seedFrequencyHints: FREQ,
    seedMorphology: MORPHOLOGY,
    seedSuppletion: SUPPLETION,
    seedCulturalTier: 3,
    seedStressPattern: "initial",
    // Phase 26b: English infinitive = "to V" particle prefix.
    seedInfinitiveStrategy: { kind: "particle-prefix", particle: "to" },
    // Phase 27a: English allows CCCVCCC (strengths, sphincters); strictness
    // is mild so historical-quality clusters survive but extreme outputs
    // get adapted.
    seedPhonotacticProfile: {
      maxOnset: 3,
      maxCoda: 4,
      maxCluster: 4,
      strictness: 0.4,
    },
    seedGrammar: {
      wordOrder: "SVO",
      affixPosition: "suffix",
      pluralMarking: "affix",
      tenseMarking: "past",
      // Phase 34 Tranche 34c: English future is periphrastic
      // ("will + V" / "going to + V") and English perfect is
      // periphrastic ("have + V"). Seed both as periphrastic.
      futureRealisation: "will-future",
      perfectRealisation: "have-perfect",
      // Phase 35 Tranche 35c/d/e: English typology — two-way
      // demonstrative (this/that), sg/pl number, progressive aspect
      // (be V-ing) overtly marked in addition to simple.
      demonstrativeDistance: "two-way",
      numberSystem: "sg-pl",
      aspectSystem: "prog",
      hasCase: false,
      genderCount: 0,
      articlePresence: "free",
      caseStrategy: "preposition",
      adjectivePosition: "pre",
      possessorPosition: "pre",
      numeralPosition: "pre",
      negationPosition: "pre-verb",
      aspectMarking: "progressive",
      voice: "active",
      moodMarking: "declarative",
      interrogativeStrategy: "inversion",
      prodrop: false,
      alignment: "nom-acc",
      harmony: "none",
      evidentialMarking: "none",
      classifierSystem: false,
      relativeClauseStrategy: "relativizer",
      serialVerbConstructions: false,
      politenessRegister: "none",
    },
    // Phase 31 Tranche 31d: English has no contrastive tone. Stays
    // non-tonal unless explicit areal contact triggers a tonogenesis
    // cascade (out of scope for Phase 31).
    seedToneRegime: "non-tonal",
    // Phase 34 Tranche 34g: declare common English compounds.
    // Initial form is recomposed from parts; transparent until
    // fossilisation. Real-world: many of these started transparent
    // (Old English compound) and gradually fossilised (modern
    // "lord" < hlafweard, "daisy" < dæges-ēage = "day's eye").
    seedCompounds: {
      // All parts must already exist in seedLexicon. Validated at
      // language birth via addCompound which falls back to the bare
      // meaning when a part is missing.
      daylight: { parts: ["day", "light"] },
      moonlight: { parts: ["moon", "light"] },
      sunlight: { parts: ["sun", "light"] },
      sunrise: { parts: ["sun", "rise"] },
      nightfall: { parts: ["night", "fall"] },
      waterfall: { parts: ["water", "fall"] },
      homework: { parts: ["home", "work"] },
      riverside: { parts: ["river", "side"] },
      // Phase 36 Tranche 36f: derivational compounds. Each rebuilt
      // at language birth from base + bound morpheme. The base and
      // suffix evolve independently; sound-change drift on `dark`
      // automatically propagates to `darkness` until the compound
      // fossilises.
      stranger: { parts: ["strange", "-er.agt"] },
      teacher: { parts: ["teach", "-er.agt"] },
      runner: { parts: ["run", "-er.agt"] },
      singer: { parts: ["sing", "-er.agt"] },
      darkness: { parts: ["dark", "-ness"] },
      happiness: { parts: ["happy", "-ness"] },
      sadness: { parts: ["sad", "-ness"] },
      goodness: { parts: ["good", "-ness"] },
      kingdom: { parts: ["king", "-dom"] },
      freedom: { parts: ["free", "-dom"] },
      friendship: { parts: ["friend", "-ship"] },
      childhood: { parts: ["child", "-hood"] },
    },
    seedBoundMorphemes: BOUND_MORPHEMES,
    seedPhonemeTarget: 44,
    // Phase 46a-migration: declare the canonical English module set.
    // Word-order is now module-owned (the realiser reads `meta.order`
    // from the active wordOrder module instead of dispatching
    // `sliceOrder` directly). When `lang.grammar.wordOrder` drifts at
    // runtime, `steps/grammar.ts` swaps the active module to track
    // the new order. Other modules in this list remain pass-through
    // stubs until their own migration lands.
    seedActiveModules: [
      "semantic:lexicon",
      "semantic:clusters",
      "semantic:frequency",
      "semantic:synonymy",
      "semantic:colexification",
      "semantic:borrowing",
      "semantic:calque",
      "semantic:reborrow",
      "semantic:taboo",
      "semantic:coinage",
      "syntactical:wordOrder/svo",
      "syntactical:alignment/nom-acc",
      "syntactical:adj-placement",
      "syntactical:poss-placement",
      "syntactical:num-placement",
      "syntactical:neg-placement",
      "syntactical:relativiser",
      "syntactical:coordination",
      "grammatical:articles",
      "grammatical:number-system",
      "grammatical:aspect",
      "grammatical:reference-tracking",
      "grammatical:numerals",
      "grammatical:demonstratives",
      "morphological:paradigms",
      "morphological:derivation",
      "morphological:inflection-class",
      "morphological:analogy",
    ],
    preset: "english",
  };
}
