import type { SimulationConfig, Lexicon, Meaning } from "../types";
import type { Morphology } from "../morphology/types";
import { defaultConfig } from "../config";

const LEXICON: Lexicon = {
  water: ["w", "ɔ", "t", "ə", "r"],
  fire: ["f", "a", "j", "ə", "r"],
  stone: ["s", "t", "o", "n"],
  earth: ["ə", "r", "θ"],
  sky: ["s", "k", "a", "j"],
  sun: ["s", "ʌ", "n"],
  moon: ["m", "uː", "n"],
  star: ["s", "t", "a", "r"],
  cloud: ["k", "l", "a", "w", "d"],
  rain: ["r", "e", "j", "n"],
  snow: ["s", "n", "o", "w"],
  ice: ["a", "j", "s"],
  wind: ["w", "ɪ", "n", "d"],
  thunder: ["θ", "ʌ", "n", "d", "ə", "r"],
  lightning: ["l", "a", "j", "t", "n", "ɪ", "ŋ"],
  river: ["r", "ɪ", "v", "ə", "r"],
  sea: ["s", "iː"],
  lake: ["l", "e", "j", "k"],
  ocean: ["o", "ʃ", "ə", "n"],
  mountain: ["m", "a", "w", "n", "t", "ə", "n"],
  hill: ["h", "ɪ", "l"],
  valley: ["v", "æ", "l", "i"],
  forest: ["f", "ɔ", "r", "ə", "s", "t"],
  field: ["f", "iː", "l", "d"],
  road: ["r", "o", "d"],
  path: ["p", "æ", "θ"],
  day: ["d", "e", "j"],
  night: ["n", "a", "j", "t"],
  morning: ["m", "ɔ", "r", "n", "ɪ", "ŋ"],
  evening: ["iː", "v", "n", "ɪ", "ŋ"],
  year: ["j", "ɪ", "r"],
  winter: ["w", "ɪ", "n", "t", "ə", "r"],
  summer: ["s", "ʌ", "m", "ə", "r"],
  spring: ["s", "p", "r", "ɪ", "ŋ"],
  time: ["t", "a", "j", "m"],
  tree: ["t", "r", "iː"],
  wood: ["w", "ʊ", "d"],
  leaf: ["l", "iː", "f"],
  flower: ["f", "l", "a", "w", "ə", "r"],
  grass: ["g", "r", "æ", "s"],
  root: ["r", "uː", "t"],
  seed: ["s", "iː", "d"],
  fruit: ["f", "r", "uː", "t"],
  grain: ["g", "r", "e", "j", "n"],
  bark: ["b", "a", "r", "k"],
  oak: ["o", "k"],
  apple: ["æ", "p", "ə", "l"],
  pine: ["p", "a", "j", "n"],
  bush: ["b", "ʊ", "ʃ"],
  vine: ["v", "a", "j", "n"],
  herb: ["ə", "r", "b"],
  mushroom: ["m", "ʌ", "ʃ", "r", "uː", "m"],
  berry: ["b", "ɛ", "r", "i"],
  bread: ["b", "r", "ɛ", "d"],
  meat: ["m", "iː", "t"],
  milk: ["m", "ɪ", "l", "k"],
  cheese: ["tʃ", "iː", "z"],
  egg: ["ɛ", "g"],
  honey: ["h", "ʌ", "n", "i"],
  salt: ["s", "ɔ", "l", "t"],
  sugar: ["ʃ", "ʊ", "g", "ə", "r"],
  oil: ["ɔ", "j", "l"],
  wine: ["w", "a", "j", "n"],
  beer: ["b", "ɪ", "r"],
  dog: ["d", "ɔ", "g"],
  wolf: ["w", "ʊ", "l", "f"],
  horse: ["h", "ɔ", "r", "s"],
  cow: ["k", "a", "w"],
  bull: ["b", "ʊ", "l"],
  sheep: ["ʃ", "iː", "p"],
  goat: ["g", "o", "t"],
  pig: ["p", "ɪ", "g"],
  bear: ["b", "ɛ", "r"],
  deer: ["d", "ɪ", "r"],
  fish: ["f", "ɪ", "ʃ"],
  bird: ["b", "ə", "r", "d"],
  eagle: ["iː", "g", "ə", "l"],
  hawk: ["h", "ɔ", "k"],
  cat: ["k", "æ", "t"],
  mouse: ["m", "a", "w", "s"],
  rabbit: ["r", "æ", "b", "ɪ", "t"],
  fox: ["f", "ɔ", "k", "s"],
  snake: ["s", "n", "e", "j", "k"],
  worm: ["w", "ə", "r", "m"],
  ant: ["æ", "n", "t"],
  bee: ["b", "iː"],
  fly: ["f", "l", "a", "j"],
  spider: ["s", "p", "a", "j", "d", "ə", "r"],
  feather: ["f", "ɛ", "ð", "ə", "r"],
  wing: ["w", "ɪ", "ŋ"],
  horn: ["h", "ɔ", "r", "n"],
  tail: ["t", "e", "j", "l"],
  body: ["b", "ɔ", "d", "i"],
  head: ["h", "ɛ", "d"],
  hair: ["h", "ɛ", "r"],
  face: ["f", "e", "j", "s"],
  eye: ["a", "j"],
  ear: ["ɪ", "r"],
  nose: ["n", "o", "z"],
  mouth: ["m", "a", "w", "θ"],
  tongue: ["t", "ʌ", "ŋ"],
  tooth: ["t", "uː", "θ"],
  lip: ["l", "ɪ", "p"],
  chin: ["tʃ", "ɪ", "n"],
  neck: ["n", "ɛ", "k"],
  shoulder: ["ʃ", "o", "l", "d", "ə", "r"],
  arm: ["a", "r", "m"],
  hand: ["h", "æ", "n", "d"],
  finger: ["f", "ɪ", "ŋ", "g", "ə", "r"],
  nail: ["n", "e", "j", "l"],
  chest: ["tʃ", "ɛ", "s", "t"],
  back: ["b", "æ", "k"],
  belly: ["b", "ɛ", "l", "i"],
  heart: ["h", "a", "r", "t"],
  liver: ["l", "ɪ", "v", "ə", "r"],
  bone: ["b", "o", "n"],
  blood: ["b", "l", "ʌ", "d"],
  skin: ["s", "k", "ɪ", "n"],
  flesh: ["f", "l", "ɛ", "ʃ"],
  knee: ["n", "iː"],
  leg: ["l", "ɛ", "g"],
  foot: ["f", "ʊ", "t"],
  mother: ["m", "ʌ", "ð", "ə", "r"],
  father: ["f", "a", "ð", "ə", "r"],
  son: ["s", "ʌ", "n"],
  daughter: ["d", "ɔ", "t", "ə", "r"],
  brother: ["b", "r", "ʌ", "ð", "ə", "r"],
  sister: ["s", "ɪ", "s", "t", "ə", "r"],
  uncle: ["ʌ", "ŋ", "k", "ə", "l"],
  aunt: ["æ", "n", "t"],
  child: ["tʃ", "a", "j", "l", "d"],
  parent: ["p", "ɛ", "r", "ə", "n", "t"],
  husband: ["h", "ʌ", "z", "b", "ə", "n", "d"],
  wife: ["w", "a", "j", "f"],
  friend: ["f", "r", "ɛ", "n", "d"],
  stranger: ["s", "t", "r", "e", "j", "n", "dʒ", "ə", "r"],
  king: ["k", "ɪ", "ŋ"],
  queen: ["k", "w", "iː", "n"],
  warrior: ["w", "ɔ", "r", "i", "ə", "r"],
  village: ["v", "ɪ", "l", "ɪ", "dʒ"],
  town: ["t", "a", "w", "n"],
  city: ["s", "ɪ", "t", "i"],
  house: ["h", "a", "w", "s"],
  home: ["h", "o", "m"],
  door: ["d", "ɔ", "r"],
  window: ["w", "ɪ", "n", "d", "o"],
  knife: ["n", "a", "j", "f"],
  axe: ["æ", "k", "s"],
  spear: ["s", "p", "ɪ", "r"],
  bow: ["b", "o"],
  arrow: ["æ", "r", "o"],
  rope: ["r", "o", "p"],
  cloth: ["k", "l", "ɔ", "θ"],
  shoe: ["ʃ", "uː"],
  hat: ["h", "æ", "t"],
  ring: ["r", "ɪ", "ŋ"],
  boat: ["b", "o", "t"],
  ship: ["ʃ", "ɪ", "p"],
  cart: ["k", "a", "r", "t"],
  wheel: ["w", "iː", "l"],
  i: ["a", "j"],
  you: ["j", "u"],
  he: ["h", "iː"],
  she: ["ʃ", "iː"],
  it: ["ɪ", "t"],
  "he-she": ["h", "iː"],
  we: ["w", "iː"],
  they: ["ð", "e", "j"],
  this: ["ð", "ɪ", "s"],
  that: ["ð", "æ", "t"],
  here: ["h", "ɪ", "r"],
  there: ["ð", "ɛ", "r"],
  what: ["w", "ʌ", "t"],
  who: ["h", "uː"],
  where: ["w", "ɛ", "r"],
  when: ["w", "ɛ", "n"],
  why: ["w", "a", "j"],
  how: ["h", "a", "w"],
  one: ["w", "ʌ", "n"],
  two: ["t", "uː"],
  three: ["θ", "r", "iː"],
  four: ["f", "ɔ", "r"],
  five: ["f", "a", "j", "v"],
  six: ["s", "ɪ", "k", "s"],
  seven: ["s", "ɛ", "v", "ə", "n"],
  eight: ["e", "j", "t"],
  nine: ["n", "a", "j", "n"],
  ten: ["t", "ɛ", "n"],
  hundred: ["h", "ʌ", "n", "d", "r", "ə", "d"],
  thousand: ["θ", "a", "w", "z", "ə", "n", "d"],
  many: ["m", "ɛ", "n", "i"],
  few: ["f", "j", "u"],
  half: ["h", "æ", "f"],
  big: ["b", "ɪ", "g"],
  small: ["s", "m", "ɔ", "l"],
  new: ["n", "u"],
  old: ["o", "l", "d"],
  good: ["g", "ʊ", "d"],
  bad: ["b", "æ", "d"],
  hot: ["h", "ɔ", "t"],
  cold: ["k", "o", "l", "d"],
  wet: ["w", "ɛ", "t"],
  dry: ["d", "r", "a", "j"],
  long: ["l", "ɔ", "ŋ"],
  short: ["ʃ", "ɔ", "r", "t"],
  hard: ["h", "a", "r", "d"],
  soft: ["s", "ɔ", "f", "t"],
  heavy: ["h", "ɛ", "v", "i"],
  round: ["r", "a", "w", "n", "d"],
  sharp: ["ʃ", "a", "r", "p"],
  sweet: ["s", "w", "iː", "t"],
  sour: ["s", "a", "w", "ə", "r"],
  strong: ["s", "t", "r", "ɔ", "ŋ"],
  weak: ["w", "iː", "k"],
  fast: ["f", "æ", "s", "t"],
  slow: ["s", "l", "o"],
  light: ["l", "a", "j", "t"],
  dark: ["d", "a", "r", "k"],
  go: ["g", "o"],
  come: ["k", "ʌ", "m"],
  walk: ["w", "ɔ", "k"],
  run: ["r", "ʌ", "n"],
  swim: ["s", "w", "ɪ", "m"],
  climb: ["k", "l", "a", "j", "m"],
  fall: ["f", "ɔ", "l"],
  rise: ["r", "a", "j", "z"],
  see: ["s", "iː"],
  know: ["n", "o"],
  hear: ["h", "ɪ", "r"],
  feel: ["f", "iː", "l"],
  smell: ["s", "m", "ɛ", "l"],
  taste: ["t", "e", "j", "s", "t"],
  eat: ["iː", "t"],
  drink: ["d", "r", "ɪ", "ŋ", "k"],
  sleep: ["s", "l", "iː", "p"],
  die: ["d", "a", "j"],
  live: ["l", "ɪ", "v"],
  breathe: ["b", "r", "iː", "ð"],
  sit: ["s", "ɪ", "t"],
  stand: ["s", "t", "æ", "n", "d"],
  give: ["g", "ɪ", "v"],
  take: ["t", "e", "j", "k"],
  throw: ["θ", "r", "o"],
  break: ["b", "r", "e", "j", "k"],
  cut: ["k", "ʌ", "t"],
  kill: ["k", "ɪ", "l"],
  fight: ["f", "a", "j", "t"],
  hunt: ["h", "ʌ", "n", "t"],
  speak: ["s", "p", "iː", "k"],
  say: ["s", "e", "j"],
  sing: ["s", "ɪ", "ŋ"],
  laugh: ["l", "æ", "f"],
  cry: ["k", "r", "a", "j"],
  think: ["θ", "ɪ", "ŋ", "k"],
  love: ["l", "ʌ", "v"],
  fear: ["f", "ɪ", "r"],
  want: ["w", "a", "n", "t"],
  hold: ["h", "o", "l", "d"],
  carry: ["k", "ɛ", "r", "i"],
  push: ["p", "ʊ", "ʃ"],
  pull: ["p", "ʊ", "l"],
  build: ["b", "ɪ", "l", "d"],
  make: ["m", "e", "j", "k"],
  do: ["d", "uː"],
  be: ["b", "iː"],
  have: ["h", "æ", "v"],
  work: ["w", "ə", "r", "k"],
  play: ["p", "l", "e", "j"],
  name: ["n", "e", "j", "m"],
  word: ["w", "ə", "r", "d"],
  story: ["s", "t", "ɔ", "r", "i"],
  song: ["s", "ɔ", "ŋ"],
  truth: ["t", "r", "uː", "θ"],
  god: ["g", "ɔ", "d"],
  spirit: ["s", "p", "ɪ", "r", "ɪ", "t"],
  the: ["ð", "ə"],
  a: ["ə"],
  of: ["ə", "v"],
  to: ["t", "u"],
  in: ["ɪ", "n"],
  on: ["a", "n"],
  at: ["æ", "t"],
  by: ["b", "a", "j"],
  with: ["w", "ɪ", "ð"],
  for: ["f", "ɔ", "r"],
  from: ["f", "r", "ʌ", "m"],
  and: ["æ", "n", "d"],
  or: ["ɔ", "r"],
  not: ["n", "a", "t"],
  if: ["ɪ", "f"],
  yes: ["j", "ɛ", "s"],
  no: ["n", "o"],
};

const FREQ: Record<Meaning, number> = {
  the: 0.99, a: 0.98, of: 0.97, to: 0.97, in: 0.97, and: 0.98, not: 0.96,
  i: 0.99, you: 0.99, we: 0.97, they: 0.95, this: 0.96, that: 0.96,
  be: 0.99, have: 0.97, do: 0.96, go: 0.95, come: 0.94, see: 0.94,
  say: 0.94, know: 0.93, think: 0.92, want: 0.91, take: 0.90, give: 0.90,
  make: 0.91, work: 0.85,
  one: 0.96, two: 0.94, three: 0.92, big: 0.90, small: 0.88, good: 0.92, new: 0.88,
  water: 0.92, fire: 0.85, day: 0.92, night: 0.90, time: 0.95,
  mother: 0.92, father: 0.92, child: 0.90, friend: 0.85, name: 0.92,
  hand: 0.89, foot: 0.88, eye: 0.90, head: 0.88, heart: 0.86,
  eat: 0.92, drink: 0.90, sleep: 0.88, die: 0.85,
};

const MORPHOLOGY: Morphology = {
  paradigms: {
    "noun.num.pl": {
      affix: ["z"],
      position: "suffix",
      category: "noun.num.pl",
      variants: [
        { when: "vowel-final", affix: ["z"] },
        { when: "consonant-final", affix: ["s"] },
      ],
    },
    "noun.case.gen": { affix: ["z"], position: "suffix", category: "noun.case.gen" },
    "verb.tense.past": {
      affix: ["d"],
      position: "suffix",
      category: "verb.tense.past",
      variants: [
        { when: "vowel-final", affix: ["d"] },
        { when: "consonant-final", affix: ["ə", "d"] },
      ],
    },
    "verb.aspect.prog": { affix: ["ɪ", "ŋ"], position: "suffix", category: "verb.aspect.prog" },
    "verb.person.3sg": { affix: ["z"], position: "suffix", category: "verb.person.3sg" },
    "adj.degree.cmp": { affix: ["ə", "r"], position: "suffix", category: "adj.degree.cmp" },
    "adj.degree.sup": { affix: ["ə", "s", "t"], position: "suffix", category: "adj.degree.sup" },
  },
};

export function presetEnglish(): SimulationConfig {
  const base = defaultConfig();
  return {
    ...base,
    seed: "english",
    seedLexicon: LEXICON,
    seedFrequencyHints: FREQ,
    seedMorphology: MORPHOLOGY,
    seedStressPattern: "initial",
    seedGrammar: {
      wordOrder: "SVO",
      affixPosition: "suffix",
      pluralMarking: "affix",
      tenseMarking: "past",
      hasCase: false,
      genderCount: 0,
      articlePresence: "free",
      caseStrategy: "preposition",
      adjectivePosition: "pre",
      possessorPosition: "pre",
      numeralPosition: "pre",
      negationPosition: "pre-verb",
      aspectMarking: "progressive",
      voice: "active",
      moodMarking: "declarative",
      interrogativeStrategy: "inversion",
      prodrop: false,
      alignment: "nom-acc",
      harmony: "none",
      evidentialMarking: "none",
      classifierSystem: false,
      relativeClauseStrategy: "relativizer",
      serialVerbConstructions: false,
      politenessRegister: "none",
    },
    preset: "english",
  };
}
