import type { SimulationConfig, Lexicon, Meaning } from "../types";
import type { Morphology } from "../morphology/types";
import { defaultConfig } from "../config";

// Hand-authored Proto-Germanic seed. Forms are simplified Ringe-style
// reconstructions: PIE after Grimm's Law (p→f, t→θ, k→h, b→p, d→t, g→k)
// and Verner's Law conditioned voicing. Long vowels marked with macron.
const LEXICON: Lexicon = {
  // — natural world / weather —
  water: ["w", "a", "t", "a", "r"],
  fire: ["f", "u", "r"],
  stone: ["s", "t", "a", "i", "n", "a", "z"],
  earth: ["e", "r", "θ", "ō"],
  sky: ["h", "i", "m", "i", "n", "a", "z"],
  sun: ["s", "u", "n", "n", "ō"],
  moon: ["m", "ē", "n", "ō"],
  star: ["s", "t", "e", "r", "n", "ō"],
  cloud: ["w", "u", "l", "k", "n", "a", "z"],
  rain: ["r", "e", "g", "n", "a", "z"],
  snow: ["s", "n", "a", "i", "w", "a", "z"],
  ice: ["ī", "s", "a"],
  wind: ["w", "i", "n", "d", "a", "z"],
  thunder: ["þ", "u", "n", "r", "a", "z"],
  lightning: ["l", "a", "u", "h", "m", "u", "z"],
  river: ["a", "h", "w", "ō"],
  sea: ["s", "a", "i", "w", "i", "z"],
  lake: ["s", "a", "i", "w", "a", "z"],
  mountain: ["b", "e", "r", "g", "a", "z"],
  hill: ["h", "u", "l", "j", "az"],
  valley: ["d", "a", "l", "a"],
  forest: ["w", "a", "l", "þ", "u", "z"],
  field: ["f", "e", "l", "θ", "u", "z"],
  road: ["w", "e", "g", "a", "z"],
  path: ["p", "a", "θ", "a", "z"],
  // — sky cycle / time —
  day: ["d", "a", "g", "a", "z"],
  night: ["n", "a", "h", "t"],
  morning: ["m", "u", "r", "g", "a", "n"],
  evening: ["a", "i", "b", "a", "n", "d", "a", "z"],
  year: ["j", "ē", "r", "a"],
  season: ["s", "ē", "θ", "u"],
  winter: ["w", "i", "n", "t", "r", "u", "z"],
  summer: ["s", "u", "m", "a", "r", "a", "z"],
  time: ["t", "ī", "m", "ô"],
  // — flora / fauna —
  tree: ["b", "a", "g", "m", "a"],
  wood: ["w", "i", "d", "u", "z"],
  leaf: ["l", "a", "u", "b", "a"],
  flower: ["b", "l", "ō", "m", "ô"],
  grass: ["g", "r", "a", "s", "a"],
  root: ["w", "r", "ō", "t", "i", "z"],
  seed: ["s", "ē", "d", "i", "z"],
  fruit: ["a", "k", "r", "a", "n", "a"],
  grain: ["k", "u", "r", "n", "a"],
  bark: ["b", "a", "r", "k", "u", "z"],
  oak: ["a", "i", "k", "s"],
  birch: ["b", "e", "r", "k", "ō"],
  apple: ["a", "p", "l", "u", "z"],
  // — animals —
  dog: ["h", "u", "n", "d", "a", "z"],
  wolf: ["w", "u", "l", "f", "a", "z"],
  horse: ["h", "r", "u", "s", "s", "a"],
  cow: ["k", "ū", "z"],
  bull: ["s", "t", "i", "u", "r", "a", "z"],
  sheep: ["s", "k", "ē", "p", "ą"],
  goat: ["g", "a", "i", "t", "s"],
  pig: ["s", "w", "ī", "n", "ą"],
  bear: ["b", "e", "r", "a", "n"],
  deer: ["d", "i", "u", "z", "ą"],
  fish: ["f", "i", "s", "k", "a", "z"],
  bird: ["f", "u", "g", "l", "a", "z"],
  eagle: ["a", "r", "n", "u", "z"],
  snake: ["w", "u", "r", "m", "i", "z"],
  worm: ["w", "u", "r", "m", "i", "z"],
  louse: ["l", "ū", "s"],
  bee: ["b", "i", "j", "ô"],
  egg: ["a", "j", "j", "a"],
  feather: ["f", "e", "θ", "r", "ō"],
  wing: ["f", "e", "θ", "r", "a"],
  horn: ["h", "u", "r", "n", "a"],
  tail: ["s", "t", "e", "r", "t", "a", "z"],
  // — body —
  body: ["l", "ī", "k", "ą"],
  head: ["h", "a", "u", "β", "u", "ð"],
  hair: ["h", "ē", "r"],
  face: ["a", "n", "d", "i"],
  eye: ["a", "u", "g", "ō"],
  ear: ["a", "u", "s", "ō"],
  nose: ["n", "a", "s", "ō"],
  mouth: ["m", "u", "n", "θ", "a", "z"],
  tooth: ["t", "a", "n", "θ", "s"],
  tongue: ["t", "u", "n", "g", "ō"],
  lip: ["l", "e", "p", "ô"],
  neck: ["h", "a", "l", "s", "a", "z"],
  shoulder: ["s", "k", "u", "l", "d", "r", "ō"],
  arm: ["a", "r", "m", "a", "z"],
  hand: ["h", "a", "n", "d", "u", "z"],
  finger: ["f", "i", "n", "g", "r", "a", "z"],
  nail: ["n", "a", "g", "l", "a", "z"],
  chest: ["b", "r", "u", "s", "t", "s"],
  back: ["h", "r", "u", "g", "j", "a", "z"],
  belly: ["k", "w", "e", "θ", "u", "z"],
  heart: ["h", "e", "r", "t", "ō"],
  liver: ["l", "i", "β", "r", "ō"],
  lung: ["l", "u", "n", "g", "ō"],
  bone: ["b", "a", "i", "n", "a"],
  blood: ["b", "l", "ō", "θ", "a"],
  skin: ["s", "k", "i", "n", "θ", "a"],
  flesh: ["f", "l", "a", "i", "s", "k", "a"],
  knee: ["k", "n", "i", "w", "a"],
  leg: ["l", "a", "g", "j", "a"],
  foot: ["f", "ō", "t", "s"],
  // — kinship / people —
  person: ["m", "a", "n", "n", "a", "n"],
  man: ["w", "i", "r", "a", "z"],
  woman: ["k", "w", "e", "n", "ō"],
  child: ["b", "a", "r", "n", "a"],
  baby: ["k", "i", "n", "θ", "a"],
  mother: ["m", "ō", "t", "ē", "r"],
  father: ["f", "a", "ð", "ē", "r"],
  son: ["s", "u", "n", "u", "z"],
  daughter: ["d", "u", "h", "t", "ē", "r"],
  brother: ["b", "r", "ō", "θ", "ē", "r"],
  sister: ["s", "w", "e", "s", "t", "ē", "r"],
  husband: ["h", "ū", "s", "b", "ō", "n", "d", "a"],
  wife: ["w", "ī", "β", "ą"],
  king: ["k", "u", "n", "i", "n", "g", "a", "z"],
  god: ["g", "u", "ð", "a", "n"],
  guest: ["g", "a", "s", "t", "i", "z"],
  enemy: ["f", "i", "j", "a", "n", "d", "s"],
  // — household / artifact —
  house: ["h", "ū", "s", "ą"],
  door: ["d", "u", "r", "u"],
  hearth: ["h", "e", "r", "θ", "a", "z"],
  yoke: ["j", "u", "k", "ą"],
  wheel: ["h", "w", "e", "h", "w", "l", "a"],
  boat: ["b", "a", "i", "t", "ą"],
  ship: ["s", "k", "i", "p", "a"],
  knife: ["s", "a", "h", "s", "ą"],
  axe: ["a", "k", "w", "e", "s", "ī"],
  spear: ["g", "a", "i", "z", "a", "z"],
  bow: ["b", "u", "g", "ō"],
  arrow: ["a", "r", "h", "w", "ō"],
  rope: ["r", "a", "i", "p", "a"],
  cloth: ["k", "l", "a", "i", "θ", "a"],
  wool: ["w", "u", "l", "l", "ō"],
  // — food / drink —
  bread: ["b", "r", "a", "u", "θ", "ą"],
  meat: ["f", "l", "a", "i", "s", "k", "a"],
  milk: ["m", "e", "l", "u", "k", "s"],
  honey: ["h", "u", "n", "a", "g", "a"],
  salt: ["s", "a", "l", "t", "ą"],
  // — verbs of motion / state —
  be: ["w", "e", "s"],
  go: ["g", "a", "n", "g"],
  come: ["k", "w", "e", "m"],
  walk: ["w", "a", "l", "k"],
  run: ["r", "i", "n", "n"],
  stand: ["s", "t", "a", "n", "d"],
  sit: ["s", "i", "t"],
  lie: ["l", "i", "g"],
  fall: ["f", "a", "l", "l"],
  fly: ["f", "l", "i", "u", "g"],
  swim: ["s", "w", "i", "m"],
  // — verbs of perception / cognition —
  see: ["s", "e", "h", "w"],
  hear: ["h", "a", "u", "z"],
  know: ["k", "u", "n", "n"],
  think: ["þ", "a", "n", "k"],
  speak: ["s", "p", "r", "e", "k"],
  say: ["s", "a", "g", "j"],
  call: ["k", "a", "l", "l"],
  ask: ["b", "i", "d"],
  // — verbs of action —
  do: ["d", "ō", "n"],
  make: ["m", "a", "k"],
  take: ["n", "e", "m"],
  give: ["g", "e", "β"],
  hold: ["h", "a", "l", "d"],
  carry: ["b", "e", "r"],
  throw: ["w", "e", "r", "p"],
  pull: ["t", "e", "u", "h"],
  push: ["s", "t", "a", "u", "t"],
  cut: ["s", "k", "e", "r"],
  break: ["b", "r", "e", "k"],
  bend: ["b", "u", "g"],
  build: ["b", "ū", "w"],
  burn: ["b", "r", "i", "n", "n"],
  wash: ["w", "a", "s", "k"],
  weave: ["w", "e", "β"],
  plant: ["s", "ē"],
  // — verbs of life —
  eat: ["e", "t"],
  drink: ["d", "r", "i", "n", "k"],
  sleep: ["s", "l", "ē", "p"],
  dream: ["d", "r", "a", "u", "m", "a", "z"],
  live: ["l", "i", "β"],
  die: ["d", "a", "u", "þ"],
  bear_child: ["b", "e", "r"],
  grow: ["w", "a", "h", "s"],
  love: ["l", "u", "β"],
  fear: ["f", "u", "r", "h", "t"],
  laugh: ["h", "l", "a", "h"],
  cry: ["w", "ō", "p"],
  // — numbers —
  one: ["a", "i", "n", "a", "z"],
  two: ["t", "w", "a", "i"],
  three: ["θ", "r", "ī", "z"],
  four: ["f", "i", "ð", "w", "ō", "r"],
  five: ["f", "i", "m", "f"],
  six: ["s", "e", "h", "s"],
  seven: ["s", "e", "β", "u", "n"],
  eight: ["a", "h", "t", "ō", "u"],
  nine: ["n", "i", "u", "n"],
  ten: ["t", "e", "h", "u", "n"],
  hundred: ["h", "u", "n", "d", "a"],
  // — qualities —
  big: ["m", "i", "k", "i", "l", "a", "z"],
  small: ["l", "ī", "t", "i", "l", "a", "z"],
  long: ["l", "a", "n", "g", "a", "z"],
  short: ["s", "k", "u", "r", "t", "a", "z"],
  tall: ["h", "a", "u", "h", "a", "z"],
  wide: ["w", "ī", "d", "a", "z"],
  thick: ["þ", "e", "k", "u", "z"],
  thin: ["þ", "u", "n", "n", "u", "z"],
  heavy: ["s", "w", "ē", "r", "a", "z"],
  light: ["l", "i", "h", "t", "a", "z"],
  hot: ["h", "a", "i", "t", "a", "z"],
  cold: ["k", "a", "l", "d", "a", "z"],
  wet: ["w", "ē", "t", "a", "z"],
  dry: ["þ", "u", "r", "s", "u", "z"],
  full: ["f", "u", "l", "l", "a", "z"],
  empty: ["t", "ō", "m", "a", "z"],
  new: ["n", "i", "u", "j", "a", "z"],
  old: ["a", "l", "d", "a", "z"],
  young: ["j", "u", "n", "g", "a", "z"],
  good: ["g", "ō", "d", "a", "z"],
  bad: ["u", "β", "i", "l", "a", "z"],
  sweet: ["s", "w", "ō", "t", "u", "z"],
  bitter: ["b", "i", "t", "r", "a", "z"],
  strong: ["s", "t", "a", "r", "k", "a", "z"],
  weak: ["w", "a", "i", "k", "a", "z"],
  fast: ["s", "n", "e", "l", "l", "a", "z"],
  slow: ["s", "l", "a", "i", "w", "a", "z"],
  // — colour —
  red: ["r", "a", "u", "ð", "a", "z"],
  black: ["s", "w", "a", "r", "t", "a", "z"],
  white: ["h", "w", "ī", "t", "a", "z"],
  green: ["g", "r", "ō", "n", "i", "z"],
  yellow: ["g", "e", "l", "w", "a", "z"],
  blue: ["b", "l", "ē", "w", "a", "z"],
  // — abstract / pronouns —
  name: ["n", "a", "m", "ô"],
  word: ["w", "u", "r", "d", "a"],
  truth: ["s", "a", "n", "θ", "a", "z"],
  this: ["s", "a"],
  that: ["þ", "a", "t"],
  here: ["h", "ē", "r"],
  there: ["þ", "a", "r"],
  i: ["e", "k"],
  you: ["þ", "ū"],
  we: ["w", "ī", "z"],
  they: ["þ", "a", "i"],
};

const FREQ: Record<Meaning, number> = {
  water: 0.95, fire: 0.85, mother: 0.92, father: 0.92, child: 0.9,
  go: 0.96, come: 0.95, eat: 0.95, drink: 0.92, see: 0.94,
  one: 0.97, two: 0.94, three: 0.92, big: 0.9, small: 0.9,
  i: 0.99, you: 0.99, we: 0.97, this: 0.96, that: 0.96,
  be: 0.98, do: 0.95, make: 0.93, give: 0.92, take: 0.92,
  day: 0.92, night: 0.92, sun: 0.88, moon: 0.85,
  hand: 0.89, foot: 0.89, eye: 0.9, head: 0.85,
};

const MORPHOLOGY: Morphology = {
  paradigms: {
    "noun.case.nom": { affix: ["a", "z"], position: "suffix", category: "noun.case.nom" },
    "noun.case.acc": { affix: ["a", "n"], position: "suffix", category: "noun.case.acc" },
    "noun.case.gen": { affix: ["e", "s"], position: "suffix", category: "noun.case.gen" },
    "noun.case.dat": { affix: ["i"], position: "suffix", category: "noun.case.dat" },
    "noun.num.pl": { affix: ["ō", "z"], position: "suffix", category: "noun.num.pl" },
    "verb.tense.past": { affix: ["d", "a"], position: "suffix", category: "verb.tense.past" },
    "verb.person.1sg": { affix: ["ō"], position: "suffix", category: "verb.person.1sg" },
    "verb.person.2sg": { affix: ["i", "z"], position: "suffix", category: "verb.person.2sg" },
    "verb.person.3sg": { affix: ["θ", "i"], position: "suffix", category: "verb.person.3sg" },
  },
};

export function presetGermanic(): SimulationConfig {
  const base = defaultConfig();
  return {
    ...base,
    seed: "germanic",
    seedLexicon: LEXICON,
    seedFrequencyHints: FREQ,
    seedMorphology: MORPHOLOGY,
    preset: "germanic",
  };
}
