import type { SimulationConfig, Lexicon, Meaning } from "../types";
import type { Morphology } from "../morphology/types";
import { defaultConfig } from "../config";

// Hand-authored Proto-Germanic seed. Forms are simplified Ringe-style
// reconstructions: PIE after Grimm's Law (p→f, t→θ, k→h, b→p, d→t, g→k)
// and Verner's Law conditioned voicing. Long vowels marked with macron.
const LEXICON: Lexicon = {
  // — natural world / weather —
  water: ["w", "a", "t", "a", "r"],
  fire: ["f", "u", "r"],
  stone: ["s", "t", "a", "i", "n", "a", "z"],
  earth: ["e", "r", "θ", "oː"],
  sky: ["h", "i", "m", "i", "n", "a", "z"],
  sun: ["s", "u", "n", "n", "oː"],
  moon: ["m", "eː", "n", "oː"],
  star: ["s", "t", "e", "r", "n", "oː"],
  cloud: ["w", "u", "l", "k", "n", "a", "z"],
  rain: ["r", "e", "g", "n", "a", "z"],
  snow: ["s", "n", "a", "i", "w", "a", "z"],
  ice: ["iː", "s", "a"],
  wind: ["w", "i", "n", "d", "a", "z"],
  thunder: ["θ", "u", "n", "r", "a", "z"],
  lightning: ["l", "a", "u", "h", "m", "u", "z"],
  river: ["a", "h", "w", "oː"],
  sea: ["s", "a", "i", "w", "i", "z"],
  lake: ["s", "a", "i", "w", "a", "z"],
  mountain: ["b", "e", "r", "g", "a", "z"],
  hill: ["h", "u", "l", "j", "a", "z"],
  valley: ["d", "a", "l", "a"],
  forest: ["w", "a", "l", "θ", "u", "z"],
  field: ["f", "e", "l", "θ", "u", "z"],
  road: ["w", "e", "g", "a", "z"],
  path: ["p", "a", "θ", "a", "z"],
  // — sky cycle / time —
  day: ["d", "a", "g", "a", "z"],
  night: ["n", "a", "h", "t"],
  morning: ["m", "u", "r", "g", "a", "n"],
  evening: ["a", "i", "b", "a", "n", "d", "a", "z"],
  year: ["j", "eː", "r", "a"],
  season: ["s", "eː", "θ", "u"],
  winter: ["w", "i", "n", "t", "r", "u", "z"],
  summer: ["s", "u", "m", "a", "r", "a", "z"],
  time: ["t", "iː", "m", "oː"],
  // — flora / fauna —
  tree: ["b", "a", "g", "m", "a"],
  wood: ["w", "i", "d", "u", "z"],
  leaf: ["l", "a", "u", "b", "a"],
  flower: ["b", "l", "oː", "m", "oː"],
  grass: ["g", "r", "a", "s", "a"],
  root: ["w", "r", "oː", "t", "i", "z"],
  seed: ["s", "eː", "d", "i", "z"],
  fruit: ["a", "k", "r", "a", "n", "a"],
  grain: ["k", "u", "r", "n", "a"],
  bark: ["b", "a", "r", "k", "u", "z"],
  oak: ["a", "i", "k", "s"],
  birch: ["b", "e", "r", "k", "oː"],
  apple: ["a", "p", "l", "u", "z"],
  // — animals —
  dog: ["h", "u", "n", "d", "a", "z"],
  wolf: ["w", "u", "l", "f", "a", "z"],
  horse: ["h", "r", "u", "s", "s", "a"],
  cow: ["k", "uː", "z"],
  bull: ["s", "t", "i", "u", "r", "a", "z"],
  sheep: ["s", "k", "eː", "p", "ã"],
  goat: ["g", "a", "i", "t", "s"],
  pig: ["s", "w", "iː", "n", "ã"],
  bear: ["b", "e", "r", "a", "n"],
  deer: ["d", "i", "u", "z", "ã"],
  fish: ["f", "i", "s", "k", "a", "z"],
  bird: ["f", "u", "g", "l", "a", "z"],
  eagle: ["a", "r", "n", "u", "z"],
  snake: ["w", "u", "r", "m", "i", "z"],
  worm: ["w", "u", "r", "m", "i", "z"],
  louse: ["l", "uː", "s"],
  bee: ["b", "i", "j", "oː"],
  egg: ["a", "j", "j", "a"],
  feather: ["f", "e", "θ", "r", "oː"],
  wing: ["f", "e", "θ", "r", "a"],
  horn: ["h", "u", "r", "n", "a"],
  tail: ["s", "t", "e", "r", "t", "a", "z"],
  // — body —
  body: ["l", "iː", "k", "ã"],
  head: ["h", "a", "u", "β", "u", "ð"],
  hair: ["h", "eː", "r"],
  face: ["a", "n", "d", "i"],
  eye: ["a", "u", "g", "oː"],
  ear: ["a", "u", "s", "oː"],
  nose: ["n", "a", "s", "oː"],
  mouth: ["m", "u", "n", "θ", "a", "z"],
  tooth: ["t", "a", "n", "θ", "s"],
  tongue: ["t", "u", "n", "g", "oː"],
  lip: ["l", "e", "p", "oː"],
  neck: ["h", "a", "l", "s", "a", "z"],
  shoulder: ["s", "k", "u", "l", "d", "r", "oː"],
  arm: ["a", "r", "m", "a", "z"],
  hand: ["h", "a", "n", "d", "u", "z"],
  finger: ["f", "i", "n", "g", "r", "a", "z"],
  nail: ["n", "a", "g", "l", "a", "z"],
  chest: ["b", "r", "u", "s", "t", "s"],
  back: ["h", "r", "u", "g", "j", "a", "z"],
  belly: ["k", "w", "e", "θ", "u", "z"],
  heart: ["h", "e", "r", "t", "oː"],
  liver: ["l", "i", "β", "r", "oː"],
  lung: ["l", "u", "n", "g", "oː"],
  bone: ["b", "a", "i", "n", "a"],
  blood: ["b", "l", "oː", "θ", "a"],
  skin: ["s", "k", "i", "n", "θ", "a"],
  flesh: ["f", "l", "a", "i", "s", "k", "a"],
  knee: ["k", "n", "i", "w", "a"],
  leg: ["l", "a", "g", "j", "a"],
  foot: ["f", "oː", "t", "s"],
  // — kinship / people —
  person: ["m", "a", "n", "n", "a", "n"],
  man: ["w", "i", "r", "a", "z"],
  woman: ["k", "w", "e", "n", "oː"],
  child: ["b", "a", "r", "n", "a"],
  baby: ["k", "i", "n", "θ", "a"],
  mother: ["m", "oː", "t", "eː", "r"],
  father: ["f", "a", "ð", "eː", "r"],
  son: ["s", "u", "n", "u", "z"],
  daughter: ["d", "u", "h", "t", "eː", "r"],
  brother: ["b", "r", "oː", "θ", "eː", "r"],
  sister: ["s", "w", "e", "s", "t", "eː", "r"],
  husband: ["h", "uː", "s", "b", "oː", "n", "d", "a"],
  wife: ["w", "iː", "β", "ã"],
  king: ["k", "u", "n", "i", "n", "g", "a", "z"],
  god: ["g", "u", "ð", "a", "n"],
  guest: ["g", "a", "s", "t", "i", "z"],
  enemy: ["f", "i", "j", "a", "n", "d", "s"],
  // — household / artifact —
  house: ["h", "uː", "s", "ã"],
  door: ["d", "u", "r", "u"],
  hearth: ["h", "e", "r", "θ", "a", "z"],
  yoke: ["j", "u", "k", "ã"],
  wheel: ["h", "w", "e", "h", "w", "l", "a"],
  boat: ["b", "a", "i", "t", "ã"],
  ship: ["s", "k", "i", "p", "a"],
  knife: ["s", "a", "h", "s", "ã"],
  axe: ["a", "k", "w", "e", "s", "iː"],
  spear: ["g", "a", "i", "z", "a", "z"],
  bow: ["b", "u", "g", "oː"],
  arrow: ["a", "r", "h", "w", "oː"],
  rope: ["r", "a", "i", "p", "a"],
  cloth: ["k", "l", "a", "i", "θ", "a"],
  wool: ["w", "u", "l", "l", "oː"],
  // — food / drink —
  bread: ["b", "r", "a", "u", "θ", "ã"],
  meat: ["f", "l", "a", "i", "s", "k", "a"],
  milk: ["m", "e", "l", "u", "k", "s"],
  honey: ["h", "u", "n", "a", "g", "a"],
  salt: ["s", "a", "l", "t", "ã"],
  // — verbs of motion / state —
  be: ["w", "e", "s"],
  go: ["g", "a", "n", "g"],
  come: ["k", "w", "e", "m"],
  walk: ["w", "a", "l", "k"],
  run: ["r", "i", "n", "n"],
  stand: ["s", "t", "a", "n", "d"],
  sit: ["s", "i", "t"],
  lie: ["l", "i", "g"],
  fall: ["f", "a", "l", "l"],
  fly: ["f", "l", "i", "u", "g"],
  swim: ["s", "w", "i", "m"],
  // — verbs of perception / cognition —
  see: ["s", "e", "h", "w"],
  hear: ["h", "a", "u", "z"],
  know: ["k", "u", "n", "n"],
  think: ["θ", "a", "n", "k"],
  speak: ["s", "p", "r", "e", "k"],
  say: ["s", "a", "g", "j"],
  call: ["k", "a", "l", "l"],
  ask: ["b", "i", "d"],
  // — verbs of action —
  do: ["d", "oː", "n"],
  make: ["m", "a", "k"],
  take: ["n", "e", "m"],
  give: ["g", "e", "β"],
  hold: ["h", "a", "l", "d"],
  carry: ["b", "e", "r"],
  throw: ["w", "e", "r", "p"],
  pull: ["t", "e", "u", "h"],
  push: ["s", "t", "a", "u", "t"],
  cut: ["s", "k", "e", "r"],
  break: ["b", "r", "e", "k"],
  bend: ["b", "u", "g"],
  build: ["b", "uː", "w"],
  burn: ["b", "r", "i", "n", "n"],
  wash: ["w", "a", "s", "k"],
  weave: ["w", "e", "β"],
  plant: ["s", "eː"],
  // — verbs of life —
  eat: ["e", "t"],
  drink: ["d", "r", "i", "n", "k"],
  sleep: ["s", "l", "eː", "p"],
  dream: ["d", "r", "a", "u", "m", "a", "z"],
  live: ["l", "i", "β"],
  die: ["d", "a", "u", "θ"],
  bear_child: ["b", "e", "r"],
  grow: ["w", "a", "h", "s"],
  love: ["l", "u", "β"],
  fear: ["f", "u", "r", "h", "t"],
  laugh: ["h", "l", "a", "h"],
  cry: ["w", "oː", "p"],
  // — numbers —
  one: ["a", "i", "n", "a", "z"],
  two: ["t", "w", "a", "i"],
  three: ["θ", "r", "iː", "z"],
  four: ["f", "i", "ð", "w", "oː", "r"],
  five: ["f", "i", "m", "f"],
  six: ["s", "e", "h", "s"],
  seven: ["s", "e", "β", "u", "n"],
  eight: ["a", "h", "t", "oː", "u"],
  nine: ["n", "i", "u", "n"],
  ten: ["t", "e", "h", "u", "n"],
  hundred: ["h", "u", "n", "d", "a"],
  // — qualities —
  big: ["m", "i", "k", "i", "l", "a", "z"],
  small: ["l", "iː", "t", "i", "l", "a", "z"],
  long: ["l", "a", "n", "g", "a", "z"],
  short: ["s", "k", "u", "r", "t", "a", "z"],
  tall: ["h", "a", "u", "h", "a", "z"],
  wide: ["w", "iː", "d", "a", "z"],
  thick: ["θ", "e", "k", "u", "z"],
  thin: ["θ", "u", "n", "n", "u", "z"],
  heavy: ["s", "w", "eː", "r", "a", "z"],
  light: ["l", "i", "h", "t", "a", "z"],
  hot: ["h", "a", "i", "t", "a", "z"],
  cold: ["k", "a", "l", "d", "a", "z"],
  wet: ["w", "eː", "t", "a", "z"],
  dry: ["θ", "u", "r", "s", "u", "z"],
  full: ["f", "u", "l", "l", "a", "z"],
  empty: ["t", "oː", "m", "a", "z"],
  new: ["n", "i", "u", "j", "a", "z"],
  old: ["a", "l", "d", "a", "z"],
  young: ["j", "u", "n", "g", "a", "z"],
  good: ["g", "oː", "d", "a", "z"],
  bad: ["u", "β", "i", "l", "a", "z"],
  sweet: ["s", "w", "oː", "t", "u", "z"],
  bitter: ["b", "i", "t", "r", "a", "z"],
  strong: ["s", "t", "a", "r", "k", "a", "z"],
  weak: ["w", "a", "i", "k", "a", "z"],
  fast: ["s", "n", "e", "l", "l", "a", "z"],
  slow: ["s", "l", "a", "i", "w", "a", "z"],
  // — colour —
  red: ["r", "a", "u", "ð", "a", "z"],
  black: ["s", "w", "a", "r", "t", "a", "z"],
  white: ["h", "w", "iː", "t", "a", "z"],
  green: ["g", "r", "oː", "n", "i", "z"],
  yellow: ["g", "e", "l", "w", "a", "z"],
  blue: ["b", "l", "eː", "w", "a", "z"],
  // — abstract / pronouns —
  name: ["n", "a", "m", "oː"],
  word: ["w", "u", "r", "d", "a"],
  truth: ["s", "a", "n", "θ", "a", "z"],
  this: ["s", "a"],
  that: ["θ", "a", "t"],
  here: ["h", "eː", "r"],
  there: ["θ", "a", "r"],
  i: ["e", "k"],
  you: ["θ", "uː"],
  we: ["w", "iː", "z"],
  they: ["θ", "a", "i"],
  // — closed-class roots (Proto-Germanic *sa / *þat / *jainaz; *ne;
  //   *unde; *ana; *furi; *bi). Articles are reflexes of the *sa
  //   demonstrative — turning articlePresence on lets the engine
  //   surface them. —
  he: ["s", "a"],
  she: ["s", "oː"],
  it: ["θ", "a", "t"],
  the: ["θ", "ə"],
  a: ["a"],
  and: ["u", "n", "d"],
  or: ["e", "θ", "θ"],
  not: ["n", "e"],
  in: ["i", "n"],
  on: ["a", "n", "a"],
  to: ["t", "oː"],
  for: ["f", "u", "r", "i"],
  by: ["b", "i"],
};

const FREQ: Record<Meaning, number> = {
  water: 0.95, fire: 0.85, mother: 0.92, father: 0.92, child: 0.9,
  go: 0.96, come: 0.95, eat: 0.95, drink: 0.92, see: 0.94,
  one: 0.97, two: 0.94, three: 0.92, big: 0.9, small: 0.9,
  i: 0.99, you: 0.99, we: 0.97, this: 0.96, that: 0.96,
  be: 0.98, do: 0.95, make: 0.93, give: 0.92, take: 0.92,
  day: 0.92, night: 0.92, sun: 0.88, moon: 0.85,
  hand: 0.89, foot: 0.89, eye: 0.9, head: 0.85,
};

const MORPHOLOGY: Morphology = {
  paradigms: {
    "noun.case.nom": { affix: ["a", "z"], position: "suffix", category: "noun.case.nom" },
    "noun.case.acc": { affix: ["a", "n"], position: "suffix", category: "noun.case.acc" },
    "noun.case.gen": { affix: ["e", "s"], position: "suffix", category: "noun.case.gen" },
    "noun.case.dat": { affix: ["i"], position: "suffix", category: "noun.case.dat" },
    "noun.num.pl": { affix: ["oː", "z"], position: "suffix", category: "noun.num.pl" },
    "verb.tense.past": { affix: ["d", "a"], position: "suffix", category: "verb.tense.past" },
    "verb.person.1sg": { affix: ["oː"], position: "suffix", category: "verb.person.1sg" },
    "verb.person.2sg": { affix: ["i", "z"], position: "suffix", category: "verb.person.2sg" },
    "verb.person.3sg": { affix: ["θ", "i"], position: "suffix", category: "verb.person.3sg" },
  },
};

export function presetGermanic(): SimulationConfig {
  const base = defaultConfig();
  return {
    ...base,
    seed: "germanic",
    seedLexicon: LEXICON,
    seedFrequencyHints: FREQ,
    seedMorphology: MORPHOLOGY,
    // Germanic typology: SOV → SVO drift over time; free articles
    // (`the`-style); preposition strategy for case marking; pre-noun
    // adjectives.
    seedGrammar: {
      wordOrder: "SVO",
      articlePresence: "free",
      caseStrategy: "preposition",
      adjectivePosition: "pre",
      possessorPosition: "pre",
    },
    preset: "germanic",
  };
}
