import type { SimulationConfig, Lexicon, Meaning } from "../types";
import type { Morphology } from "../morphology/types";
import { defaultConfig } from "../config";

// Phase 48 T15: Germanic preset notation notes.
//
// - Word-final `ã` represents Proto-Germanic neuter / masculine
//   accusative singular endings (*-ą / *-an), reconstructed with a
//   nasalised final vowel. These are NOT phonemic nasal-vowel
//   contrasts (PGmc had no /ã/ vs /a/ contrast); they're the
//   reconstruction-tradition realisation of *-an/*-ą with the nasal
//   eroding into the preceding vowel. Daughters denasalise via
//   regular sound change.
// - Labiovelars (`kʷ`, `xʷ`) and palatalised stops (`kʲ`, `gʲ`) are
//   inherited from PIE. PGmc lost most labiovelars (a few survive in
//   reconstructions like *kʷena- "woman").
// - Long vowels marked with `ː`. Length is phonemic in PGmc.
const LEXICON: Lexicon = {
  water: ["w", "a", "t", "a", "ɾ"],
  fire: ["f", "u", "ɾ"],
  stone: ["s", "t", "a", "i", "n", "a", "z"],
  earth: ["e", "ɾ", "θ", "oː"],
  sky: ["x", "i", "m", "i", "n", "a", "z"],
  sun: ["s", "u", "n", "n", "oː"],
  moon: ["m", "eː", "n", "oː"],
  star: ["s", "t", "e", "ɾ", "n", "oː"],
  cloud: ["w", "u", "l", "k", "n", "a", "z"],
  rain: ["ɾ", "e", "g", "n", "a", "z"],
  snow: ["s", "n", "a", "i", "w", "a", "z"],
  ice: ["iː", "s", "a"],
  wind: ["w", "i", "n", "d", "a", "z"],
  thunder: ["θ", "u", "n", "ɾ", "a", "z"],
  lightning: ["l", "a", "u", "x", "m", "u", "z"],
  river: ["a", "xʷ", "oː"],
  sea: ["s", "a", "i", "w", "i", "z"],
  lake: ["s", "a", "i", "w", "a", "z"],
  mountain: ["b", "e", "ɾ", "g", "a", "z"],
  hill: ["x", "u", "l", "j", "a", "z"],
  valley: ["d", "a", "l", "a"],
  forest: ["w", "a", "l", "θ", "u", "z"],
  field: ["f", "e", "l", "θ", "u", "z"],
  road: ["w", "e", "g", "a", "z"],
  path: ["p", "a", "θ", "a", "z"],
  day: ["d", "a", "g", "a", "z"],
  night: ["n", "a", "x", "t"],
  morning: ["m", "u", "ɾ", "g", "a", "n"],
  evening: ["a", "i", "b", "a", "n", "d", "a", "z"],
  year: ["j", "eː", "ɾ", "a"],
  season: ["s", "eː", "θ", "u"],
  winter: ["w", "i", "n", "t", "ɾ", "u", "z"],
  summer: ["s", "u", "m", "a", "ɾ", "a", "z"],
  time: ["t", "iː", "m", "oː"],
  tree: ["b", "a", "g", "m", "a"],
  wood: ["w", "i", "d", "u", "z"],
  leaf: ["l", "a", "u", "b", "a"],
  flower: ["b", "l", "oː", "m", "oː"],
  grass: ["g", "ɾ", "a", "s", "a"],
  root: ["w", "ɾ", "oː", "t", "i", "z"],
  seed: ["s", "eː", "d", "i", "z"],
  fruit: ["a", "k", "ɾ", "a", "n", "a"],
  grain: ["k", "u", "ɾ", "n", "a"],
  bark: ["b", "a", "ɾ", "k", "u", "z"],
  oak: ["a", "i", "k", "s"],
  birch: ["b", "e", "ɾ", "k", "oː"],
  apple: ["a", "p", "l", "u", "z"],
  dog: ["x", "u", "n", "d", "a", "z"],
  wolf: ["w", "u", "l", "f", "a", "z"],
  horse: ["x", "ɾ", "u", "s", "s", "a"],
  cow: ["k", "uː", "z"],
  bull: ["s", "t", "i", "u", "ɾ", "a", "z"],
  sheep: ["s", "k", "eː", "p", "ã"],
  goat: ["g", "a", "i", "t", "s"],
  pig: ["s", "w", "iː", "n", "ã"],
  bear: ["b", "e", "ɾ", "a", "n"],
  deer: ["d", "i", "u", "z", "ã"],
  fish: ["f", "i", "s", "k", "a", "z"],
  bird: ["f", "u", "g", "l", "a", "z"],
  eagle: ["a", "ɾ", "n", "u", "z"],
  snake: ["w", "u", "ɾ", "m", "i", "z"],
  worm: ["w", "u", "ɾ", "m", "i", "z"],
  louse: ["l", "uː", "s"],
  bee: ["b", "i", "j", "oː"],
  egg: ["a", "j", "j", "a"],
  feather: ["f", "e", "θ", "ɾ", "oː"],
  wing: ["f", "e", "θ", "ɾ", "a"],
  horn: ["x", "u", "ɾ", "n", "a"],
  tail: ["s", "t", "e", "ɾ", "t", "a", "z"],
  body: ["l", "iː", "k", "ã"],
  head: ["x", "a", "u", "b", "u", "d"],
  hair: ["x", "eː", "ɾ"],
  face: ["a", "n", "d", "i"],
  eye: ["a", "u", "g", "oː"],
  ear: ["a", "u", "s", "oː"],
  nose: ["n", "a", "s", "oː"],
  mouth: ["m", "u", "n", "θ", "a", "z"],
  tooth: ["t", "a", "n", "θ", "s"],
  tongue: ["t", "u", "n", "g", "oː"],
  lip: ["l", "e", "p", "oː"],
  neck: ["x", "a", "l", "s", "a", "z"],
  shoulder: ["s", "k", "u", "l", "d", "ɾ", "oː"],
  arm: ["a", "ɾ", "m", "a", "z"],
  hand: ["x", "a", "n", "d", "u", "z"],
  finger: ["f", "i", "n", "g", "ɾ", "a", "z"],
  nail: ["n", "a", "g", "l", "a", "z"],
  chest: ["b", "ɾ", "u", "s", "t", "s"],
  back: ["x", "ɾ", "u", "g", "j", "a", "z"],
  belly: ["kʷ", "e", "θ", "u", "z"],
  heart: ["x", "e", "ɾ", "t", "oː"],
  liver: ["l", "i", "b", "ɾ", "oː"],
  lung: ["l", "u", "n", "g", "oː"],
  bone: ["b", "a", "i", "n", "a"],
  blood: ["b", "l", "oː", "θ", "a"],
  skin: ["s", "k", "i", "n", "θ", "a"],
  flesh: ["f", "l", "a", "i", "s", "k", "a"],
  knee: ["k", "n", "i", "w", "a"],
  leg: ["l", "a", "g", "j", "a"],
  foot: ["f", "oː", "t", "s"],
  person: ["m", "a", "n", "n", "a", "n"],
  man: ["w", "i", "ɾ", "a", "z"],
  woman: ["kʷ", "e", "n", "oː"],
  child: ["b", "a", "ɾ", "n", "a"],
  baby: ["k", "i", "n", "θ", "a"],
  mother: ["m", "oː", "t", "eː", "ɾ"],
  father: ["f", "a", "d", "eː", "ɾ"],
  son: ["s", "u", "n", "u", "z"],
  daughter: ["d", "u", "x", "t", "eː", "ɾ"],
  brother: ["b", "ɾ", "oː", "θ", "eː", "ɾ"],
  sister: ["s", "w", "e", "s", "t", "eː", "ɾ"],
  wife: ["w", "iː", "b", "ã"],
  friend: ["f", "ɾ", "i", "j", "oː", "n", "d", "s"],
  king: ["k", "u", "n", "i", "n", "g", "a", "z"],
  god: ["g", "u", "d", "a", "n"],
  guest: ["g", "a", "s", "t", "i", "z"],
  enemy: ["f", "i", "j", "a", "n", "d", "s"],
  house: ["x", "uː", "s", "ã"],
  door: ["d", "u", "ɾ", "u"],
  hearth: ["x", "e", "ɾ", "θ", "a", "z"],
  yoke: ["j", "u", "k", "ã"],
  wheel: ["xʷ", "e", "xʷ", "l", "a"],
  boat: ["b", "a", "i", "t", "ã"],
  ship: ["s", "k", "i", "p", "a"],
  knife: ["s", "a", "x", "s", "ã"],
  axe: ["a", "kʷ", "e", "s", "iː"],
  spear: ["g", "a", "i", "z", "a", "z"],
  bow: ["b", "u", "g", "oː"],
  arrow: ["a", "ɾ", "xʷ", "oː"],
  rope: ["ɾ", "a", "i", "p", "a"],
  cloth: ["k", "l", "a", "i", "θ", "a"],
  wool: ["w", "u", "l", "l", "oː"],
  bread: ["b", "ɾ", "a", "u", "θ", "ã"],
  meat: ["f", "l", "a", "i", "s", "k", "a"],
  milk: ["m", "e", "l", "u", "k", "s"],
  honey: ["x", "u", "n", "a", "g", "a"],
  salt: ["s", "a", "l", "t", "ã"],
  be: ["w", "e", "s"],
  go: ["g", "a", "n", "g"],
  come: ["kʷ", "e", "m"],
  walk: ["w", "a", "l", "k"],
  run: ["ɾ", "i", "n", "n"],
  stand: ["s", "t", "a", "n", "d"],
  sit: ["s", "i", "t"],
  lie: ["l", "i", "g"],
  fall: ["f", "a", "l", "l"],
  fly: ["f", "l", "i", "u", "g"],
  swim: ["s", "w", "i", "m"],
  see: ["s", "e", "xʷ"],
  hear: ["x", "a", "u", "z"],
  know: ["k", "u", "n", "n"],
  think: ["θ", "a", "n", "k"],
  speak: ["s", "p", "ɾ", "e", "k"],
  say: ["s", "a", "g", "j"],
  call: ["k", "a", "l", "l"],
  ask: ["b", "i", "d"],
  do: ["d", "oː", "n"],
  make: ["m", "a", "k"],
  take: ["n", "e", "m"],
  give: ["g", "e", "b"],
  hold: ["x", "a", "l", "d"],
  carry: ["b", "e", "ɾ"],
  throw: ["w", "e", "ɾ", "p"],
  pull: ["t", "e", "u", "x"],
  push: ["s", "t", "a", "u", "t"],
  cut: ["s", "k", "e", "ɾ"],
  break: ["b", "ɾ", "e", "k"],
  bend: ["b", "u", "g"],
  build: ["b", "uː", "w"],
  burn: ["b", "ɾ", "i", "n", "n"],
  wash: ["w", "a", "s", "k"],
  weave: ["w", "e", "b"],
  plant: ["s", "eː"],
  eat: ["e", "t"],
  drink: ["d", "ɾ", "i", "n", "k"],
  sleep: ["s", "l", "eː", "p"],
  dream: ["d", "ɾ", "a", "u", "m", "a", "z"],
  live: ["l", "i", "b"],
  die: ["d", "a", "u", "θ"],
  bear_child: ["b", "e", "ɾ"],
  grow: ["w", "a", "x", "s"],
  love: ["l", "u", "b"],
  fear: ["f", "u", "ɾ", "x", "t"],
  laugh: ["x", "l", "a", "x"],
  cry: ["w", "oː", "p"],
  one: ["a", "i", "n", "a", "z"],
  two: ["t", "w", "a", "i"],
  three: ["θ", "ɾ", "iː", "z"],
  four: ["f", "i", "d", "w", "oː", "ɾ"],
  five: ["f", "i", "m", "f"],
  six: ["s", "e", "x", "s"],
  seven: ["s", "e", "b", "u", "n"],
  eight: ["a", "x", "t", "oː", "u"],
  nine: ["n", "i", "u", "n"],
  ten: ["t", "e", "x", "u", "n"],
  hundred: ["x", "u", "n", "d", "a"],
  big: ["m", "i", "k", "i", "l", "a", "z"],
  small: ["l", "iː", "t", "i", "l", "a", "z"],
  long: ["l", "a", "n", "g", "a", "z"],
  short: ["s", "k", "u", "ɾ", "t", "a", "z"],
  tall: ["x", "a", "u", "x", "a", "z"],
  wide: ["w", "iː", "d", "a", "z"],
  thick: ["θ", "e", "k", "u", "z"],
  thin: ["θ", "u", "n", "n", "u", "z"],
  heavy: ["s", "w", "eː", "ɾ", "a", "z"],
  light: ["l", "i", "x", "t", "a", "z"],
  hot: ["x", "a", "i", "t", "a", "z"],
  cold: ["k", "a", "l", "d", "a", "z"],
  wet: ["w", "eː", "t", "a", "z"],
  dry: ["θ", "u", "ɾ", "s", "u", "z"],
  full: ["f", "u", "l", "l", "a", "z"],
  empty: ["t", "oː", "m", "a", "z"],
  new: ["n", "i", "u", "j", "a", "z"],
  old: ["a", "l", "d", "a", "z"],
  young: ["j", "u", "n", "g", "a", "z"],
  good: ["g", "oː", "d", "a", "z"],
  bad: ["u", "b", "i", "l", "a", "z"],
  sweet: ["s", "w", "oː", "t", "u", "z"],
  bitter: ["b", "i", "t", "ɾ", "a", "z"],
  strong: ["s", "t", "a", "ɾ", "k", "a", "z"],
  weak: ["w", "a", "i", "k", "a", "z"],
  fast: ["s", "n", "e", "l", "l", "a", "z"],
  slow: ["s", "l", "a", "i", "w", "a", "z"],
  red: ["ɾ", "a", "u", "d", "a", "z"],
  black: ["s", "w", "a", "ɾ", "t", "a", "z"],
  white: ["xʷ", "iː", "t", "a", "z"],
  green: ["g", "ɾ", "oː", "n", "i", "z"],
  yellow: ["g", "e", "l", "w", "a", "z"],
  blue: ["b", "l", "eː", "w", "a", "z"],
  name: ["n", "a", "m", "oː"],
  word: ["w", "u", "ɾ", "d", "a"],
  truth: ["s", "a", "n", "θ", "a", "z"],
  this: ["s", "a"],
  that: ["θ", "a", "t"],
  here: ["x", "eː", "ɾ"],
  there: ["θ", "a", "ɾ"],
  i: ["e", "k"],
  you: ["θ", "uː"],
  we: ["w", "iː", "z"],
  they: ["θ", "a", "i"],
  he: ["s", "a"],
  she: ["s", "oː"],
  it: ["θ", "a", "t"],
  the: ["θ", "ə"],
  a: ["a"],
  and: ["u", "n", "d"],
  or: ["e", "θ", "θ"],
  not: ["n", "e"],
  in: ["i", "n"],
  on: ["a", "n", "a"],
  to: ["t", "oː"],
  for: ["f", "u", "ɾ", "i"],
  by: ["b", "i"],
  // Phase 36 Tranche 36n: Proto-Germanic derivational morphemes.
  // -arja agentive (PGmc *bakarjaz "baker"), -iþō abstract noun
  // (*frijaþō → freedom), -uŋgō nominalisation (*dengwuŋgō →
  // -ing), -laikaz adjectival (*frijalaikaz → -ly), -skapiz
  // collective (*friundskapiz → -ship).
  "-arja.agt": ["a", "ɾ", "j", "a"],
  "-iþō.abs": ["i", "θ", "oː"],
  "-uŋgō.nmlz": ["u", "ŋ", "g", "oː"],
  "-laikaz.adj": ["l", "a", "j", "k", "a", "z"],
  "-skapiz.coll": ["s", "k", "a", "p", "i", "z"],
  // Phase 47 T4: Germanic typology = SVO + balanced (Greenberg). Add
  // prefixes covering negation, repetition, reversal, and away. These
  // mirror the Proto-Germanic / Old English inventory.
  "un-": ["u", "n"],
  "ga-": ["g", "a"],
  "fra-": ["f", "ɾ", "a"],
  "ufar-": ["u", "f", "a", "ɾ"],
};

const GERMANIC_BOUND_MORPHEMES = new Set<string>([
  "-arja.agt", "-iþō.abs", "-uŋgō.nmlz", "-laikaz.adj", "-skapiz.coll",
  // Phase 47 T4: derivational prefixes (un- is also negational; counted
  // in NEGATIONAL_TAGS at synthesis time so it fires only on rung 5).
  "un-", "ga-", "fra-", "ufar-",
]);

// Phase 29 Tranche 5s: deepened Germanic frequency hints.
const FREQ: Record<Meaning, number> = {
  // Pronouns + closed-class
  i: 0.99, you: 0.99, we: 0.97, they: 0.95, he: 0.96, she: 0.96, it: 0.95,
  this: 0.96, that: 0.96, here: 0.92, there: 0.92,
  not: 0.97, and: 0.98, or: 0.93,
  // Top verbs — Germanic strong-verb candidates
  be: 0.98, have: 0.97, do: 0.95, go: 0.96, come: 0.95,
  see: 0.94, say: 0.94, know: 0.93, give: 0.92, take: 0.92,
  make: 0.93, find: 0.88, want: 0.93, eat: 0.95, drink: 0.92,
  walk: 0.85, run: 0.85, sleep: 0.88, hear: 0.88, speak: 0.88,
  // Kinship / body — high persistence
  mother: 0.92, father: 0.92, child: 0.9, brother: 0.85, sister: 0.85,
  hand: 0.89, foot: 0.89, eye: 0.9, head: 0.85, mouth: 0.85,
  ear: 0.83, heart: 0.85, blood: 0.85,
  one: 0.97, two: 0.94, three: 0.92, four: 0.86, five: 0.86,
  // Common nouns
  water: 0.95, fire: 0.85, day: 0.92, night: 0.92, sun: 0.88, moon: 0.85,
  earth: 0.84, sky: 0.84, star: 0.78, tree: 0.83, stone: 0.83,
  house: 0.88, road: 0.78, bread: 0.85,
  big: 0.9, small: 0.9, good: 0.92, bad: 0.85, new: 0.83, old: 0.83,
  // Mid-low
  thunder: 0.55, lightning: 0.5, hill: 0.5, shoulder: 0.5, claw: 0.42,
};

const MORPHOLOGY: Morphology = {
  paradigms: {
    "noun.case.nom": { affix: ["a", "z"], position: "suffix", category: "noun.case.nom" },
    "noun.case.acc": { affix: ["a", "n"], position: "suffix", category: "noun.case.acc" },
    "noun.case.gen": { affix: ["e", "s"], position: "suffix", category: "noun.case.gen" },
    "noun.case.dat": { affix: ["i"], position: "suffix", category: "noun.case.dat" },
    "noun.num.pl": { affix: ["oː", "z"], position: "suffix", category: "noun.num.pl" },
    "verb.tense.past": { affix: ["d", "a"], position: "suffix", category: "verb.tense.past" },
    "verb.person.1sg": { affix: ["oː"], position: "suffix", category: "verb.person.1sg" },
    "verb.person.2sg": { affix: ["i", "z"], position: "suffix", category: "verb.person.2sg" },
    "verb.person.3sg": { affix: ["θ", "i"], position: "suffix", category: "verb.person.3sg" },
  },
};

/**
 * Phase 20e-2: Common-Germanic suppletion / strong verbs.
 *
 * Pre-Old-English ablaut classes I-VII and umlaut plurals. The phonemic
 * forms here use Proto-Germanic-style reconstructed shapes (Ringe et al.).
 * Some are simplified for the simulator's inventory.
 */
const SUPPLETION: NonNullable<import("../types").Language["suppletion"]> = {
  // Class III: drink/drank/drunk — *drinkaną
  drink: { "verb.tense.past": ["d", "ɾ", "a", "n", "k"] },
  swim: { "verb.tense.past": ["s", "w", "a", "m"] },
  // Class IV: bear/bore — *beraną
  bear: { "verb.tense.past": ["b", "e", "ɾ", "a"] },
  // Class V: see/saw — *sehwaną
  see: { "verb.tense.past": ["s", "a", "xʷ"] },
  eat: { "verb.tense.past": ["e", "t"] },
  // Class VII: come/came — *kweman/*kwamaną
  come: { "verb.tense.past": ["kʷ", "a", "m"] },
  run: { "verb.tense.past": ["ɾ", "a", "n", "n"] },
  // Athematic / suppletive: be (was), go (went-equivalent eode)
  be: { "verb.tense.past": ["w", "a", "s"] },
  go: { "verb.tense.past": ["i", "d", "ð"] },
  // Umlaut plurals (i-mutation): foot/feet, mouse/mice, man/men, woman/women, tooth/teeth
  foot: { "noun.num.pl": ["f", "oː", "t", "s"] },
  man: { "noun.num.pl": ["m", "a", "n", "n", "i", "z"] },
  woman: { "noun.num.pl": ["kʷ", "e", "n", "oː", "s"] },
};

export function presetGermanic(): SimulationConfig {
  const base = defaultConfig();
  return {
    ...base,
    seed: "germanic",
    seedLexicon: LEXICON,
    seedFrequencyHints: FREQ,
    seedMorphology: MORPHOLOGY,
    seedSuppletion: SUPPLETION,
    seedCulturalTier: 1,
    seedStressPattern: "initial",
    // Phase 27a: Germanic licenses moderate clusters (OE strang "strong",
    // CCCVCC); mild strictness allows historical-quality sound changes.
    seedPhonotacticProfile: {
      maxOnset: 3,
      maxCoda: 3,
      maxCluster: 4,
      strictness: 0.4,
    },
    seedGrammar: {
      wordOrder: "SVO",
      articlePresence: "free",
      caseStrategy: "preposition",
      adjectivePosition: "pre",
      possessorPosition: "pre",
    },
    // Phase 31 Tranche 31d: Germanic non-tonal (Norwegian + Swedish
    // are pitch-accent but the proto here is plain non-tonal Common
    // Germanic).
    seedToneRegime: "non-tonal",
    seedBoundMorphemes: GERMANIC_BOUND_MORPHEMES,
    seedPhonemeTarget: 28,
    // Phase 46a-migration: Common Germanic — SVO, nom-acc alignment,
    // articles on a free surface (eventually fuse), full inflectional
    // morphology. Module set tracks the canonical typology so the
    // realiser uses module hooks where they're migrated.
    seedActiveModules: [
      "semantic:lexicon",
      "semantic:clusters",
      "semantic:frequency",
      "semantic:synonymy",
      "semantic:colexification",
      "semantic:borrowing",
      "semantic:calque",
      "semantic:reborrow",
      "semantic:taboo",
      "semantic:coinage",
      "syntactical:wordOrder/svo",
      "syntactical:alignment/nom-acc",
      "syntactical:adj-placement",
      "syntactical:poss-placement",
      "syntactical:num-placement",
      "syntactical:neg-placement",
      "syntactical:relativiser",
      "syntactical:coordination",
      "grammatical:articles",
      "grammatical:number-system",
      "grammatical:aspect",
      "grammatical:reference-tracking",
      "grammatical:numerals",
      "grammatical:demonstratives",
      "morphological:paradigms",
      "morphological:derivation",
      "morphological:inflection-class",
      "morphological:agreement",
      "morphological:analogy",
    ],
    preset: "germanic",
  };
}
