import type { SimulationConfig, Lexicon, Meaning } from "../types";
import type { Morphology } from "../morphology/types";
import { defaultConfig } from "../config";

/**
 * Hand-authored Proto-Indo-European seed lexicon. Forms are simplified
 * reconstructions drawn from the standard literature (Pokorny / LIV /
 * Mallory–Adams), transcribed in IPA rather than the traditional
 * Indo-Europeanist notation. Mappings used:
 *
 *   - Palatovelars  ḱ ǵ ǵʰ        → kʲ gʲ gʲʰ      (palatalised velars)
 *   - Labiovelars   kʷ gʷ gʷʰ     → kʷ gʷ gʷʰ      (unchanged — already IPA)
 *   - Aspirates     bʰ dʰ gʰ      → bʰ dʰ gʰ       (unchanged — already IPA)
 *   - Laryngeals    h₁ h₂ h₃      → h₁ h₂ h₃       (kept as convention —
 *     there is no standard IPA letter for the reconstructed laryngeals,
 *     so we leave them opaque; `PHONE_FEATURES` has dedicated entries).
 *   - Syllabic resonants m̥ n̥ l̥ r̥ → m̩ n̩ l̩ r̩      (IPA U+0329, not U+0325)
 *   - Long vowels    ā ē ī ō ū    → aː eː iː oː uː (IPA length mark)
 *   - Acute stress  á é í ó ú     → dropped; the engine doesn't yet
 *     track per-segment stress as a feature, so retaining the accent
 *     just clutters the lexicon. Will return if a stress pass lands.
 *   - Diphthongs `ew`, `ow`, etc. → split into two phonemes.
 */
const LEXICON: Lexicon = {
  // — natural world / weather —
  water: ["w", "o", "d", "r̩"],
  fire: ["p", "e", "h₂", "w", "r̩"],
  stone: ["a", "kʲ", "m", "o", "n"],
  earth: ["dʰ", "e", "gʲʰ", "o", "m"],
  sky: ["d", "y", "e", "w"],
  sun: ["s", "a", "h₂", "w", "e", "l"],
  moon: ["m", "e", "h₁", "n", "s"],
  star: ["h₂", "s", "t", "e", "r"],
  cloud: ["n", "e", "bʰ", "o", "s"],
  rain: ["h₂", "w", "e", "r"],
  snow: ["s", "n", "e", "y", "gʷʰ"],
  wind: ["h₂", "w", "e", "h₁", "n", "t"],
  thunder: ["s", "t", "e", "n", "h₂"],
  lightning: ["bʰ", "l", "e", "i", "g"],
  ice: ["y", "e", "g"],
  river: ["h₂", "e", "p"],
  sea: ["m", "o", "r", "i"],
  lake: ["l", "i", "m", "n"],
  mountain: ["gʷ", "r̩", "h₃", "i"],
  hill: ["k", "o", "l", "n"],
  valley: ["d", "o", "l"],
  forest: ["w", "i", "dʰ", "u"],
  field: ["h₂", "e", "gʲ", "r", "o"],
  road: ["p", "o", "n", "t", "i"],
  path: ["s", "t", "i", "gʰ"],
  // — sky cycle / time —
  day: ["d", "y", "e", "w"],
  night: ["n", "o", "kʷ", "t", "s"],
  morning: ["h₂", "e", "w", "s", "o", "s"],
  evening: ["w", "e", "s", "p", "e", "r", "o"],
  year: ["y", "e", "h₁", "r"],
  season: ["s", "e", "m", "h₂"],
  winter: ["gʲʰ", "e", "i", "m"],
  summer: ["s", "a", "m", "h₂"],
  // PIE *déh₂-mn̩ "time, turn" (cf. Greek δῆμος, Lat. tempus is actually
  // from *tempos, so avoid it as the PIE source and use *deh₂-).
  time: ["d", "e", "h₂", "m", "n̩"],
  // — flora / fauna —
  tree: ["d", "o", "r", "u"],
  wood: ["d", "o", "r", "u"],
  leaf: ["bʰ", "o", "l", "y", "o"],
  flower: ["bʰ", "l", "o", "h₃", "s"],
  grass: ["gʰ", "r̩", "h₃", "s"],
  root: ["w", "r", "aː", "d"],
  seed: ["s", "eː", "m", "n"],
  fruit: ["bʰ", "r", "o", "g"],
  grain: ["gʰ", "r", "eː", "h₁", "n"],
  bark: ["k", "o", "r", "k"],
  oak: ["a", "y", "g"],
  birch: ["bʰ", "e", "r", "h₂", "gʲ", "o"],
  apple: ["a", "b", "l", "u"],
  // — animals —
  dog: ["kʲ", "w", "o", "n"],
  wolf: ["w", "l̩", "kʷ", "o"],
  horse: ["h₁", "e", "kʲ", "w", "o", "s"],
  cow: ["gʷ", "o", "w", "s"],
  bull: ["t", "a", "w", "r", "o"],
  sheep: ["h₃", "o", "w", "i"],
  goat: ["k", "a", "p", "r", "o"],
  pig: ["s", "u", "h₁", "s"],
  bear: ["h₂", "r̩", "t", "kʲ", "o"],
  deer: ["h₁", "e", "l", "n̩"],
  fish: ["p", "i", "s", "kʲ"],
  bird: ["h₂", "e", "w", "i"],
  eagle: ["h₃", "o", "r", "n̩"],
  // PIE *h₁ógʷʰis "snake".
  snake: ["h₁", "o", "gʷʰ", "i", "s"],
  worm: ["w", "r̩", "m", "i"],
  louse: ["l", "u", "s"],
  bee: ["bʰ", "e", "i"],
  egg: ["h₂", "oː", "w", "y", "o"],
  feather: ["p", "e", "t", "r", "o"],
  wing: ["p", "o", "t", "n", "h₂"],
  horn: ["kʲ", "e", "r", "n"],
  tail: ["p", "u", "kʲ", "n"],
  // — body —
  // PIE *kʷr̩p- "body" (source of Lat. corpus, Skt. kr̩p-). The Latin
  // nominative "korpus" was a bad seed — use the bare root.
  body: ["kʷ", "r̩", "p"],
  head: ["kʲ", "e", "r", "h₂"],
  hair: ["p", "u", "l", "h₂"],
  face: ["p", "r", "o", "kʷ", "p"],
  eye: ["h₃", "o", "kʷ"],
  ear: ["h₂", "o", "w", "s"],
  // PIE *neh₂s- "nose".
  nose: ["n", "e", "h₂", "s"],
  mouth: ["h₁", "o", "s"],
  tooth: ["h₁", "d", "o", "n", "t"],
  tongue: ["d", "n̩", "gʲʰ", "w", "e", "h₂"],
  lip: ["l", "e", "b"],
  neck: ["gʷ", "e", "r", "i", "h₂"],
  shoulder: ["h₂", "o", "m", "s", "o"],
  arm: ["bʰ", "aː", "gʰ", "u"],
  hand: ["gʲʰ", "e", "s", "r"],
  finger: ["d", "i", "g", "i", "t"],
  nail: ["h₃", "n", "o", "gʰ"],
  // PIE *bʰerǵʰ- "high, chest" — the Lat. pectus form was wrong.
  chest: ["bʰ", "e", "r", "gʲʰ"],
  back: ["t", "e", "r", "g", "o"],
  belly: ["gʲʰ", "o", "l", "k", "o"],
  heart: ["kʲ", "e", "r", "d"],
  liver: ["y", "e", "kʷ", "r̩"],
  lung: ["p", "l", "e", "w", "m", "n"],
  bone: ["h₃", "o", "s", "t"],
  blood: ["k", "r", "e", "w", "h₂"],
  skin: ["k", "o", "r", "y", "o"],
  flesh: ["m", "eː", "m", "s", "o"],
  knee: ["gʲ", "o", "n", "u"],
  leg: ["k", "r", "u", "s"],
  foot: ["p", "o", "d", "s"],
  // — kinship / people —
  person: ["dʰ", "gʲʰ", "m", "oː"],
  man: ["w", "i", "h₁", "r", "o"],
  woman: ["gʷ", "e", "n", "h₂"],
  // PIE *putlós "young one, child".
  child: ["p", "u", "t", "l", "o", "s"],
  baby: ["s", "u", "n", "u"],
  mother: ["m", "a", "h₂", "t", "eː", "r"],
  father: ["p", "h₂", "t", "eː", "r"],
  son: ["s", "u", "n", "u"],
  daughter: ["dʰ", "u", "g", "h₂", "t", "eː", "r"],
  brother: ["bʰ", "r", "a", "h₂", "t", "eː", "r"],
  sister: ["s", "w", "e", "s", "oː", "r"],
  husband: ["p", "o", "t", "i", "s"],
  wife: ["d", "e", "m", "s", "p", "o", "t", "n", "i"],
  king: ["h₃", "r", "eː", "gʲ", "s"],
  god: ["d", "y", "e", "w", "s"],
  guest: ["gʰ", "o", "s", "t", "i"],
  enemy: ["h", "o", "s", "t", "i", "s"],
  // — household / artifact —
  house: ["d", "o", "m"],
  door: ["dʰ", "w", "o", "r"],
  fire2: ["h₁", "n̩", "gʷ", "n", "i"],
  hearth: ["h₂", "e", "h₁", "s"],
  yoke: ["y", "u", "g", "o", "m"],
  wheel: ["kʷ", "e", "kʷ", "l", "o"],
  axle: ["a", "kʲ", "s", "i"],
  boat: ["n", "e", "h₂", "u"],
  // PIE *(s)ker- "cut" → knife.
  knife: ["s", "k", "e", "r"],
  axe: ["s", "e", "k", "u", "r", "i"],
  spear: ["gʰ", "a", "i", "s", "o"],
  // PIE *h₂erkʷ-o- "bow" (source of Lat. arcus).
  bow: ["h₂", "e", "r", "kʷ", "o"],
  arrow: ["i", "s", "u"],
  rope: ["w", "e", "y", "o"],
  cloth: ["w", "e", "s"],
  wool: ["w", "l̩", "h₂", "n", "h₂"],
  // — food / drink —
  // PIE *bʰrew- "to ferment, bake" — the root behind English "bread".
  bread: ["bʰ", "r", "e", "w"],
  meat: ["m", "eː", "m", "s", "o"],
  milk: ["gʷ", "l", "a", "k", "t"],
  honey: ["m", "e", "l", "i", "t"],
  salt: ["s", "a", "h₂", "l"],
  // — verbs of motion / state —
  be: ["h₁", "e", "s"],
  go: ["gʷ", "e", "m"],
  come: ["gʷ", "e", "m"],
  walk: ["s", "t", "e", "i", "gʰ"],
  run: ["d", "r", "e", "m"],
  stand: ["s", "t", "e", "h₂"],
  sit: ["s", "e", "d"],
  lie: ["l", "e", "gʰ"],
  fall: ["p", "e", "d"],
  fly: ["p", "e", "t", "h₂"],
  swim: ["s", "n", "e", "h₂"],
  // — verbs of perception / cognition —
  see: ["w", "e", "i", "d"],
  hear: ["kʲ", "l", "e", "w"],
  know: ["gʲ", "n", "eː", "h₃"],
  think: ["m", "e", "n"],
  speak: ["w", "e", "kʷ"],
  say: ["s", "e", "kʷ"],
  call: ["k", "e", "l", "h₁"],
  ask: ["p", "r", "e", "kʲ"],
  // — verbs of action —
  do: ["dʰ", "e", "h₁"],
  make: ["w", "e", "r", "gʲ"],
  take: ["g", "h", "e", "n", "d"],
  give: ["d", "e", "h₃"],
  hold: ["gʰ", "e", "r"],
  carry: ["bʰ", "e", "r"],
  throw: ["y", "e", "h₁"],
  pull: ["t", "r", "e", "g"],
  push: ["t", "r", "u", "d"],
  cut: ["s", "e", "k"],
  break: ["bʰ", "r", "e", "g"],
  bend: ["bʰ", "e", "u", "g"],
  build: ["d", "e", "m", "h₂"],
  burn: ["dʰ", "e", "gʷʰ"],
  wash: ["l", "o", "w", "h₃"],
  weave: ["w", "e", "bʰ"],
  plant: ["s", "e", "h₁"],
  sow: ["s", "e", "h₁"],
  // — verbs of life —
  eat: ["h₁", "e", "d"],
  drink: ["p", "i", "h₃"],
  sleep: ["s", "w", "e", "p"],
  dream: ["s", "w", "o", "p", "n", "o"],
  live: ["gʷ", "y", "e", "h₃"],
  die: ["m", "e", "r"],
  bear_child: ["gʲ", "e", "n", "h₁"],
  grow: ["bʰ", "u", "h₂"],
  love: ["k", "e", "h₂"],
  fear: ["bʰ", "e", "y", "h₁"],
  laugh: ["k", "h", "a", "k"],
  cry: ["w", "e", "i"],
  // — numbers —
  one: ["o", "y", "n", "o", "s"],
  two: ["d", "w", "o", "h₁"],
  three: ["t", "r", "e", "y", "e", "s"],
  four: ["kʷ", "e", "t", "w", "o", "r", "e", "s"],
  five: ["p", "e", "n", "k", "ʷ", "e"],
  six: ["s", "w", "e", "kʲ", "s"],
  seven: ["s", "e", "p", "t", "m̩"],
  eight: ["h₃", "o", "kʲ", "t", "oː"],
  nine: ["h₁", "n", "e", "w", "n̩"],
  ten: ["d", "e", "kʲ", "m̩"],
  hundred: ["kʲ", "m̩", "t", "o", "m"],
  // — qualities —
  big: ["m", "e", "gʲ", "h₂"],
  small: ["p", "a", "u"],
  long: ["d", "l̩", "h₁", "gʰ"],
  short: ["m", "r̩", "gʲʰ", "u"],
  tall: ["h₂", "l̩", "t", "o"],
  wide: ["p", "l̩", "t", "h₂", "u"],
  thick: ["t", "e", "g"],
  thin: ["t", "e", "n", "u"],
  heavy: ["gʷ", "r", "e", "h₂"],
  light: ["l", "e", "n", "gʷʰ"],
  hot: ["k", "o", "l", "h₁"],
  cold: ["gʰ", "e", "l"],
  wet: ["w", "o", "d", "n"],
  dry: ["s", "u", "k", "s", "o"],
  full: ["p", "l̩", "h₁", "n"],
  empty: ["w", "a", "n", "o"],
  new: ["n", "e", "w", "o", "s"],
  old: ["s", "e", "n"],
  young: ["y", "u", "h₃", "w", "n"],
  good: ["d", "w", "e", "n"],
  bad: ["d", "u", "s"],
  sweet: ["s", "w", "aː", "d"],
  bitter: ["a", "k", "r", "o"],
  strong: ["s", "t", "e", "h₂"],
  weak: ["w", "e", "y", "k"],
  fast: ["k", "l", "e", "u"],
  slow: ["s", "l", "e", "h₃"],
  // — colour —
  red: ["h₁", "r", "e", "w", "dʰ"],
  black: ["k", "r̩", "s", "n", "o"],
  white: ["a", "l", "bʰ", "o"],
  green: ["gʰ", "l̩", "h₃", "r", "o"],
  yellow: ["gʲʰ", "e", "l", "h₃"],
  blue: ["bʰ", "l", "eː", "w"],
  // — abstract / pronouns —
  name: ["h₁", "n", "eː", "h₃", "m", "n̩"],
  word: ["w", "e", "kʷ", "o", "s"],
  truth: ["s", "o", "n", "t"],
  // direction / deixis
  this: ["s", "o"],
  that: ["t", "o", "d"],
  here: ["kʲ", "i"],
  there: ["t", "o"],
  // pronouns
  i: ["h₁", "e", "gʲ", "h₂"],
  you: ["t", "u"],
  we: ["w", "e", "y"],
  they: ["t", "o", "y"],
};

const FREQ: Record<Meaning, number> = {
  water: 0.95, fire: 0.85, mother: 0.95, father: 0.95, child: 0.9,
  eye: 0.9, foot: 0.9, hand: 0.9, heart: 0.85, head: 0.85,
  go: 0.97, come: 0.96, eat: 0.95, drink: 0.94, see: 0.95, hear: 0.92,
  one: 0.98, two: 0.96, three: 0.94, big: 0.9, small: 0.9,
  i: 0.99, you: 0.99, we: 0.97, this: 0.96, that: 0.96,
  be: 0.99, do: 0.97, make: 0.94, give: 0.93, take: 0.93,
  day: 0.93, night: 0.93, sun: 0.9, moon: 0.85,
  good: 0.92, bad: 0.9, new: 0.85, old: 0.85,
};

const MORPHOLOGY: Morphology = {
  paradigms: {
    "noun.case.nom": { affix: ["s"], position: "suffix", category: "noun.case.nom" },
    "noun.case.acc": { affix: ["m"], position: "suffix", category: "noun.case.acc" },
    "noun.case.gen": { affix: ["e", "s"], position: "suffix", category: "noun.case.gen" },
    "noun.case.dat": { affix: ["e", "y"], position: "suffix", category: "noun.case.dat" },
    "noun.case.loc": { affix: ["i"], position: "suffix", category: "noun.case.loc" },
    "noun.case.inst": { affix: ["bʰ", "i"], position: "suffix", category: "noun.case.inst" },
    "noun.num.pl": { affix: ["e", "s"], position: "suffix", category: "noun.num.pl" },
    "noun.num.du": { affix: ["o", "h₁"], position: "suffix", category: "noun.num.du" },
    "verb.tense.past": { affix: ["e"], position: "prefix", category: "verb.tense.past" },
    "verb.aspect.pfv": { affix: ["e"], position: "suffix", category: "verb.aspect.pfv" },
    "verb.aspect.ipfv": { affix: ["y", "o"], position: "suffix", category: "verb.aspect.ipfv" },
    "verb.person.1sg": { affix: ["m", "i"], position: "suffix", category: "verb.person.1sg" },
    "verb.person.2sg": { affix: ["s", "i"], position: "suffix", category: "verb.person.2sg" },
    "verb.person.3sg": { affix: ["t", "i"], position: "suffix", category: "verb.person.3sg" },
  },
};

export function presetPIE(): SimulationConfig {
  const base = defaultConfig();
  return {
    ...base,
    seed: "pie",
    seedLexicon: LEXICON,
    seedFrequencyHints: FREQ,
    seedMorphology: MORPHOLOGY,
    preset: "pie",
  };
}
