import type { SimulationConfig, Lexicon, Meaning } from "../types";
import type { Morphology } from "../morphology/types";
import { defaultConfig } from "../config";

const LEXICON: Lexicon = {
  water: ["w", "o", "d", "r̩"],
  fire: ["p", "e", "w", "r̩"],
  stone: ["a", "kʲ", "m", "o", "n"],
  earth: ["dʰ", "e", "gʲʰ", "o", "m"],
  sky: ["d", "j", "e", "w"],
  sun: ["s", "a", "w", "e", "l"],
  moon: ["m", "e", "n", "s"],
  star: ["s", "t", "e", "ɾ"],
  cloud: ["n", "e", "bʰ", "o", "s"],
  rain: ["w", "e", "ɾ"],
  snow: ["s", "n", "e", "j", "gʷʰ"],
  wind: ["w", "e", "n", "t"],
  thunder: ["s", "t", "e", "n"],
  lightning: ["bʰ", "l", "e", "i", "g"],
  ice: ["j", "e", "g"],
  river: ["e", "p"],
  sea: ["m", "o", "ɾ", "i"],
  lake: ["l", "i", "m", "n"],
  mountain: ["gʷ", "r̩", "i"],
  hill: ["k", "o", "l", "n"],
  valley: ["d", "o", "l"],
  forest: ["w", "i", "dʰ", "u"],
  field: ["e", "gʲ", "ɾ", "o"],
  road: ["p", "o", "n", "t", "i"],
  path: ["s", "t", "i", "gʰ"],
  day: ["d", "j", "e", "w"],
  night: ["n", "o", "kʷ", "t", "s"],
  morning: ["e", "w", "s", "o", "s"],
  evening: ["w", "e", "s", "p", "e", "ɾ", "o"],
  year: ["j", "e", "ɾ"],
  season: ["s", "e", "m"],
  winter: ["gʲʰ", "e", "i", "m"],
  summer: ["s", "a", "m"],
  time: ["d", "e", "m", "n̩"],
  tree: ["d", "o", "ɾ", "u"],
  wood: ["d", "o", "ɾ", "u"],
  leaf: ["bʰ", "o", "l", "j", "o"],
  flower: ["bʰ", "l", "o", "s"],
  grass: ["gʰ", "r̩", "s"],
  root: ["w", "ɾ", "aː", "d"],
  seed: ["s", "eː", "m", "n"],
  fruit: ["bʰ", "ɾ", "o", "g"],
  grain: ["gʰ", "ɾ", "eː", "n"],
  bark: ["s", "k", "e", "ɾ"],
  oak: ["a", "j", "g"],
  birch: ["bʰ", "e", "ɾ", "gʲ", "o"],
  apple: ["a", "b", "l", "u"],
  dog: ["kʲ", "w", "o", "n"],
  wolf: ["w", "l̩", "kʷ", "o"],
  horse: ["e", "kʲ", "w", "o", "s"],
  cow: ["gʷ", "o", "w", "s"],
  bull: ["t", "a", "w", "ɾ", "o"],
  sheep: ["o", "w", "i"],
  goat: ["k", "a", "p", "ɾ", "o"],
  pig: ["s", "u", "s"],
  bear: ["r̩", "t", "kʲ", "o"],
  deer: ["e", "l", "n̩"],
  fish: ["p", "i", "s", "kʲ"],
  bird: ["e", "w", "i"],
  eagle: ["o", "ɾ", "n̩"],
  snake: ["o", "gʷʰ", "i", "s"],
  worm: ["w", "r̩", "m", "i"],
  louse: ["l", "u", "s"],
  bee: ["bʰ", "e", "i"],
  egg: ["oː", "w", "j", "o"],
  feather: ["p", "e", "t", "ɾ", "o"],
  horn: ["kʲ", "e", "ɾ", "n"],
  tail: ["p", "u", "kʲ", "n"],
  body: ["kʷ", "r̩", "p"],
  head: ["kʲ", "e", "ɾ"],
  hair: ["p", "u", "l"],
  face: ["o", "kʷ"],
  eye: ["o", "kʷ"],
  ear: ["o", "w", "s"],
  nose: ["n", "e", "s"],
  mouth: ["o", "s"],
  tooth: ["d", "o", "n", "t"],
  tongue: ["d", "n̩", "gʲʰ", "w", "e"],
  neck: ["gʷ", "e", "ɾ", "i"],
  shoulder: ["o", "m", "s", "o"],
  arm: ["bʰ", "aː", "gʰ", "u"],
  hand: ["gʲʰ", "e", "s", "ɾ"],
  nail: ["n", "o", "gʰ"],
  chest: ["bʰ", "e", "ɾ", "gʲʰ"],
  back: ["t", "e", "ɾ", "g", "o"],
  belly: ["gʲʰ", "o", "l", "k", "o"],
  heart: ["kʲ", "e", "ɾ", "d"],
  liver: ["j", "e", "kʷ", "r̩"],
  lung: ["p", "l", "e", "w", "m", "n"],
  bone: ["o", "s", "t"],
  blood: ["k", "ɾ", "e", "w"],
  skin: ["k", "o", "ɾ", "j", "o"],
  flesh: ["m", "eː", "m", "s", "o"],
  knee: ["gʲ", "o", "n", "u"],
  foot: ["p", "o", "d", "s"],
  person: ["dʰ", "gʲʰ", "m", "oː"],
  man: ["w", "i", "ɾ", "o"],
  woman: ["gʷ", "e", "n"],
  child: ["p", "u", "t", "l", "o", "s"],
  baby: ["s", "u", "n", "u"],
  mother: ["m", "e", "t", "eː", "ɾ"],
  father: ["p", "t", "eː", "ɾ"],
  son: ["s", "u", "n", "u"],
  daughter: ["dʰ", "u", "g", "t", "eː", "ɾ"],
  brother: ["bʰ", "ɾ", "e", "t", "eː", "ɾ"],
  sister: ["s", "w", "e", "s", "oː", "ɾ"],
  husband: ["p", "o", "t", "i", "s"],
  wife: ["d", "e", "m", "s", "p", "o", "t", "n", "i"],
  king: ["ɾ", "eː", "gʲ", "s"],
  god: ["d", "j", "e", "w", "s"],
  guest: ["gʰ", "o", "s", "t", "i"],
  house: ["d", "o", "m"],
  door: ["dʰ", "w", "o", "ɾ"],
  fire_ritual: ["n̩", "gʷ", "n", "i"],
  hearth: ["e", "s"],
  yoke: ["j", "u", "g", "o", "m"],
  wheel: ["kʷ", "e", "kʷ", "l", "o"],
  axle: ["a", "kʲ", "s", "i"],
  boat: ["n", "e", "u"],
  knife: ["s", "k", "e", "ɾ"],
  axe: ["s", "e", "k", "u", "ɾ", "i"],
  spear: ["gʰ", "a", "i", "s", "o"],
  bow: ["e", "ɾ", "kʷ", "o"],
  arrow: ["i", "s", "u"],
  rope: ["w", "e", "j", "o"],
  cloth: ["w", "e", "s"],
  wool: ["w", "l̩", "n"],
  bread: ["bʰ", "ɾ", "e", "w"],
  meat: ["m", "eː", "m", "s", "o"],
  milk: ["gʷ", "l", "a", "k", "t"],
  honey: ["m", "e", "l", "i", "t"],
  salt: ["s", "a", "l"],
  be: ["e", "s"],
  go: ["gʷ", "e", "m"],
  come: ["gʷ", "e", "m"],
  walk: ["s", "t", "e", "i", "gʰ"],
  run: ["d", "ɾ", "e", "m"],
  stand: ["s", "t", "e"],
  sit: ["s", "e", "d"],
  lie: ["l", "e", "gʰ"],
  fall: ["p", "e", "d"],
  fly: ["p", "e", "t"],
  swim: ["s", "n", "e"],
  see: ["w", "e", "i", "d"],
  hear: ["kʲ", "l", "e", "w"],
  know: ["gʲ", "n", "eː"],
  think: ["m", "e", "n"],
  speak: ["w", "e", "kʷ"],
  say: ["s", "e", "kʷ"],
  call: ["k", "e", "l"],
  ask: ["p", "ɾ", "e", "kʲ"],
  do: ["dʰ", "e"],
  make: ["w", "e", "ɾ", "gʲ"],
  take: ["gʰ", "e", "n", "d"],
  give: ["d", "e"],
  hold: ["gʰ", "e", "ɾ"],
  carry: ["bʰ", "e", "ɾ"],
  throw: ["j", "e"],
  pull: ["t", "ɾ", "e", "g"],
  push: ["t", "ɾ", "u", "d"],
  cut: ["s", "e", "k"],
  break: ["bʰ", "ɾ", "e", "g"],
  bend: ["bʰ", "e", "u", "g"],
  build: ["d", "e", "m"],
  burn: ["dʰ", "e", "gʷʰ"],
  wash: ["l", "o", "w"],
  weave: ["w", "e", "bʰ"],
  plant: ["s", "e"],
  sow: ["s", "e"],
  eat: ["e", "d"],
  drink: ["p", "i"],
  sleep: ["s", "w", "e", "p"],
  dream: ["s", "w", "o", "p", "n", "o"],
  live: ["gʷ", "j", "e"],
  die: ["m", "e", "ɾ"],
  bear_child: ["gʲ", "e", "n"],
  grow: ["bʰ", "u"],
  love: ["k", "e"],
  fear: ["bʰ", "e", "j"],
  cry: ["w", "e", "i"],
  one: ["o", "j", "n", "o", "s"],
  two: ["d", "w", "o"],
  three: ["t", "ɾ", "e", "j", "e", "s"],
  four: ["kʷ", "e", "t", "w", "o", "ɾ", "e", "s"],
  five: ["p", "e", "n", "kʷ", "e"],
  six: ["s", "w", "e", "kʲ", "s"],
  seven: ["s", "e", "p", "t", "m̩"],
  eight: ["o", "kʲ", "t", "oː"],
  nine: ["n", "e", "w", "n̩"],
  ten: ["d", "e", "kʲ", "m̩"],
  hundred: ["kʲ", "m̩", "t", "o", "m"],
  big: ["m", "e", "gʲ"],
  small: ["p", "e", "u"],
  long: ["d", "l̩", "gʰ"],
  short: ["m", "r̩", "gʲʰ", "u"],
  tall: ["l̩", "t", "o"],
  wide: ["p", "l̩", "t", "u"],
  thick: ["t", "e", "g"],
  thin: ["t", "e", "n", "u"],
  heavy: ["gʷ", "ɾ", "e"],
  light: ["l", "e", "n", "gʷʰ"],
  hot: ["gʷʰ", "e", "ɾ"],
  cold: ["gʰ", "e", "l"],
  wet: ["w", "o", "d", "n"],
  dry: ["s", "u", "k", "s", "o"],
  full: ["p", "l̩", "n"],
  empty: ["w", "e", "n", "o"],
  new: ["n", "e", "w", "o", "s"],
  old: ["s", "e", "n"],
  young: ["j", "u", "w", "n"],
  good: ["d", "w", "e", "n"],
  bad: ["d", "u", "s"],
  sweet: ["s", "w", "e", "d"],
  bitter: ["a", "k", "ɾ", "o"],
  strong: ["s", "t", "e"],
  weak: ["w", "e", "j", "k"],
  fast: ["k", "l", "e", "u"],
  slow: ["s", "l", "e"],
  red: ["ɾ", "e", "w", "dʰ"],
  black: ["k", "r̩", "s", "n", "o"],
  white: ["e", "l", "bʰ", "o"],
  green: ["gʲʰ", "ɾ", "o"],
  yellow: ["gʲʰ", "e", "l"],
  blue: ["bʰ", "l", "eː", "w"],
  name: ["n", "o", "m", "n̩"],
  word: ["w", "e", "kʷ", "o", "s"],
  truth: ["s", "o", "n", "t"],
  this: ["s", "o"],
  that: ["t", "o", "d"],
  here: ["kʲ", "i"],
  there: ["t", "o"],
  i: ["e", "gʲ"],
  you: ["t", "u"],
  we: ["w", "e", "j"],
  they: ["t", "o", "j"],
  jaw: ["gʲ", "e", "n", "u"],
  throat: ["gʷ", "e", "ɾ"],
  chin: ["gʲ", "e", "n", "u"],
  thumb: ["p", "o", "l", "e", "kʲ"],
  sinew: ["s", "n", "eː", "w"],
  grandfather: ["e", "w", "o"],
  grandmother: ["a", "n"],
  uncle: ["e", "w", "n̩", "t", "ɾ"],
  nephew: ["n", "e", "p", "oː", "t"],
  niece: ["n", "e", "p", "t", "i"],
  widow: ["w", "i", "dʰ", "e", "w", "a"],
  orphan: ["o", "ɾ", "bʰ", "o"],
  youth: ["j", "u", "w", "e", "n"],
  elder: ["gʲ", "e", "ɾ"],
  otter: ["u", "d", "ɾ", "o"],
  beaver: ["bʰ", "e", "bʰ", "ɾ"],
  mouse: ["m", "uː", "s"],
  fox: ["w", "l̩", "p", "e", "kʲ"],
  duck: ["a", "n", "e", "t"],
  goose: ["gʲʰ", "a", "n", "s"],
  lamb: ["w", "r̩", "eː", "n"],
  calf: ["w", "e", "t", "e", "l"],
  foal: ["p", "oː", "l"],
  barley: ["e", "d", "o", "s"],
  wheat: ["p", "uː", "ɾ"],
  vine: ["w", "e", "j", "t"],
  nut: ["k", "n", "u"],
  mead: ["m", "e", "dʰ", "u"],
  beer: ["a", "l", "u"],
  flour: ["m", "o", "l"],
  dough: ["t", "a", "j", "s"],
  wine: ["w", "o", "j", "n", "o"],
  plow: ["e", "ɾ"],
  mill: ["m", "e", "l"],
  hoe: ["p", "e", "kʲ"],
  sickle: ["s", "k", "o", "ɾ"],
  loom: ["w", "e", "bʰ", "n̩"],
  spindle: ["s", "n", "eː"],
  thread: ["p", "e", "n", "s"],
  basket: ["k", "o", "ɾ"],
  wagon: ["w", "e", "gʲʰ", "n", "o"],
  reins: ["ɾ", "e", "j"],
  hammer: ["a", "kʲ", "m", "oː"],
  gold: ["gʲʰ", "l̩", "t", "o"],
  silver: ["r̩", "gʲ", "n̩", "t"],
  metal: ["a", "j", "e", "s"],
  frost: ["p", "ɾ", "u", "s"],
  hail: ["gʰ", "ɾ", "o"],
  dew: ["e", "w", "s", "r̩"],
  fog: ["m", "e", "j", "gʰ"],
  breeze: ["e", "n", "m"],
  east: ["e", "w", "s"],
  west: ["w", "e", "s", "p", "e", "ɾ"],
  up: ["u", "p", "e", "ɾ"],
  down: ["n̩", "dʰ", "o"],
  outside: ["e", "gʲʰ"],
  inside: ["e", "n"],
  soft: ["m", "e", "l", "d"],
  hard: ["k", "a", "ɾ"],
  stiff: ["s", "t", "e", "ɾ"],
  rough: ["k", "l̩"],
  naked: ["n", "o", "gʷ"],
  clean: ["kʲ", "l", "e", "w"],
  dirty: ["p", "uː"],
  holy: ["s", "a", "kʲ"],
  sacred: ["kʲ", "w", "e", "n", "t"],
  sell: ["p", "e", "ɾ"],
  buy: ["kʷ", "ɾ", "e", "j"],
  tell: ["s", "e", "kʷ"],
  promise: ["s", "p", "o", "n", "d"],
  count: ["ɾ", "e"],
  measure: ["m", "e"],
  show: ["d", "e", "j", "kʲ"],
  find: ["w", "e", "j", "d"],
  lose: ["l", "e", "j"],
  steal: ["kʲ", "l", "e", "p"],
  hide_verb: ["k", "e", "l"],
  share: ["d", "e"],
  divide: ["d", "e", "j"],
  join: ["j", "e", "w", "g"],
  bind: ["d", "e"],
  release: ["l", "e", "w"],
  sing: ["k", "a", "n"],
  wake: ["gʷ", "e", "ɾ"],
  meet: ["m", "e", "j", "t"],
  leave: ["l", "e", "j", "kʷ"],
  stay: ["s", "t", "e", "w"],
  wait: ["s", "p", "e", "kʲ"],
  hope: ["s", "p", "e"],
  tribe: ["t", "e", "w", "t", "a"],
  clan: ["gʲ", "e", "n"],
  sacrifice: ["gʲʰ", "e", "w"],
  offering: ["d", "e", "n"],
  prayer: ["gʷʰ", "e", "dʰ"],
  oath: ["o", "j"],
  feast: ["d", "e", "j", "t"],
  gift: ["d", "o", "n"],
  host: ["d", "o", "m"],
  mind: ["m", "e", "n"],
  soul: ["a", "n"],
  ghost: ["gʰ", "e", "j", "s"],
  shadow: ["s", "kʲ", "o", "t"],
  light_noun: ["l", "e", "w", "k"],
  dark: ["t", "e", "m"],
  life: ["gʷ", "j", "e"],
  death: ["m", "r̩"],
  spring: ["w", "e", "s", "r̩"],
  autumn: ["e", "s", "e", "n"],
  dawn: ["e", "w", "s", "oː", "s"],
  dusk: ["w", "e", "s", "p", "e", "ɾ"],
  hour: ["oː", "ɾ"],
  now: ["n", "uː"],
  yesterday: ["dʰ", "gʰ", "j", "e", "s"],
  all: ["s", "o", "l"],
  many: ["m", "e", "gʲ"],
  some: ["s", "e", "m"],
  none: ["n", "e", "kʷ", "e"],
  half: ["s", "eː", "m", "i"],
  twice: ["d", "w", "i", "s"],
  thrice: ["t", "ɾ", "i", "s"],
  who: ["kʷ", "i", "s"],
  what: ["kʷ", "i", "d"],
  where: ["kʷ", "u"],
  when: ["kʷ", "a", "n"],
  why: ["kʷ", "e"],
  not: ["n", "e"],
  yes: ["j", "a"],
  pain: ["p", "e"],
  joy: ["gʲ", "e", "w"],
  hunger: ["gʷ", "e", "ɾ"],
  thirst: ["t", "r̩", "s"],
  shame: ["s", "kʲ", "e", "m"],
  he: ["s", "o"],
  she: ["s", "e"],
  it: ["t", "o", "d"],
  and: ["kʷ", "e"],
  or: ["w", "eː"],
  in: ["e", "n"],
  on: ["o", "p"],
  to: ["d", "o"],
  for: ["p", "ɾ", "o"],
  by: ["e", "p", "i"],
  // Phase 36 Tranche 36n: PIE derivational morphemes. *-tér agentive
  // (*ph₂tér "father" lit. "protector"), *-mn̥ neuter action noun
  // (*nh₃men- → name), *-eh₂ feminine collective, *-tós passive
  // participle, *-i̯o thematic adjective.
  // Phase 58.6 user fix: laryngeals stripped from PIE forms; the
  // bound-morpheme tags follow suit.
  "-tér.agt": ["t", "e", "ɾ"],
  "-mn̥.action": ["m", "n̩"],
  "-e.fem": ["e"],
  "-tós.ptcp": ["t", "o", "s"],
  "-i̯o.adj": ["j", "o"],
  // Phase 47 T4: PIE typology = SOV + suffix-heavy (Greenberg). Add
  // more suffixes covering instrument, comparative, abstract,
  // diminutive. Daughters inherit + erode these.
  "-tro.inst": ["t", "ɾ", "o"],
  "-ter.cmp": ["t", "e", "ɾ"],
  "-nis.abs": ["n", "i", "s"],
  "-ko.dim": ["k", "o"],
  // Phase 58.6: PIE prefixes tagged with shorthand category. *n̥-
  // privative/negative (the famous a-/an-/un- ancestor), *pri-
  // temporal/before. These let English-input prefixes (un-, pre-,
  // dis-) resolve to PIE's realisations via parseEnglishAffix →
  // selectAffixForCategory; the shorthand tells the affix dispatcher
  // which abstract DerivationCategory each surface form serves.
  "n̥-.neg": ["n̩"],
  "pri-.tbef": ["p", "ɾ", "i"],
};

const PIE_BOUND_MORPHEMES = new Set<string>([
  "-tér.agt", "-mn̥.action", "-e.fem", "-tós.ptcp", "-i̯o.adj",
  "-tro.inst", "-ter.cmp", "-nis.abs", "-ko.dim",
  "n̥-.neg", "pri-.tbef",
]);

// Phase 29 Tranche 5s: deepened PIE frequency hints.
const FREQ: Record<Meaning, number> = {
  i: 0.99, you: 0.99, we: 0.97, they: 0.95, he: 0.96, she: 0.96, it: 0.95,
  this: 0.96, that: 0.96, here: 0.92, there: 0.92,
  not: 0.97, and: 0.98, or: 0.92,
  be: 0.99, have: 0.96, do: 0.97, go: 0.97, come: 0.96,
  see: 0.95, say: 0.93, know: 0.92, give: 0.93, take: 0.93,
  make: 0.94, want: 0.92, eat: 0.95, drink: 0.94, sleep: 0.88,
  walk: 0.85, run: 0.85, hear: 0.92, speak: 0.88, think: 0.88,
  mother: 0.95, father: 0.95, child: 0.9, brother: 0.85, sister: 0.85,
  daughter: 0.85, son: 0.85,
  hand: 0.9, foot: 0.9, eye: 0.9, head: 0.85, mouth: 0.83,
  ear: 0.82, heart: 0.85, blood: 0.85,
  one: 0.98, two: 0.96, three: 0.94, four: 0.86, five: 0.86,
  water: 0.95, fire: 0.85, day: 0.93, night: 0.93, sun: 0.9, moon: 0.85,
  earth: 0.86, sky: 0.84, star: 0.78, tree: 0.82, stone: 0.82,
  big: 0.9, small: 0.9, good: 0.92, bad: 0.9, new: 0.85, old: 0.85,
  thunder: 0.55, lightning: 0.5, hill: 0.5, shoulder: 0.5,
};

const LEXICAL_STRESS: Record<Meaning, number> = {
  mother: 1,
  daughter: 1,
  child: 1,
  seven: 1,
  eight: 1,
  hundred: 1,
  short: 1,
  wide: 1,
  yoke: 1,
  wheel: 1,
  evening: 0,
  four: 0,
  wife: 0,
};

const MORPHOLOGY: Morphology = {
  paradigms: {
    "noun.case.nom": { affix: ["s"], position: "suffix", category: "noun.case.nom" },
    "noun.case.acc": { affix: ["m"], position: "suffix", category: "noun.case.acc" },
    "noun.case.gen": { affix: ["e", "s"], position: "suffix", category: "noun.case.gen" },
    "noun.case.dat": { affix: ["e", "j"], position: "suffix", category: "noun.case.dat" },
    "noun.case.loc": { affix: ["i"], position: "suffix", category: "noun.case.loc" },
    "noun.case.inst": { affix: ["bʰ", "i"], position: "suffix", category: "noun.case.inst" },
    "noun.num.pl": { affix: ["e", "s"], position: "suffix", category: "noun.num.pl" },
    "noun.num.du": { affix: ["o"], position: "suffix", category: "noun.num.du" },
    "verb.tense.past": { affix: ["e"], position: "prefix", category: "verb.tense.past" },
    "verb.aspect.pfv": { affix: ["e"], position: "suffix", category: "verb.aspect.pfv" },
    "verb.aspect.ipfv": { affix: ["j", "o"], position: "suffix", category: "verb.aspect.ipfv" },
    "verb.person.1sg": { affix: ["m", "i"], position: "suffix", category: "verb.person.1sg" },
    "verb.person.2sg": { affix: ["s", "i"], position: "suffix", category: "verb.person.2sg" },
    "verb.person.3sg": { affix: ["t", "i"], position: "suffix", category: "verb.person.3sg" },
  },
};

/**
 * Phase 20e-2: PIE athematic verb / suppletion fragments.
 *
 * Reconstructed past-tense / aorist forms for the small set of verbs
 * known to be irregular in PIE itself (Beekes, Fortson). The simulator
 * doesn't model PIE's full athematic conjugation, but the most common
 * pattern — distinct e-grade present vs. zero/o-grade aorist — is
 * captured here as suppletion entries the engine can apply.
 */
const SUPPLETION: NonNullable<import("../types").Language["suppletion"]> = {
  // *h₁es- (be) athematic; aorist *h₁ē-
  be: { "verb.tense.past": ["ē", "s"] },
  // *h₁ei- (go) athematic; aorist *h₁it-
  go: { "verb.tense.past": ["i", "t"] },
  // *gʷem- (come) — root aorist *gʷm̥-
  come: { "verb.tense.past": ["gʷ", "m̥"] },
  // *weid- (see, also "know" as perfect) — aorist *wēid-
  see: { "verb.tense.past": ["w", "ē", "i", "d"] },
  // *h₁ed- (eat) — aorist *h₁ēd-
  eat: { "verb.tense.past": ["ē", "d"] },
  // Suppletive man/men: *wiHro- vs *h₂ner- (the famous PIE doublet)
  // Stored as a plural alternate.
  man: { "noun.num.pl": ["n", "e", "ɾ", "e", "s"] },
};

export function presetPIE(): SimulationConfig {
  const base = defaultConfig();
  return {
    ...base,
    seed: "pie",
    seedLexicon: LEXICON,
    seedFrequencyHints: FREQ,
    seedMorphology: MORPHOLOGY,
    seedSuppletion: SUPPLETION,
    seedCulturalTier: 0,
    seedStressPattern: "lexical",
    seedLexicalStress: LEXICAL_STRESS,
    // Phase 27a: PIE licenses substantial clusters (*kʷetwores-, *septḿ);
    // medium strictness so reconstructed-quality clusters survive but
    // pathological outputs trigger repair.
    seedPhonotacticProfile: {
      maxOnset: 3,
      maxCoda: 3,
      maxCluster: 4,
      strictness: 0.5,
    },
    seedGrammar: {
      wordOrder: "SOV",
      articlePresence: "none",
      caseStrategy: "case",
      adjectivePosition: "pre",
      possessorPosition: "pre",
      synthesisIndex: 2.5,
      fusionIndex: 0.7,
      hasCase: true,
      // Phase 39n: PIE had a productive dual (Vedic, Greek, Lithuanian
      // retain it). Daughters can lose it as a measurable diachronic
      // event (Latin → Romance lost the dual; English lost it pre-1100).
      numberSystem: "sg-du-pl",
      // PIE evidential / mood / aspect were rich. Phase 39n seeds the
      // dual as the most attested feature; pitch-accent is reserved
      // for Phase 40+ (mobile accent reconstruction is contentious).
    },
    // Phase 31 Tranche 31d: Proto-Indo-European is typologically
    // pitch-accent (Vedic / Greek / Lithuanian retain traces of
    // mobile accent), but the simulator models lexical-stress
    // explicitly via seedLexicalStress and doesn't seed actual tone
    // marks. So PIE is non-tonal here — pitch-accent realisation is
    // Phase 32+.
    seedToneRegime: "non-tonal",
    seedBoundMorphemes: PIE_BOUND_MORPHEMES,
    seedPhonemeTarget: 36,
    // Phase 40d: PIE descendants historically LOST aspirates (Greek
    // bʰ→pʰ, Latin bʰ→f), not gained them. Pre-40d the simulator
    // drifted PIE daughters toward bʰ/dʰ/gʷʰ-heavy outputs because
    // fortition.initial_aspiration fired at catalog default. This
    // prior down-weights it 10× and boosts attested IE patterns
    // (intervocalic voicing, lenition, monophthongisation). Soft
    // prior — daughters can still drift away from it via per-language
    // weight evolution and naturalBiasOverride drift.
    seedRuleBias: {
      "fortition.initial_aspiration": 0.1,
      "voicing.s_intervocalic": 1.5,
      "lenition.tap_intervocalic": 1.2,
      "monophthongization.au_to_o": 1.4,
    },
    // Phase 46a-migration: Proto-Indo-European — SOV, full case system
    // (8 cases), sg-du-pl numbers, no articles. The articles module is
    // off; daughters that grammaticalise articles activate it via
    // Phase 46d's deferred-load when the demonstrative→article
    // pathway fires.
    seedActiveModules: [
      "semantic:lexicon",
      "semantic:clusters",
      "semantic:frequency",
      "semantic:synonymy",
      "semantic:colexification",
      "semantic:borrowing",
      "semantic:calque",
      "semantic:reborrow",
      "semantic:taboo",
      "semantic:coinage",
      "syntactical:wordOrder/sov",
      "syntactical:alignment/nom-acc",
      "syntactical:adj-placement",
      "syntactical:poss-placement",
      "syntactical:num-placement",
      "syntactical:neg-placement",
      "syntactical:relativiser",
      "syntactical:coordination",
      "grammatical:case-marking",
      "grammatical:number-system",
      "grammatical:aspect",
      "grammatical:mood",
      "grammatical:reference-tracking",
      "grammatical:numerals",
      "grammatical:demonstratives",
      "morphological:paradigms",
      "morphological:derivation",
      "morphological:inflection-class",
      "morphological:agreement",
      "morphological:analogy",
    ],
    // Phase 48 T13: PIE uses reconstruction-tradition notation
    // (laryngeals h₁/h₂/h₃, triple-diacritic stops gʲʰ etc.). Flag
    // tells the validator to allow these as valid phonemes for this
    // preset. Other presets remain held to standard IPA-2020.
    reconstructionMode: true,
    preset: "pie",
  };
}
