import type { SimulationConfig, Lexicon, Meaning } from "../types";
import type { Morphology } from "../morphology/types";
import { defaultConfig } from "../config";

// Hand-authored Proto-Indo-European seed lexicon. Forms are simplified
// reconstructions drawn from the standard literature (Pokorny / LIV /
// Mallory–Adams). Laryngeals (h₁ h₂ h₃) and syllabic resonants (m̥ n̥ l̥ r̥)
// are kept as single segments so the engine treats them as discrete
// phonemes the way a real PIE-descendant simulation would.
const LEXICON: Lexicon = {
  // — natural world / weather —
  water: ["w", "ó", "d", "r̥"],
  fire: ["p", "éh₂", "w", "r̥"],
  stone: ["a", "ḱ", "m", "ó", "n"],
  earth: ["d", "ʰ", "é", "ǵ", "ʰ", "o", "m"],
  sky: ["d", "y", "éw"],
  sun: ["s", "á", "h₂", "w", "e", "l"],
  moon: ["m", "éh₁", "n", "s"],
  star: ["h₂", "s", "t", "ér"],
  cloud: ["n", "é", "b", "ʰ", "o", "s"],
  rain: ["h₂", "w", "é", "r"],
  snow: ["s", "n", "é", "y", "g", "ʷ", "ʰ"],
  wind: ["h₂", "w", "éh₁", "n", "t"],
  thunder: ["s", "t", "é", "n", "h₂"],
  lightning: ["b", "ʰ", "l", "é", "i", "g"],
  ice: ["y", "é", "g"],
  river: ["h₂", "é", "p"],
  sea: ["m", "ó", "r", "i"],
  lake: ["l", "í", "m", "n"],
  mountain: ["g", "ʷ", "r̥", "h₃", "i"],
  hill: ["k", "ó", "l", "n"],
  valley: ["d", "ó", "l", "ʰ"],
  forest: ["w", "í", "d", "ʰ", "u"],
  field: ["h₂", "é", "ǵ", "r", "o"],
  road: ["p", "ó", "n", "t", "i"],
  path: ["s", "t", "i", "g", "ʰ"],
  // — sky cycle / time —
  day: ["d", "y", "é", "w"],
  night: ["n", "ó", "k", "ʷ", "t", "s"],
  morning: ["h₂", "ew", "s", "ó", "s"],
  evening: ["w", "é", "s", "p", "e", "r", "o"],
  year: ["y", "é", "h₁", "r"],
  season: ["s", "é", "m", "h₂"],
  winter: ["ǵ", "ʰ", "é", "i", "m"],
  summer: ["s", "á", "m", "h₂"],
  time: ["t", "é", "m", "p", "o", "s"],
  // — flora / fauna —
  tree: ["d", "ó", "r", "u"],
  wood: ["d", "ó", "r", "u"],
  leaf: ["b", "ʰ", "ó", "l", "y", "o"],
  flower: ["b", "ʰ", "l", "ó", "h₃", "s"],
  grass: ["g", "ʰ", "r̥", "h₃", "s"],
  root: ["w", "r", "ā", "d"],
  seed: ["s", "ē", "m", "n"],
  fruit: ["b", "ʰ", "r", "ó", "g"],
  grain: ["g", "ʰ", "r", "ē", "h₁", "n"],
  bark: ["k", "ó", "r", "k"],
  oak: ["a", "y", "g"],
  birch: ["b", "ʰ", "é", "r", "h₂", "ǵ", "o"],
  apple: ["a", "b", "l", "u"],
  // — animals —
  dog: ["ḱ", "w", "ó", "n"],
  wolf: ["w", "l̥", "k", "ʷ", "o"],
  horse: ["h₁", "é", "ḱ", "w", "o", "s"],
  cow: ["g", "ʷ", "ó", "w", "s"],
  bull: ["t", "á", "w", "r", "o"],
  sheep: ["h₃", "ów", "i"],
  goat: ["k", "á", "p", "r", "o"],
  pig: ["s", "ú", "h₁", "s"],
  bear: ["h₂", "r̥", "t", "ḱ", "o"],
  deer: ["h₁", "é", "l", "n̥"],
  fish: ["p", "í", "s", "ḱ"],
  bird: ["h₂", "ew", "i"],
  eagle: ["h₃", "ó", "r", "n̥"],
  snake: ["s", "é", "r", "p"],
  worm: ["w", "r̥", "m", "i"],
  louse: ["l", "ú", "s"],
  bee: ["b", "ʰ", "é", "i"],
  egg: ["h₂", "ō", "w", "y", "ó"],
  feather: ["p", "é", "t", "r", "o"],
  wing: ["p", "ó", "t", "n", "h₂"],
  horn: ["ḱ", "ér", "n"],
  tail: ["p", "ú", "ḱ", "n"],
  // — body —
  body: ["k", "ó", "r", "p", "u", "s"],
  head: ["ḱ", "é", "r", "h₂"],
  hair: ["p", "ú", "l", "h₂"],
  face: ["p", "r", "ó", "k", "ʷ", "p"],
  eye: ["h₃", "ó", "k", "ʷ"],
  ear: ["h₂", "ow", "s"],
  nose: ["n", "á", "s"],
  mouth: ["h₁", "ó", "ss"],
  tooth: ["h₁", "d", "ó", "n", "t"],
  tongue: ["d", "n̥", "ǵ", "ʰ", "wéh₂"],
  lip: ["l", "é", "b"],
  neck: ["g", "ʷ", "ér", "i", "h₂"],
  shoulder: ["h₂", "ó", "m", "s", "o"],
  arm: ["b", "ʰ", "ā", "g", "ʰ", "u"],
  hand: ["ǵ", "ʰ", "é", "s", "r"],
  finger: ["d", "i", "g", "i", "t"],
  nail: ["h₃", "n", "ó", "g", "ʰ"],
  chest: ["p", "é", "k", "t", "u", "s"],
  back: ["t", "é", "r", "g", "o"],
  belly: ["ǵ", "ʰ", "ó", "l", "k", "o"],
  heart: ["ḱ", "é", "r", "d"],
  liver: ["y", "é", "k", "ʷ", "r̥"],
  lung: ["p", "l", "éw", "m", "n"],
  bone: ["h₃", "ó", "s", "t"],
  blood: ["k", "r", "éw", "h₂"],
  skin: ["k", "ó", "r", "y", "o"],
  flesh: ["m", "ē", "m", "s", "ó"],
  knee: ["ǵ", "ó", "n", "u"],
  leg: ["k", "r", "ú", "s"],
  foot: ["p", "ó", "d", "s"],
  // — kinship / people —
  person: ["d", "ʰ", "ǵ", "ʰ", "m", "ō"],
  man: ["w", "í", "h₁", "r", "o"],
  woman: ["g", "ʷ", "é", "n", "h₂"],
  child: ["p", "ó", "t", "l", "o"],
  baby: ["s", "ú", "n", "u"],
  mother: ["m", "á", "h₂", "t", "ē", "r"],
  father: ["p", "h₂", "t", "ē", "r"],
  son: ["s", "ú", "n", "u"],
  daughter: ["d", "ʰ", "u", "g", "h₂", "t", "ē", "r"],
  brother: ["b", "ʰ", "r", "á", "h₂", "t", "ē", "r"],
  sister: ["s", "w", "é", "s", "ō", "r"],
  husband: ["p", "ó", "t", "i", "s"],
  wife: ["d", "é", "m", "s", "p", "o", "t", "n", "i"],
  king: ["h₃", "r", "ḗ", "ǵ", "s"],
  god: ["d", "y", "éw", "s"],
  guest: ["g", "ʰ", "ó", "s", "t", "i"],
  enemy: ["h", "ó", "s", "t", "i", "s"],
  // — household / artifact —
  house: ["d", "ó", "m"],
  door: ["d", "ʰ", "w", "ó", "r"],
  fire2: ["h₁", "n̥", "g", "ʷ", "n", "i"],
  hearth: ["h₂", "é", "h₁", "s"],
  yoke: ["y", "ú", "g", "o", "m"],
  wheel: ["k", "ʷ", "é", "k", "ʷ", "l", "o"],
  axle: ["a", "ḱ", "s", "i"],
  boat: ["n", "éh₂", "u"],
  knife: ["k", "u", "l", "t", "r", "o"],
  axe: ["s", "é", "k", "u", "r", "i"],
  spear: ["g", "ʰ", "a", "i", "s", "o"],
  bow: ["a", "r", "k", "u"],
  arrow: ["i", "s", "u"],
  rope: ["w", "é", "y", "o"],
  cloth: ["w", "é", "s"],
  wool: ["w", "l̥", "h₂", "n", "h₂"],
  // — food / drink —
  bread: ["a", "r", "t", "o"],
  meat: ["m", "ē", "m", "s", "o"],
  milk: ["g", "ʷ", "l", "a", "k", "t"],
  honey: ["m", "é", "l", "i", "t"],
  salt: ["s", "á", "h₂", "l"],
  // — verbs of motion / state —
  be: ["h₁", "é", "s"],
  go: ["g", "ʷ", "é", "m"],
  come: ["g", "ʷ", "é", "m"],
  walk: ["s", "t", "é", "i", "g", "ʰ"],
  run: ["d", "r", "é", "m"],
  stand: ["s", "t", "éh₂"],
  sit: ["s", "é", "d"],
  lie: ["l", "é", "g", "ʰ"],
  fall: ["p", "é", "d"],
  fly: ["p", "é", "t", "h₂"],
  swim: ["s", "n", "éh₂"],
  // — verbs of perception / cognition —
  see: ["w", "é", "i", "d"],
  hear: ["ḱ", "l", "é", "w"],
  know: ["ǵ", "n", "ḗ", "h₃"],
  think: ["m", "é", "n"],
  speak: ["w", "é", "k", "ʷ"],
  say: ["s", "é", "k", "ʷ"],
  call: ["k", "é", "l", "h₁"],
  ask: ["p", "r", "é", "ḱ"],
  // — verbs of action —
  do: ["d", "ʰ", "é", "h₁"],
  make: ["w", "é", "rǵ"],
  take: ["g", "h", "e", "n", "d"],
  give: ["d", "é", "h₃"],
  hold: ["g", "ʰ", "é", "r"],
  carry: ["b", "ʰ", "é", "r"],
  throw: ["y", "é", "h₁"],
  pull: ["t", "r", "é", "g"],
  push: ["t", "r", "ú", "d"],
  cut: ["s", "é", "k"],
  break: ["b", "ʰ", "r", "é", "g"],
  bend: ["b", "ʰ", "é", "u", "g"],
  build: ["d", "é", "m", "h₂"],
  burn: ["d", "ʰ", "é", "g", "ʷ", "ʰ"],
  wash: ["l", "ow", "h₃"],
  weave: ["w", "é", "b", "ʰ"],
  plant: ["s", "é", "h₁"],
  sow: ["s", "é", "h₁"],
  // — verbs of life —
  eat: ["h₁", "é", "d"],
  drink: ["p", "í", "h₃"],
  sleep: ["s", "w", "é", "p"],
  dream: ["s", "w", "ó", "p", "n", "o"],
  live: ["g", "ʷ", "y", "é", "h₃"],
  die: ["m", "é", "r"],
  bear_child: ["ǵ", "é", "n", "h₁"],
  grow: ["b", "ʰ", "ú", "h₂"],
  love: ["k", "é", "h₂"],
  fear: ["b", "ʰ", "é", "y", "h₁"],
  laugh: ["k", "h", "a", "k"],
  cry: ["w", "é", "i"],
  // — numbers —
  one: ["ó", "y", "n", "o", "s"],
  two: ["d", "w", "ó", "h₁"],
  three: ["t", "r", "é", "y", "e", "s"],
  four: ["k", "ʷ", "é", "t", "w", "o", "r", "e", "s"],
  five: ["p", "é", "n", "k", "ʷ", "e"],
  six: ["s", "w", "é", "ḱ", "s"],
  seven: ["s", "e", "p", "t", "ḿ̥"],
  eight: ["h₃", "ó", "ḱ", "t", "ō"],
  nine: ["h₁", "n", "é", "w", "n̥"],
  ten: ["d", "é", "ḱ", "m̥"],
  hundred: ["ḱ", "m̥", "t", "ó", "m"],
  // — qualities —
  big: ["m", "é", "ǵ", "h₂"],
  small: ["p", "á", "u"],
  long: ["d", "l̥", "h₁", "g", "ʰ"],
  short: ["m", "r̥", "ǵ", "ʰ", "u"],
  tall: ["h₂", "l̥", "t", "o"],
  wide: ["p", "l̥", "t", "h₂", "ú"],
  thick: ["t", "é", "g"],
  thin: ["t", "é", "n", "u"],
  heavy: ["g", "ʷ", "r", "é", "h₂"],
  light: ["l", "é", "n", "g", "ʷ", "ʰ"],
  hot: ["k", "ó", "l", "h₁"],
  cold: ["g", "ʰ", "é", "l"],
  wet: ["w", "ó", "d", "n"],
  dry: ["s", "u", "k", "s", "o"],
  full: ["p", "l̥", "h₁", "n"],
  empty: ["w", "á", "n", "o"],
  new: ["n", "éw", "o", "s"],
  old: ["s", "é", "n"],
  young: ["y", "ú", "h₃", "w", "n"],
  good: ["d", "u̯", "é", "n"],
  bad: ["d", "ú", "s"],
  sweet: ["s", "w", "ā", "d"],
  bitter: ["a", "k", "r", "o"],
  strong: ["s", "t", "é", "h₂"],
  weak: ["w", "é", "y", "k"],
  fast: ["k", "l", "é", "u"],
  slow: ["s", "l", "é", "h₃"],
  // — colour —
  red: ["h₁", "r", "ew", "d", "ʰ"],
  black: ["k", "r̥", "s", "n", "ó"],
  white: ["a", "l", "b", "ʰ", "o"],
  green: ["g", "ʰ", "l̥", "h₃", "ro"],
  yellow: ["ǵ", "ʰ", "é", "l", "h₃"],
  blue: ["b", "ʰ", "l", "ē", "w"],
  // — abstract / pronouns —
  name: ["h₁", "n", "ḗ", "h₃", "m", "n̥"],
  word: ["w", "é", "k", "ʷ", "o", "s"],
  truth: ["s", "ó", "n", "t"],
  // direction
  this: ["s", "ó"],
  that: ["t", "ó", "d"],
  here: ["k", "ʲ", "í"],
  there: ["t", "ó"],
  // pronoun
  i: ["h₁", "é", "ǵ", "h₂"],
  you: ["t", "ú"],
  we: ["w", "é", "y"],
  they: ["t", "ó", "y"],
};

const FREQ: Record<Meaning, number> = {
  water: 0.95, fire: 0.85, mother: 0.95, father: 0.95, child: 0.9,
  eye: 0.9, foot: 0.9, hand: 0.9, heart: 0.85, head: 0.85,
  go: 0.97, come: 0.96, eat: 0.95, drink: 0.94, see: 0.95, hear: 0.92,
  one: 0.98, two: 0.96, three: 0.94, big: 0.9, small: 0.9,
  i: 0.99, you: 0.99, we: 0.97, this: 0.96, that: 0.96,
  be: 0.99, do: 0.97, make: 0.94, give: 0.93, take: 0.93,
  day: 0.93, night: 0.93, sun: 0.9, moon: 0.85,
  good: 0.92, bad: 0.9, new: 0.85, old: 0.85,
};

const MORPHOLOGY: Morphology = {
  paradigms: {
    "noun.case.nom": { affix: ["s"], position: "suffix", category: "noun.case.nom" },
    "noun.case.acc": { affix: ["m"], position: "suffix", category: "noun.case.acc" },
    "noun.case.gen": { affix: ["e", "s"], position: "suffix", category: "noun.case.gen" },
    "noun.case.dat": { affix: ["e", "y"], position: "suffix", category: "noun.case.dat" },
    "noun.case.loc": { affix: ["i"], position: "suffix", category: "noun.case.loc" },
    "noun.case.inst": { affix: ["b", "ʰ", "i"], position: "suffix", category: "noun.case.inst" },
    "noun.num.pl": { affix: ["e", "s"], position: "suffix", category: "noun.num.pl" },
    "noun.num.du": { affix: ["o", "h₁"], position: "suffix", category: "noun.num.du" },
    "verb.tense.past": { affix: ["e"], position: "prefix", category: "verb.tense.past" },
    "verb.aspect.pfv": { affix: ["e"], position: "suffix", category: "verb.aspect.pfv" },
    "verb.aspect.ipfv": { affix: ["y", "o"], position: "suffix", category: "verb.aspect.ipfv" },
    "verb.person.1sg": { affix: ["m", "i"], position: "suffix", category: "verb.person.1sg" },
    "verb.person.2sg": { affix: ["s", "i"], position: "suffix", category: "verb.person.2sg" },
    "verb.person.3sg": { affix: ["t", "i"], position: "suffix", category: "verb.person.3sg" },
  },
};

export function presetPIE(): SimulationConfig {
  const base = defaultConfig();
  return {
    ...base,
    seed: "pie",
    seedLexicon: LEXICON,
    seedFrequencyHints: FREQ,
    seedMorphology: MORPHOLOGY,
    preset: "pie",
  };
}
