import type { SimulationConfig, Lexicon, Meaning } from "../types";
import type { Morphology } from "../morphology/types";
import { defaultConfig } from "../config";

const LEXICON: Lexicon = {
  water: ["t", "e", "l", "o"],
  fire: ["s", "e", "l", "i"],
  stone: ["k", "i", "w", "e", "n"],
  tree: ["k", "a", "s", "i"],
  sun: ["s", "u", "n", "o"],
  moon: ["m", "u", "n"],
  star: ["m", "u", "n"],
  night: ["p", "i", "m", "e", "j", "a"],
  day: ["s", "u", "n", "o"],
  sky: ["s", "e", "w", "i"],
  earth: ["m", "a"],
  sea: ["t", "e", "l", "o"],

  head: ["l", "a", "w", "a"],
  eye: ["l", "u", "k", "i", "n"],
  mouth: ["u", "t", "a"],
  ear: ["k", "u", "t", "e"],
  hand: ["l", "u", "k", "a"],
  foot: ["n", "o", "k", "a"],
  body: ["s", "i", "j", "e", "l", "o"],
  skin: ["s", "e", "l", "o"],
  bone: ["k", "i", "w", "e", "n"],
  blood: ["t", "e", "l", "o"],
  hair: ["l", "i", "n", "j", "a"],
  nose: ["n", "e", "n", "a"],
  heart: ["p", "i", "l", "i", "n"],

  mother: ["m", "a", "m", "a"],
  father: ["m", "a", "m", "a"],
  child: ["j", "a", "n"],
  friend: ["j", "a", "n"],
  wife: ["m", "e", "l", "i"],
  husband: ["m", "i", "j", "e"],

  go: ["t", "a", "w", "a"],
  come: ["t", "a", "w", "a"],
  see: ["l", "u", "k", "i", "n"],
  know: ["s", "o", "n", "a"],
  eat: ["m", "o", "k", "u"],
  drink: ["m", "o", "k", "u"],
  sleep: ["l", "a", "p", "e"],
  die: ["m", "o", "l", "i"],
  speak: ["t", "o", "k", "i"],
  hear: ["k", "u", "t", "e"],
  fight: ["u", "t", "a", "l", "a"],
  work: ["p", "a", "l", "i"],
  give: ["p", "a", "n", "a"],
  open: ["o", "p", "e", "n"],
  stay: ["a", "w", "e", "n"],

  dog: ["s", "o", "w", "e", "l", "i"],
  cow: ["s", "o", "w", "e", "l", "i"],
  wolf: ["s", "o", "w", "e", "l", "i"],
  horse: ["s", "o", "w", "e", "l", "i"],
  fish: ["k", "a", "l", "a"],
  bird: ["w", "a", "s", "o"],
  snake: ["p", "i", "p", "i"],
  cat: ["s", "o", "w", "e", "l", "i"],
  bear: ["s", "o", "w", "e", "l", "i"],

  flower: ["k", "a", "s", "i"],
  fruit: ["k", "i", "l", "i"],
  seed: ["k", "i", "l", "i"],
  leaf: ["l", "i", "p", "u"],

  good: ["p", "o", "n", "a"],
  bad: ["i", "k", "e"],
  big: ["s", "u", "l", "i"],
  small: ["l", "i", "l", "i"],
  new: ["s", "i", "n"],
  old: ["t", "e", "n", "p", "o"],
  hot: ["s", "e", "l", "i"],
  cold: ["l", "e", "t", "e"],
  hard: ["k", "i", "w", "e", "n"],
  soft: ["k", "o"],
  strong: ["w", "a", "w", "a"],
  weak: ["l", "i", "l", "i"],
  long: ["l", "i", "n", "j", "a"],
  short: ["l", "i", "l", "i"],

  i: ["m", "i"],
  you: ["s", "i", "n", "a"],
  they: ["o", "n", "a"],
  we: ["m", "i"],
  "he-she": ["o", "n", "a"],
  this: ["n", "i"],
  that: ["n", "i"],

  one: ["w", "a", "n"],
  two: ["t", "u"],
  three: ["m", "u", "t", "e"],
  many: ["m", "u", "t", "e"],
  few: ["l", "i", "l", "i"],

  name: ["n", "i", "m", "i"],
  word: ["n", "i", "m", "i"],
  song: ["k", "a", "l", "a", "m", "a"],
  home: ["t", "o", "m", "o"],
  village: ["m", "a"],
  road: ["n", "a", "s", "i", "n"],
  love: ["o", "l", "i", "n"],
  war: ["u", "t", "a", "l", "a"],
  free: ["k", "e", "n"],
  spirit: ["k", "o", "n"],
  god: ["s", "e", "w", "i"],
  law: ["l", "a", "w", "a"],
  gift: ["p", "a", "n", "a"],
  story: ["t", "o", "k", "i"],
  he: ["o", "n", "a"],
  she: ["o", "n", "a"],
  it: ["n", "i"],
  and: ["e", "n"],
  or: ["a", "n", "u"],
  not: ["a", "l", "a"],
  in: ["l", "o", "n"],
  on: ["s", "u", "p", "a"],
  to: ["t", "a", "w", "a"],
  for: ["t", "a", "w", "a"],
  by: ["k", "e", "p", "e", "k", "e", "n"],
  yellow: ["j", "e", "l", "o"],
  red: ["l", "o", "j", "e"],
  blue: ["l", "a", "s", "o"],
  green: ["l", "a", "s", "o"],
  white: ["w", "a", "l", "o"],
  black: ["p", "i", "m", "e", "j", "a"],
  time: ["t", "e", "n", "p", "o"],
  thing: ["i", "j", "o"],
  all: ["a", "l", "i"],
  become: ["k", "a", "m", "a"],
};

const FREQ: Record<Meaning, number> = {
  i: 0.98, you: 0.98, good: 0.95, bad: 0.9,
  water: 0.9, fire: 0.85, eat: 0.9, see: 0.9,
  big: 0.85, small: 0.85, speak: 0.9,
};

const MORPHOLOGY: Morphology = { paradigms: {} };

const RULE_BIAS: Record<string, number> = {
  lenition: 0.5,
  fortition: 0.5,
  place_assim: 0.8,
  palatalization: 1,
  vowel_shift: 0.9,
  vowel_reduction: 0.7,
  harmony: 0.8,
  deletion: 0.6,
  metathesis: 0.1,
  tone: 0.1,
};

export function presetTokipona(): SimulationConfig {
  const base = defaultConfig();
  return {
    ...base,
    seed: "tokipona",
    seedLexicon: LEXICON,
    seedFrequencyHints: FREQ,
    seedMorphology: MORPHOLOGY,
    seedStressPattern: "initial",
    seedGrammar: {
      wordOrder: "SVO",
      articlePresence: "none",
      caseStrategy: "preposition",
      adjectivePosition: "pre",
      possessorPosition: "pre",
      synthesisIndex: 1.0,
      hasCase: false,
    },
    preset: "tokipona",
  };
}

export { RULE_BIAS as TOKIPONA_RULE_BIAS };
